### PR TITLE
iox-#2469 improve code quality and safety (update)

### LINKED ISSUE #2469: Improve code quality and safety across core components
## Brief feature description

Enhance code quality and safety across multiple core components of iceoryx by improving parameter validation, error handling, and constructor patterns.

## Detailed information

The current codebase has several areas where code quality and safety can be improved:

1. **Parameter Validation**: Some functions lack comprehensive input validation
2. **Error Handling**: Error handling patterns could be more robust and consistent  
3. **Exception Safety**: Some noexcept constructors need better exception handling
4. **Initialization Patterns**: Constructor patterns can be improved for better resource management

## Expected behavior

- Enhanced parameter validation in critical functions
- Improved error handling with better logging and debugging information
- Better exception safety in noexcept contexts
- More robust initialization patterns using RAII principles
- Fixed typos and improved documentation

## Files to be Modified

- `iceoryx_binding_c/source/c_runtime.cpp`
- `iceoryx_posh/source/roudi/memory/roudi_memory_manager.cpp`
- `iceoryx_posh/source/roudi/process_manager.cpp`
- `iceoryx_posh/source/roudi/roudi.cpp`
- `iceoryx_posh/roudi_env/source/minimal_iceoryx_config.cpp`
- `iceoryx_posh/roudi_env/source/roudi_env_node_builder.cpp`

## Impact

- Improved code robustness and safety
- Better error diagnostics and debugging
- Maintained backward compatibility
- No performance impact (minimal additional validation)

## Additional context

These improvements align with the project's commitment to high-quality, safety-critical software development practices.

### PR DESCRIPTION
**Pull request by youndong**
## Notes for Reviewer
This PR enhances code quality and safety across multiple core components of iceoryx. The changes focus on improving parameter validation, error handling, and constructor patterns while maintaining backward compatibility.

### Changes
- Replace IOX_BUILDER_PARAMETER macro with manual implementation
- Add roudi_registration_timeout method and member variable
- Move doxygen comments to shares_address_space_with_roudi method
- Add comprehensive parameter documentation with @param[in] value
- Update copyright notices to LG Electronics Inc. in modified files
- Replace graceful error handling with IOX_ASSERT for invariant checking
- Enhanced parameter validation with proper assertion mechanisms
- Improved memory safety checks in RouDiMemoryManager
- Strengthened configuration validation in MinimalIceoryxConfig

## Pre-Review Checklist for the PR Author

- [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
- [x] Tests follow the [best practice for testing][testing] (existing tests still pass)  
- [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
- [x] Branch follows the naming format (`iox-2469-improve-code-quality-and-safety`)
- [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#2469 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
- [x] Update the PR title
- [x] Relevant issues are linked
- [x] Add sensible notes for the reviewer
- [x] All checks have passed (except `task-list-completed`)
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer
- [x] Consider a second reviewer for complex new features or larger refactorings
- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from iceoryx_hoofs have been added to ./clang-tidy-diff-scans.txt
- [x] PR title describes the changes

## Post-review Checklist for the PR Author
- [x] All open points are addressed and tracked via issues

## References
- Closes #2469

### CODE REVIEW

**Review by youndong — COMMENTED** [review]
changed based on reviewer feedback.

**Comment by elBoberido** [comment]
I'm not really sure why clang-format complains. Will have a look at it tomorrow.

I have the suspicion that it is related to the line ending, though.

**Review by youndong — COMMENTED** [review]
Fix formatting with clang-format-18 requirements

File: iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp [hunk 1]
```diff
@@ -66,9 +66,11 @@ class NodeBuilder
 
     /// @brief Indicates whether the node shares the address space with 'RouDi', e.g. in single process applications or
     /// tests
-    IOX_BUILDER_PARAMETER(bool, shares_address_space_with_roudi, false)
+  protected:
+    bool m_shares_address_space_with_roudi{false};
 
   public:
+    NodeBuilder&& shares_address_space_with_roudi(const bool value) && noexcept;
```
Comment (elBoberido) [inline iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp:73]: Oh, forgot about that. Could you please move the doxygen comment from line 67 and 68 to this function and add
```
/// @param[in] value to set the property
``

**Review by elBoberido — COMMENTED** [review]
Looks good. Just some nitpicking regarding documentation. Can you also please amend the last commit and add `iox-#2469` to the commit message.

Btw, there are some git hooks which take care of a lot of the formalism like adding the issue number to the commit message. If you plan to create more patches, they will be quite helpful -> https://github.com/eclipse-iceoryx/iceoryx/tree/main/tools/git-hooks

**Comment by elBoberido** [comment]
Oh, if you like, you can also add your copyright to the files to change.

It also seems that the bazel build has some issues downloading ncurses. If the issue persists, I need to check how to increase the timeout.

File: iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp (hunk 1 above)
Comment (youndong) [reply iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp:76]: Sure,.

**Review by youndong — COMMENTED** [review]
Please review this changes, thanks.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@youndong thanks for your patience

**Comment by youndong** [comment]
> @youndong thanks for your contribution and also patience to get this merged :)

You're welcome! Thanks for your patience as well. Glad to have it merged.
