### PR TITLE
iox-1689 cleanup todo comments

### LINKED ISSUE #1689: Cleanup todo comments in `iceoryx_hoofs`
## Brief feature description

Every todo entry, no matter cmake or cpp file, should start with `@todo iox-#???` with a valid ticket number and a short explanation what has to be additionally.

Furthermore we require a CI check that verifies that all todo comments follow the syntax.

### LINKED ISSUE #1694: Broken MSVC compiler leads to ifdef in optional
## Brief feature description

The compiler bug in the msvc described in here 
https://developercommunity.visualstudio.com/content/problem/858688/stdforward-none-of-these-2-overloads-could-convert.html

is at the moment fixed with a `ifdef` platform macro in `optional<T>::operator=(U&& newValue) noexcept` in the `cxx::optional`.

We should check if the bug is now fixed and we can remove the platform dependent macro or that we find a sustainable solution which handles this without any macro.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1689 
- Closes #1694

### CODE REVIEW

File: iceoryx_examples/icediscovery/include/discovery_monitor.hpp [hunk 1]
```diff
@@ -41,7 +41,7 @@ class Discovery
     /// @brief register a callback to be executed on any service discovery change
     /// @param callback callback with signature void(ServiceDiscovery& discovery)
     /// @note callback is executed in a background thread
-    /// @todo signature of callback is due to the listener signature requirement
+    /// @note signature of callback is due to the listener signature requirement
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_examples/icediscovery/include/discovery_monitor.hpp:44]: This note reads a bit like a todo. Maybe #1200 would match?

File: iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp [hunk 2]
```diff
@@ -101,7 +101,6 @@ class PointerRepository
     id_t searchId(ptr_t ptr) const noexcept;
 
   private:
-    /// @todo: if required protect vector against concurrent modification
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: The following lines belong to the todo as well. I'm not sure if we should remove the todo. Maybe we could add it as a low prio task to #605  :thinking:

File: iceoryx_hoofs/testing/CMakeLists.txt [hunk 3]
```diff
@@ -17,7 +17,7 @@
 #
 ########## set hoofs internal target, needed by tests in components ##########
 #
-# TODO: we need something like internal public for internal build dependencies
+# @todo iox-#1690 we need something like internal public for internal build dependencies
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_hoofs/testing/CMakeLists.txt:20]: See @elBoberido's [comment](https://github.com/eclipse-iceoryx/iceoryx/issues/1690#issuecomment-1262680953)

File: iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp (hunk 2 above)
Comment (mossmaurice) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: @FerdinandSpitzschnueffler @elfenpiff I would not add this to #605 but replace it with a comment, that the `PointerRepository` is not thread-safe.

Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: Not threadsafe? This might be a problem. We have to check if memory synchronization issues can arise.

Scenario:
- thread A is started
- thread B is started
- thread A registers a pointer
- thread B registers a pointer -> is this a valid use case
- thread B uses a relative pointer -> do we need to sync the memory

cc @MatthiasKillat maybe a whiteboard session at some time

Comment (elfenpiff) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: @FerdinandSpitzschnueffler @mossmaurice we only mark thread-safe classes with a comment that they are thread-safe. All other classes are by default non-thread-safe.
If we start this here we may start a fire ...

Comment (elfenpiff) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: @elBoberido this is your first and last warning. You are in vacation!

Maybe this was just a trap to lure you out of your cosy hammock. The next thing you should do is go to the next bar with your laptop and trade it against at least 5 cocktails or maybe 6. :cocktail:

Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: @elfenpiff that's not quite correct. My vacation starts tomorrow ;)

Comment (elfenpiff) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: @mossmaurice @FerdinandSpitzschnueffler @MatthiasKillat  ( and NOT @elBoberido  )

I created an issue: https://github.com/eclipse-iceoryx/iceoryx/issues/1701 to track this but I would define it out of scope for this PR.

Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp:104]: Fine for me but I still think that the following lines belong to the removed comment. Either remove them as well or replace the `todo` with `note`.

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

**Comment by FerdinandSpitzschnueffler** [comment]
Seems like the last two commit messages are not signed.

**Review by mossmaurice — DISMISSED** [review]
Thanks for this PR! Nifty new CI checker :clap:

File: iceoryx_examples/ice_access_control/iox_cheeky_app.cpp [hunk 4]
```diff
@@ -30,7 +30,7 @@ int main()
     // When starting this app with the user 'notallowed'
 
     // 1) Subscribers can be created without any readable shared memory segment
-    /// @todo currently segfaults, in this case no data should ever arrive
+    /// @todo iox-#1708 currently segfaults, in this case no data should ever arrive
```
Comment (mossmaurice) [inline iceoryx_examples/ice_access_control/iox_cheeky_app.cpp:33]:
```suggestion
    /// @todo iox-#722 currently segfaults, in this case no data should ever arrive
```

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp [hunk 5]
```diff
@@ -62,7 +62,6 @@ class PortManager
 
     virtual ~PortManager() noexcept = default;
 
-    /// @todo Remove this later
```
Comment (mossmaurice) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:65]: @elfenpiff Shouldn't this be taken to an issue where the introspection can be disabled with a compile time switch?

File: iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp [hunk 6]
```diff
@@ -36,7 +36,6 @@ iox::config::TomlGatewayConfigParser::parse(const roudi::ConfigFilePathString_t&
         return iox::cxx::success<GatewayConfig>(config);
     }
 
-    /// @todo Replace with C++17 std::filesystem::exists()
```
Comment (mossmaurice) [inline iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp:39]: We should create a C++17 issue!

Comment (elfenpiff) [reply iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp:39]: No this is over engineering. Our file class solves the problem as well. The code the user would have to write with the new approach would even increase - but I admit it would be a little bit more readable.

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp (hunk 5 above)
Comment (elfenpiff) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:65]: Do you have an issue number for me. Otherwise I would remove it, this has to be refactored heavily and we also had enough issues in the code which were pointing to already closed issues.

File: iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp (hunk 6 above)
Comment (mossmaurice) [reply iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp:39]: You understood me wrong, I didn't me a C++17 todo issue which is linked in lots of different places in the code. But instead an issue for C++17 where we collect all cool features that we're longing for to use :man_technologist:

Comment (elfenpiff) [reply iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp:39]: I created one, see: https://github.com/eclipse-iceoryx/iceoryx/issues/1718

File: iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp [hunk 7]
```diff
@@ -72,7 +72,7 @@ typedef testing::Types<uint8_t, int8_t, double> Types;
 
 TYPED_TEST_SUITE(RelativePointer_test, Types, );
 
-/// @todo #605 the tests should be reworked in a refactoring of relative pointers
+/// @todo iox-#605 the tests should be reworked in a refactoring of relative pointers
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp:75]: This issue was already closed so I reopened it again.

File: iceoryx_hoofs/testing/CMakeLists.txt [hunk 8]
```diff
@@ -17,7 +17,7 @@
...
 # instead of making the whole source folder public for internal dependency resolution
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_hoofs/testing/CMakeLists.txt:21]: According to the mentioned issue, these lines can be removed.

File: iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp [hunk 9]
```diff
@@ -48,7 +48,7 @@ enum class ChunkDistributorError
 /// This ChunkDistributor can be used with different LockingPolicies for different scenarios
 /// When different threads operate on it (e.g. application sends chunks and RouDi adds and removes queues),
 /// a locking policy must be used that ensures consistent data in the ChunkDistributorData.
-/// @todo There are currently some challenge:
+/// @todo iox-#1713 There are currently some challenge:
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp:51]:
```suggestion
/// @todo iox-#1713 There are currently some challenges:
```

File: iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl [hunk 10]
```diff
@@ -21,7 +21,7 @@ namespace iox
 {
 namespace popo
 {
-/// @todo Add min() without reference to iox::algorithm?! C++11 needs a declaration for constexpr!
+/// @todo iox-#1712 Add min() without reference to iox::algorithm?! C++11 needs a declaration for constexpr!
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl:24]:
```suggestion
/// @todo iox-#1712 Add minVal() without reference to iox::algorithm?! C++11 needs a declaration for constexpr!
```

File: iceoryx_posh/source/capro/service_description.cpp [hunk 11]
```diff
@@ -229,15 +229,15 @@ bool serviceMatch(const ServiceDescription& first, const ServiceDescription& sec
 
 std::ostream& operator<<(std::ostream& stream, const ServiceDescription& service) noexcept
 {
-    /// @todo #415 Add classHash, scope and interface
+    /// @todo iox-#1715 Add classHash, scope and interface
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/source/capro/service_description.cpp:232]:
```suggestion
    /// @todo iox-#1141 Add classHash, scope and interface
```

File: iceoryx_posh/source/capro/service_description.cpp [hunk 12]
```diff
@@ -229,15 +229,15 @@ bool serviceMatch(const ServiceDescription& first, const ServiceDescription& sec
...
     stream << "Service: " << service.getServiceIDString() << ", Instance: " << service.getInstanceIDString()
            << ", Event: " << service.getEventIDString();
     return stream;
 }
 
 log::LogStream& operator<<(log::LogStream& stream, const ServiceDescription& service) noexcept
 {
-    /// @todo #415 Add classHash, scope and interface
+    /// @todo iox-#1715 Add classHash, scope and interface
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/source/capro/service_description.cpp:240]:
```suggestion
    /// @todo iox-#1141 Add classHash, scope and interface
```

File: iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp (hunk 7 above)
Comment (elfenpiff) [reply iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp:75]: Thank you!

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp (hunk 5 above)
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:65]: @elfenpiff I suppose, #518 would fit best here. An alternative would also be #414
