### PR TITLE
iox-#1076 Introduce `cxx::invoke_result` to solve the deprecated `std::result_of` problem

### LINKED ISSUE #1076: compile error:  std::result_of - deprecated in c++17 and removed in c++20
The use of std::result_of in the project prevents it from being built in C++20 projects;

e.g

iceoryx_hoofs/cxx/type_traits.hpp(66,56): error C2039: 'result_of': is not a member of 'std'

Would you consider replacing it with std::invoke_result or suitable wrappers ?

In the meantime for vc one can reintroduce the templates and get it to compile by defining _HAS_DEPRECATED_RESULT_OF

### LINKED ISSUE #1078: compile error: duration.inl - duration literals are not found
seems like the duration literals are not resolved during compilation of iceoryx_hoofs/internal/units/duration.inl in vs

e.g iceoryx_hoofs/internal/units/duration.inl(79,23): error C3861: '_ns': identifier not found

they are defined later in the header (inline namespace duration_literals)

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer
I fixed the C++20 problem with `std::result_of` and the windows issue with the duration. While fixing this further issues unraveled which had to be fixed as well.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1076 
- Closes #1078

### CODE REVIEW

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 // SPDX-License-Identifier: Apache-2.0
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp:16]: Please adapt the copyright header.

File: iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp [hunk 2]
```diff
@@ -48,9 +48,9 @@ struct Win32CallReturn<void>
```
Comment (mossmaurice) [inline iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp:48]: Please adapt the copyright header.

**Review by mossmaurice — COMMENTED** [review]
LGTM, two small nitpicks

**Review by elBoberido — COMMENTED** [review]
Looks good. Please update the copyright like @mossmaurice suggests

File: iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl [hunk 3]
```diff
@@ -21,6 +21,46 @@ namespace iox
 {
```
Comment (elBoberido) [inline iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl:21]: please update copyright

**Review by elBoberido — COMMENTED** [review]
Looks good. Please update copyright

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp (hunk 1 above)
Comment (elfenpiff) [reply iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp:16]: Everything is correct in there, Apex.AI is only in the first line. Woohoo

**Review by elBoberido — DISMISSED** [review]

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp (hunk 1 above)
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp:16]: Argh it has happened again :sweat_smile:  Can we please swap the lines? :rofl:

File: iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp [hunk 4]
```diff
@@ -38,7 +38,7 @@ enum class TimeSpecReference
 
 class Duration;
 
-inline namespace duration_literals
+namespace duration_literals
```
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp:41]: I am strongly against it.

Just assume that we have a unit like length and here we have the literal `m` for meter which is identical for `m` in minutes. Then we have ambiguous symbols.

And yes you are right, the STL actually does it like that and this is in my opinion not a good approach because of the reason stated above. But the stl does not have a unit like meter - not yet - but if they gonna get one I bet the stl will become even more complex to handle the problem above.

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp:16]: Oh, right. Most probably there was a merge last year which shuffled this around

**Comment by elBoberido** [comment]
Please fix the copyright header before this is merged. Noticed to late that there is a remaining issue

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp (hunk 1 above)
Comment (elfenpiff) [reply iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp:16]: @mossmaurice Declined! According to our contribution.md it is chronological and Apex was first here.

**Review by mossmaurice — APPROVED** [review]
