### PR TITLE
iox-#2157 Replace uint32_t with uint64_t for payload size

### LINKED ISSUE #2157: Allow For memory chunks bigger than 4GB
As discussed this seems to be a "technical unnecessary restriction."
From my experiments it seems possible to fix it by tweaking some of the types 

### Discussed in https://github.com/eclipse-iceoryx/iceoryx/discussions/2149

<div type='discussions-op-text'>

<sup>Originally posted by **kozakusek** January  3, 2024</sup>
When trying to start RouDi with a 4GB segment.mempool I encountered an unpleasant error:

```
 Condition: (t >= Minimum) && (t <= Maximum) in iox::range<T, Minimum, Maximum>::range(T) [with T = unsigned int; T Minimum = 1; T Maximum = 4294967255] is violated. (/workdir/iceoryx/iceoryx_hoofs/primitives/include/iox/algorithm.hpp:208)
```

Then after reading into the source code I noticed that in many cases (e.g. `iox_pub_loan_chunk`) the variable that refers to size is of type `uint32_t`.

Is there a reason for this limitation? Are you planning to add support for bigger memory chunks by adding option to hold size in 64bit integers?

Thanks</div>

### PR DESCRIPTION
**Pull request by kozakusek**
## Pre-Review Checklist for the PR Author

1. [x] Add a second reviewer for complex new features or larger refactorings
1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #2157

### CODE REVIEW

**Comment by elBoberido** [comment]
@kozakusek commit message is fine. Now the more tedious work starts to make it work on all platforms :)

**Comment by elBoberido** [comment]
It seems the code is not formatted with clang-format. You can use `tools/git-hooks` to automate some of the stuff which is checked by the CI, e.g. formatting the code or adding the issue number to the commit messages

**Comment by kozakusek** [comment]
@elBoberido the biggest issue I see now  is that 
- *TooLargeUserPayload_Fails tests are no longer relevant and
- I might not fully get the idea behind CHUNK_HEADER_VERSION and the threats in chunk_header.hpp: "m_chunkSize and m_chunkHeaderVersion should therefore neither changed the type, nor the position" which might be the cause for failure for the other three tests

**Comment by elBoberido** [comment]
@kozakusek I did a stupid mistake when I put `chunkSize` at the beginning of the `ChunkHeader` struct instead of `chunkHeaderVersion`. I never thought the type of `chunkSize` would change but only that maybe new members would be added. The reason for `CHUNK_HEADER_VERSION` and the test is to detect when a subscriber receives a chunk with an incompatible `ChunkHeader`. This can be the case when someone implements something like record&replay and stores all the data. If the the `ChunkHeader` would change after storing the data, a replay would result in weird bugs in the iceoryx layer. The issue we need to solve now is to keep the `chunkHeaderVersion` at an offset of 32 bits in the `ChunkHeader` struct. I think this can be achieved by swapping `userHeaderSize` with `chunkSize`. I need to check whether this would cause other issues but I think we should be safe.

**Comment by kozakusek** [comment]
So one last thing before I open this for review - should I add a unit test for memory chunks > 4GB?
Do the CI machines have enough RAM for this?

**Comment by elBoberido** [comment]
> So one last thing before I open this for review - should I add a unit test for memory chunks > 4GB? Do the CI machines have enough RAM for this? @elBoberido could you confirm?

Unfortunately the CI seems to not reliably have that much memory. AFAIR we already had to deactivate on test which required > 4GB. I need to check what changed maybe it is possible to mock a few things and test at least the algorithm.

**Comment by kozakusek** [comment]
Cleaned up the mess in examples and tests.
Hopefully fixed the issue with building on Mac.
Let me know if I and how should I mock 'stuff' for testing

**Comment by elBoberido** [comment]
CI looks good. Thanks. Will have a look at the changes the next days.

**Review by elBoberido — COMMENTED** [review]
Will continue tomorrow, it's already quite late. Just had a look at the C binding and the release notes

File: iceoryx_posh/source/mepoo/chunk_settings.cpp [hunk 1]
```diff
@@ -66,18 +66,10 @@ expected<ChunkSettings, ChunkSettings::Error> ChunkSettings::create(const uint32
...
-    return ok(ChunkSettings{userPayloadSize,
-                            adjustedUserPayloadAlignment,
-                            userHeaderSize,
-                            adjustedUserHeaderAlignment,
-                            static_cast<uint32_t>(requiredChunkSize)});
+    return ok(ChunkSettings{
+        userPayloadSize, adjustedUserPayloadAlignment, userHeaderSize, adjustedUserHeaderAlignment, requiredChunkSize});
 }
-uint64_t ChunkSettings::calculateRequiredChunkSize(const uint32_t userPayloadSize,
+uint64_t ChunkSettings::calculateRequiredChunkSize(const uint64_t userPayloadSize,
```
Comment (elBoberido) [inline iceoryx_posh/source/mepoo/chunk_settings.cpp:72]: Here we definitely needs  changes since the calculation could easily result in an overflow. It was easier when the input parameter were `uint32_t`.

Luckily we already moved to the static creation method pattern instead of calling the ctor explicitly and therefore we can also use an `iox::expected` here and forward the error in the `create` method

File: iceoryx_posh/source/mepoo/mem_pool.cpp [hunk 2]
```diff
@@ -39,7 +39,7 @@ MemPoolInfo::MemPoolInfo(const uint32_t usedChunks,
 
 constexpr uint64_t MemPool::CHUNK_MEMORY_ALIGNMENT;
 
-MemPool::MemPool(const greater_or_equal<uint32_t, CHUNK_MEMORY_ALIGNMENT> chunkSize,
+MemPool::MemPool(const greater_or_equal<uint64_t, CHUNK_MEMORY_ALIGNMENT> chunkSize,
```
Comment (elBoberido) [inline iceoryx_posh/source/mepoo/mem_pool.cpp:42]: Here we also need to check for potential overflows when `chunkSize` is multiplied with `numberOfChunks`

File: iceoryx_posh/test/moduletests/test_popo_server_port_common.hpp [hunk 3]
```diff
@@ -222,8 +222,8 @@ class ServerPort_test : public Test
     iox::optional<SutServerPort> clientPortForStateTransitionTests;
 
   public:
-    static constexpr uint32_t USER_PAYLOAD_SIZE{32U};
-    static constexpr uint32_t USER_PAYLOAD_ALIGNMENT{8U};
+    static constexpr uint64_t USER_PAYLOAD_SIZE{32U};
+    static constexpr uint64_t USER_PAYLOAD_ALIGNMENT{8U};
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_popo_server_port_common.hpp:226]: The alignment could stay as `uint32_t`

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 4]
```diff
@@ -261,8 +261,8 @@ TEST_F(PublisherPort_test, allocatingAChunkWithoutUserHeaderAndLargeUserPayloadA
 TEST_F(PublisherPort_test, allocatingAChunkWithLargeUserHeaderResultsInLargeChunk)
 {
     ::testing::Test::RecordProperty("TEST_ID", "598e04d8-8a37-43ef-b686-64e7b2723ffe");
-    constexpr uint32_t USER_PAYLOAD_SIZE{SMALL_CHUNK / 2};
-    constexpr uint32_t LARGE_USER_HEADER_SIZE{SMALL_CHUNK};
+    constexpr uint64_t USER_PAYLOAD_SIZE{SMALL_CHUNK / 2};
+    constexpr uint64_t LARGE_USER_HEADER_SIZE{SMALL_CHUNK};
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:265]: This could also stay `uint32_t`

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 5]
```diff
@@ -63,10 +63,10 @@ class PublisherPort_test : public Test
     static constexpr size_t MEMORY_SIZE = 1024 * 1024;
     uint8_t m_memory[MEMORY_SIZE];
     static constexpr uint32_t NUM_CHUNKS_IN_POOL = 20;
-    static constexpr uint32_t SMALL_CHUNK = 128;
-    static constexpr uint32_t BIG_CHUNK = 256;
+    static constexpr uint64_t SMALL_CHUNK = 128;
+    static constexpr uint64_t BIG_CHUNK = 256;
 
-    static constexpr uint32_t USER_PAYLOAD_ALIGNMENT = iox::CHUNK_DEFAULT_USER_PAYLOAD_ALIGNMENT;
+    static constexpr uint64_t USER_PAYLOAD_ALIGNMENT = iox::CHUNK_DEFAULT_USER_PAYLOAD_ALIGNMENT;
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:69]: This also. If you changed it to prevent casts in the tests, then this can be left as it is now.

File: iceoryx_posh/test/moduletests/test_popo_client_port.cpp [hunk 6]
```diff
@@ -206,8 +206,8 @@ class ClientPort_test : public Test
     iox::optional<SutClientPort> clientPortForStateTransitionTests;
 
   public:
-    static constexpr uint32_t USER_PAYLOAD_SIZE{32U};
-    static constexpr uint32_t USER_PAYLOAD_ALIGNMENT{8U};
+    static constexpr uint64_t USER_PAYLOAD_SIZE{32U};
+    static constexpr uint64_t USER_PAYLOAD_ALIGNMENT{8U};
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_popo_client_port.cpp:210]: Same here, `uint32_t`

File: iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp [hunk 7]
```diff
@@ -72,12 +72,12 @@ class ChunkSender_test : public Test
...
     static constexpr uint32_t NUM_CHUNKS_IN_POOL = 20;
-    static constexpr uint32_t SMALL_CHUNK = 128;
-    static constexpr uint32_t BIG_CHUNK = 256;
+    static constexpr uint64_t SMALL_CHUNK = 128;
+    static constexpr uint64_t BIG_CHUNK = 256;
     static constexpr uint64_t HISTORY_CAPACITY = 4;
     static constexpr uint32_t MAX_NUMBER_QUEUES = 128;
 
-    static constexpr uint32_t USER_PAYLOAD_ALIGNMENT = iox::CHUNK_DEFAULT_USER_PAYLOAD_ALIGNMENT;
+    static constexpr uint64_t USER_PAYLOAD_ALIGNMENT = iox::CHUNK_DEFAULT_USER_PAYLOAD_ALIGNMENT;
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp:80]: Also `uint32_t`

File: iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp [hunk 8]
```diff
@@ -183,7 +183,7 @@ TEST_F(MemPool_test, MempoolCtorWhenChunkSizeIsNotAMultipleOfAlignmentReturnErro
 TEST_F(MemPool_test, MempoolCtorWhenChunkSizeIsSmallerThanChunkMemoryAlignmentGetsTerminated)
 {
     ::testing::Test::RecordProperty("TEST_ID", "52df897a-0847-476c-9d2f-99cb16432199");
-    constexpr uint32_t CHUNK_SIZE_SMALLER_THAN_MEMORY_ALIGNMENT = iox::mepoo::MemPool::CHUNK_MEMORY_ALIGNMENT - 1U;
+    constexpr uint64_t CHUNK_SIZE_SMALLER_THAN_MEMORY_ALIGNMENT = iox::mepoo::MemPool::CHUNK_MEMORY_ALIGNMENT - 1U;
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp:186]: Also `uint32_t`

**Review by elBoberido — COMMENTED** [review]
Not yet fully done. I have saved some of the critical files for tomorrow :)

Btw, please don't squash commits from now on since this will make the review harder and there are subtle thinks to look at.

File: iceoryx_posh/source/mepoo/chunk_settings.cpp (hunk 1 above)
Comment (elfenpiff) [reply iceoryx_posh/source/mepoo/chunk_settings.cpp:72]: @elBoberido I think having an overflow here is most likely caused by just a programming mistake, and therefore I would vote to use `IOX_ENSURES` here and panic when this occurs. I cannot imagine a use case where an overflow can happen, and it is a real world example.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 2 above)
Comment (elfenpiff) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:42]: @elBoberido yes, but I would call here again panic and not work with an expected.

**Review by elfenpiff — CHANGES_REQUESTED** [review]
Since this affects a lot of files and from the comments from @elBoberido I saw that there are maybe even more places where we overlooked to change an `uint32_t` to an `uint64_t`. This could result in weird unsigned integer overflow bugs.

Therefore, I would add a test that verifies that payloads larger than 4GB are actually supported. Those tests shall be added to:
* `iceoryx_posh/test/integrationtests/test_client_server.cpp`
* `iceoryx_posh/test/integrationtests/test_publish_subscriber_communication.cpp`

I would introduce a test struct like:
```cxx
struct LargeData {
  uint8_t payload[4294967296 + 100]; // + 100 to be 100 bytes above the original limit
};
```

And use it for the typed communication. Also we need to adjust the roudi config to support those large structs. I think this should work in the test setup

```cxx
RouDi_GTest(MinimalRouDiConfigBuilder().payloadChunkSize(4294967296 + 100).payloadChunkCount(2).create());
```

I would test both cases, one with the typed API and one with the untyped API. If this is too complex or time-consuming, I would also accept just a test with one of the APIs.

File: iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp [hunk 9]
```diff
@@ -35,12 +35,12 @@ struct MePooConfig
     struct Entry
     {
         /// @brief set the size and count of memory chunks
-        Entry(uint32_t f_size, uint32_t f_chunkCount) noexcept
+        Entry(uint64_t f_size, uint32_t f_chunkCount) noexcept
```
[the remark this answers is not in the document]
Comment (gpalmer-latai) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp:38]: Why is it `f` anyway? I would think that that meant "floating point".

[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp:38]: @gpalmer-latai You are right. That's due to historical reasons using an old coding style.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 2 above)
Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:42]: I'd also like to see an explicit IOX_EXPECTS verifying that `chunkSize` * `numChunks` isn't somehow greater than `numeric_limits<uint64_t>::max`. Such a check would have helped previously when I discovered the `numeric_limits<uint64_t>::max` overflow bug.

File: iceoryx_posh/source/mepoo/mem_pool.cpp [hunk 10]
```diff
@@ -101,14 +101,14 @@ void* MemPool::getChunk() noexcept
     return indexToPointer(index, m_chunkSize, m_rawMemory.get());
 }
 
-void* MemPool::indexToPointer(uint32_t index, uint32_t chunkSize, void* const rawMemoryBase) noexcept
+void* MemPool::indexToPointer(uint32_t index, uint64_t chunkSize, void* const rawMemoryBase) noexcept
 {
     const auto offset = static_cast<uint64_t>(index) * chunkSize;
     return static_cast<void*>(static_cast<uint8_t*>(rawMemoryBase) + offset);
```
Comment (gpalmer-latai) [inline iceoryx_posh/source/mepoo/mem_pool.cpp:107]: This is more of a comment on the previous change to fix overflow for memory pools spanning more than 4GB. 

Do we have to care about 32-bit operating systems? I.e. should we be using `size_t` and validating while parsing the config and via a few `IOX_ENSURES` statements that we don't overflow `numeric_limits<size_t>::max`? 

Otherwise the pointer arithmetic will simply overflow on those platforms and probably segfault.

Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:107]: In any case I wouldn't require any action in this particular PR. It should be a separate issue.

File: iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp:38]: @gpalmer-latai it was the coding style of we well known German automotive supplier and `f` means `function parameter`. There was also a `l_` prefix for local variables.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 2 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:42]: Well, `chunkSize * numChunks` will never be larger than `numeric_limits<uint64_t>::max` ;)

We have to check whether `numeric_limits<uint64_t>::max / numChunks` is larger or equal to `chunkSize`.

Side note, it is now called `IOX_ENFORCE` :)

I would avoid to panic here, an incorrect size is not different from an incorrect alignment, which also does not panic. Let's keep doing it like the local error handling on the class instead of mixing it. It makes testing also a little bit easier.

File: iceoryx_posh/source/mepoo/chunk_settings.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/chunk_settings.cpp:72]: I would avoid to panic here, an incorrect size is not different from an incorrect alignment, which also does not panic. Let's keep doing it like the local error handling on the class instead of mixing it. It makes testing also a little bit easier.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 10 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:107]: These methods could also easily become private. The only reason they are public is because it was easier to test.

File: iceoryx_posh/source/mepoo/memory_manager.cpp [hunk 11]
```diff
@@ -58,7 +58,7 @@ void MemoryManager::addMemPool(BumpAllocator& managementAllocator,
                 return log;
             } << "These mempools must be added in an increasing chunk size ordering. The newly added  MemPool [ "
                  "ChunkSize = "
-              << adjustedChunkSize << ", ChunkPayloadSize = " << static_cast<uint32_t>(chunkPayloadSize)
+              << adjustedChunkSize << ", ChunkPayloadSize = " << static_cast<uint64_t>(chunkPayloadSize)
               << ", ChunkCount = " << static_cast<uint32_t>(numberOfChunks) << "] breaks that requirement!");
```
Comment (elBoberido) [inline iceoryx_posh/source/mepoo/memory_manager.cpp:62]: Small nitpick. The casts can be removed. There once was a bug in the `LogStream` implementation which was fixed a while back.

No hard requirement for a merge since this was already there, just a nice to have :)

File: iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp [hunk 12]
```diff
@@ -115,61 +115,12 @@ TEST(ChunkSettings_test, CallingRequiredChunkSizeReturnsCorrectValue)
 
 // END GETTER METHOD TESTS
 
-// BEGIN EXCEEDING CHUNK SIZE TESTS
-
-TEST(ChunkSettings_test, NoCustomUserPayloadAlignmentAndTooLargeUserPayload_Fails)
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp:120]: These tests must be added again. Wrong input parameter can still lead to an overflow.

**Review by elBoberido — COMMENTED** [review]
Can you please also update `chunk_header.md` regarding the uint32_t->uint64_t change

File: iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (kozakusek) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp:38]: Does the `m_` prefix, that I've noticed being used in many places, have the same history?

[the remark this answers is not in the document]
Comment (gpalmer-latai) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp:38]: I would assume `m_` means member. I think this one is intended to stay? Unless y'all want to adopt the trailing underscore pattern 😉

[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp]: Yes, `m_` stays. We need some pattern for the members :)

File: iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp [hunk 13]
```diff
@@ -713,4 +743,36 @@ TEST_F(PublisherSubscriberCommunication_test, PublisherUniqueIdMatchesReceivedSa
...
+                         }
+                         sample.publish();
+                     })
+                     .has_error());
+
+    EXPECT_FALSE(subscriber->take()
+                     .and_then([](auto& sample) {
+                         for (uint64_t i = 4242; i < 5353; ++i)
+                         {
+                             EXPECT_THAT(sample->complexType.bigPayload[i], Eq(static_cast<uint8_t>(i % 256U)));
```
Comment (elBoberido) [inline iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp:770]: Please use `ASSERT_THAT` to break out of the for loop after the first failed check.

**Review by elBoberido — COMMENTED** [review]
Looks good. Maybe a few performance improvements for the new tests but they are not that important since we don't run them in the CI.

More important though would be to add the new option to the cmake options. This shouldn't take much time and you can just copy&paste from an existing options.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 14]
```diff
@@ -450,4 +482,127 @@ TEST_F(ClientServer_test, ClientTakesResponseUnblocksServerSendingResponse)
...
+    // send request
+    {
+        auto loanResult = client.loan();
+        ASSERT_FALSE(loanResult.has_error());
+        auto& request = loanResult.value();
+        request.getRequestHeader().setSequenceId(SEQUENCE_ID);
+        for (uint64_t i = START; i < END; ++i)
+        {
+            request->bigPayload[i] = static_cast<uint8_t>(i % 256U);
+        }
```
[the remark this answers is not in the document]
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:508]: Yeah.
Doing it for the whole payload took a lot of time, that is why I reduced it to a smaller part.
However your idea with writing every 4096th element (or even 2048th) makes a lot more sense

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 15]
```diff
@@ -450,4 +482,127 @@ TEST_F(ClientServer_test, ClientTakesResponseUnblocksServerSendingResponse)
     EXPECT_THAT(wasResponseSent.load(), Eq(true));
 }
 
+#ifdef RUN_BIG_PAYLOAD_TESTS
+
+TEST_F(BigPayloadClientServer_test, TypedApiWithBigPayloadWithMatchingOptionsWorks)
+{
+    ::testing::Test::RecordProperty("TEST_ID", "9838d2dc-bd87-42aa-b581-a9526e35e46a");
+
```
[the remark this answers is not in the document]
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:490]: Wouldn't it still cause BigPayloadClientServer_test to be constructed?
This leads to the machine running out of memory either way.
At least IIUC this is what happened in CI when I tried to use `GTEST_SKIP()`

File: iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp (hunk 13 above)
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp:770]: Oh yeah.
Missed that macro.
Makes a lot more sense than having an if with break

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:490]: Yes, you are right. I totally overlooked that. Then lets keep it as is but only add the option to `iceoryx_meta/build_options.cmake`

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@elfenpiff @gpalmer-latai please also have a final look

@kozakusek looks good. Thanks for the contributions. Btw, there is a [developer meetup](https://github.com/eclipse-iceoryx/iceoryx/wiki/Developer-meetup) on each first Tuesday of the month. Would be great to hear more about your use case.

**Comment by gpalmer-latai** [comment]
It seems like it would be a good idea for you to take some credit for your contribution by updating the copyright headers: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/source/mepoo/mem_pool.cpp#L3

Basically put your individual name as @elBoberido has if you signed the eclipse agreement as an individual contributor, or if you are doing this for work purposes and your company cares to claim your IP, you can put their name as well.

File: iceoryx_posh/source/mepoo/chunk_settings.cpp [hunk 16]
```diff
@@ -63,41 +63,50 @@ expected<ChunkSettings, ChunkSettings::Error> ChunkSettings::create(const uint32
...
     // have a look at »Required Chunk Size Calculation« in chunk_header.md for more details regarding the calculation
     if (userHeaderSize == 0)
     {
         // the most simple case with no user-header and the user-payload adjacent to the ChunkHeader
         if (userPayloadAlignment <= alignof(mepoo::ChunkHeader))
         {
+            if (userPayloadSize > std::numeric_limits<uint64_t>::max() - sizeof(ChunkHeader))
+            {
+                return err(ChunkSettings::Error::REQUIRED_CHUNK_SIZE_EXCEEDS_MAX_CHUNK_SIZE);
+            }
```
Comment (gpalmer-latai) [inline iceoryx_posh/source/mepoo/chunk_settings.cpp:90]: Since you've added this (unlikely) error case, it'd probably be good to add a unit test as well that calls the function with exactly the bad threshold size and asserts that an error is returned.

Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/chunk_settings.cpp:90]: Same for the other error case.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 2 above)
Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:42]: Let me rephrase - I'd like a check that the multiplication will not overflow. There is pseudocode for this in this stackoverflow: https://stackoverflow.com/a/1815391

Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:42]: And it looks like the check below does indeed implement the check correctly 👍

File: iceoryx_posh/source/mepoo/mem_pool.cpp [hunk 17]
```diff
@@ -49,6 +49,7 @@ MemPool::MemPool(const greater_or_equal<uint32_t, CHUNK_MEMORY_ALIGNMENT> chunkS
 {
     if (isMultipleOfAlignment(chunkSize))
     {
+        IOX_EXPECTS(m_chunkSize <= std::numeric_limits<uint64_t>::max() / m_numberOfChunks);
```
Comment (gpalmer-latai) [inline iceoryx_posh/source/mepoo/mem_pool.cpp:52]: Nice, thank you.

Very small nit here and in other places. You can use `IOX_EXPECTS_WITH_MSG` to add an explanation of what the failure of this check implies. Like "Requested size of memory pool is greater than the maximum of uint64_t::max()"

**Review by gpalmer-latai — APPROVED** [review]
Left a few suggestions about more extension testing/error messaging, but overall this looks great to me.

File: iceoryx_posh/source/mepoo/chunk_settings.cpp (hunk 16 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/chunk_settings.cpp:90]: If I did not overlook something, there are already test cases for all of the possible errors. It just happend that the checks are now partially at a different location. At least the coverage of these files is 100%

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 17 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:52]: Oh yes, please. This will make my life easier wenn porting to the new macros which require always an error string

File: iceoryx_posh/source/mepoo/chunk_settings.cpp (hunk 16 above)
Comment (gpalmer-latai) [reply iceoryx_posh/source/mepoo/chunk_settings.cpp:90]: Ah okay. I guess I didn't look hard enough and assumed because there wasn't a new unit test calling this function directly and exercising the expected value, it might not be checked. 

But you are right - this is the same error that existed before.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 18]
```diff
@@ -450,4 +482,121 @@ TEST_F(ClientServer_test, ClientTakesResponseUnblocksServerSendingResponse)
...
+    // send request
+    {
+        auto loanResult = client.loan();
+        ASSERT_FALSE(loanResult.has_error());
+        auto& request = loanResult.value();
+        request.getRequestHeader().setSequenceId(SEQUENCE_ID);
+        for (uint64_t i = FIRST; i <= LAST; i += STEP)
+        {
+            request->bigPayload[i] = static_cast<uint8_t>((i / STEP) % 256U);
```
Comment (elfenpiff) [inline iceoryx_posh/test/integrationtests/test_client_server.cpp:508]: (optional) To give more context understanding I would use here `std::numeric_limits<uint8_t>::max()`. Maybe also add a little type alias to `BigPayloadStruct` and use it here.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 19]
```diff
@@ -450,4 +482,121 @@ TEST_F(ClientServer_test, ClientTakesResponseUnblocksServerSendingResponse)
...
+
+    // take response
+    {
+        auto takeResult = client.take();
+        ASSERT_FALSE(takeResult.has_error());
+        auto& response = takeResult.value();
+        EXPECT_THAT(response.getResponseHeader().getSequenceId(), Eq(SEQUENCE_ID));
+        for (uint64_t i = FIRST; i <= LAST; i += STEP)
+        {
+            ASSERT_THAT(response->bigPayload[i], Eq(static_cast<uint8_t>(((i / STEP) % 256U) + SHIFT)));
```
Comment (elfenpiff) [inline iceoryx_posh/test/integrationtests/test_client_server.cpp:537]: (optional) Same here, use numeric limits.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 20]
```diff
@@ -35,6 +35,8 @@ using namespace iox::capro;
 using namespace iox::runtime;
 using namespace iox::roudi_env;
 
+constexpr uint64_t BIG_PAYLOAD_SIZE = std::numeric_limits<uint32_t>::max() + 105UL;
```
Comment (elfenpiff) [inline iceoryx_posh/test/integrationtests/test_client_server.cpp:38]: (optional) I would rename the variable into `PAYLOAD_LARGER_4GB` so that it becomes clearer that we are testing here a payload that exceeds 32-bit.

**Review by elfenpiff — APPROVED** [review]
I have some remarks, but they are purely optional. If you have to touch the PR again, it would be nice if you would incorporate them, otherwise just merge the PR.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp [hunk 21]
```diff
@@ -82,6 +95,25 @@ class ClientServer_test : public RouDi_GTest
 };
 constexpr iox::units::Duration ClientServer_test::DEADLOCK_TIMEOUT;
 
+class BigPayloadClientServer_test : public ClientServer_test
+{
+  public:
+    BigPayloadClientServer_test()
+        : ClientServer_test(
+            MinimalRouDiConfigBuilder().payloadChunkSize(BIG_PAYLOAD_SIZE + 128).payloadChunkCount(2).create())
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:103]: No, this is just an arbitrary number to make sure the payload is larger than 4GB.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 18 above)
Comment (elBoberido) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:508]: `std::numeric_limits<uint8_t>::max().` won't work but yeah, a constexpr for this magic number would be nice. But on the other hand, I think this is not even necessary since the cast to uint8_t does already what wants to be achieved by `%256`.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:103]: Btw, could you increase the size of the payload by at least the step size in the for loop. This is just to ensure to write beyond the 4GB mark.

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 17 above)
Comment (kozakusek) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:52]: Sure
But what do you mean by other places?
I couldn't find any other places around the touched code that would use IOX_EXPECTS and would benefit from the message.
Could you point me to the code you had in mind?

Comment (elBoberido) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:52]: Don't worry, if there is a place without a message it will be added when I port the code the the new macros, which I would start once this PR is merged.

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:103]: > No, this is just an arbitrary number to make sure the payload is larger than 4GB.

Actually this number is included in the constant `BIG_PAYLOAD_SIZE`
This might have been an arbitrary offset that should manage to fit the header

**Comment by kozakusek** [comment]
> It seems like it would be a good idea for you to take some credit for your contribution by updating the copyright headers: https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_posh/source/mepoo/mem_pool.cpp#L3
> 
> Basically put your individual name as @elBoberido has if you signed the eclipse agreement as an individual contributor, or if you are doing this for work purposes and your company cares to claim your IP, you can put their name as well.

Well
Why not
I'll add it in the few files that I've done something more than just change 32 to 64 :D

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 18 above)
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:508]: That's what I wanted to say. 
This modulo is unnecessary here.

I am not sure what would you expect the alias to be.
`uint8_t` is precisely what I needed here and what I am used to use when I refer to 'just some bytes in memory'.

**Comment by elBoberido** [comment]
> Well
> Why not
> I'll add it in the few files that I've done something more than just change 32 to 64 :D

That' s also how I handle it. It must be something more complex than something a trained ferret could have done :laughing:

File: iceoryx_posh/test/integrationtests/test_client_server.cpp (hunk 18 above)
Comment (kozakusek) [reply iceoryx_posh/test/integrationtests/test_client_server.cpp:508]: And I can get rid of the cast.
Good idea

**Review by elBoberido — APPROVED** [review]
Looks good. Every request was implemented. I'm going to merge once the CI is finished. Thanks very much for your contribution and patience. Hope to see you in the developer meetup :)
