### PR TITLE
Iox #495 add gcc 5.4 and latest clang ci job

### LINKED ISSUE #495: fail build on ubuntu 16.04 with g++ 5.4.0
## Required information

**Operating system:**
PRETTY_NAME="Ubuntu 16.04.7 LTS"

**Compiler version:**
Target: x86_64-linux-gnu
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Observed result or behaviour:**
See attached log file [compiler_log_BH1SCW.txt](https://github.com/eclipse-iceoryx/iceoryx/files/6090535/compiler_log_BH1SCW.txt)

**Expected result or behaviour:**
build with no error 

**Conditions where it occurred / Performed steps:**
git commit id:
current master (original f1c4b31c54cc7fccb352fc3cdda562d9a22fe638)

---

Issues:
- [ ] Unsupported compiler command line option `-Wno-noexcept-type`
- [ ] Call to ostream from constexpr function; basically all `clog` calls in `duration.inl`; added in PR #501
   Error: `call to non-constexpr function ‘std::basic_ostream`

### PR DESCRIPTION
**Pull request by dkroenke**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer
Adding CI build for gcc 5.4 and latest clang.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References
Closes #495

### CODE REVIEW

File: iceoryx_utils/test/moduletests/test_posix_mutex.cpp [hunk 1]
```diff
@@ -26,15 +28,6 @@ using namespace iox::units::duration_literals;
 class Mutex_test : public Test
 {
   public:
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_posix_mutex.cpp:30]: I think all of the unit tests can have the potential to deadlock when our mutex implementation is flawed. In this case it would be ideal that the unit tests itself discovers the deadlock and terminates the whole tests so that it is not running forever.
@FerdinandSpitzschnueffler wrote the `iceoryx_utils/testutils/watch_dog.hpp` class, could you please use it here like
```cpp
class Mutex_test : public Test {
   // ...
   iox::units::Duration m_watchdogTimeout = 2_s;
   Watchdog m_deadlockWatchdog(m_watchdogTimeout);
   void SetUp() override {
      // ...
      m_deadlockWatchdog.watchAndActOnFailure([]{ std::terminate(); });
   }
};
```

**Review by elfenpiff — CHANGES_REQUESTED** [review]
Please use the `Watchdog` in the mutex tests to terminate the unit test when a potential deadlock would occur.

File: iceoryx_utils/test/moduletests/test_posix_mutex.cpp [hunk 2]
```diff
@@ -49,28 +44,43 @@ class Mutex_test : public Test
...
-    EXPECT_THAT(sut.try_lock(), Eq(true));
-    EXPECT_THAT(sut.unlock(), Eq(true));
+    EXPECT_THAT(sutNonRecursive.try_lock(), Eq(true));
+    EXPECT_THAT(sutNonRecursive.unlock(), Eq(true));
 }
 
-TEST_F(Mutex_test, TryLockWithLock)
+
+#ifndef _WIN32
+TEST_F(Mutex_test, TryLockWithNonRecursiveLock)
```
Comment (marthtz) [inline iceoryx_utils/test/moduletests/test_posix_mutex.cpp:61]: Could we be a bit more explicit with all the test names in this file? I'm kind of missing the expected result for each test, e.g. `TryLockAfterNonRecursiveLockReturnsFalse` or so. Same for most other tests here.

Comment (dkroenke) [reply iceoryx_utils/test/moduletests/test_posix_mutex.cpp]: Correct, i made them more expressive.

File: iceoryx_utils/test/moduletests/test_posix_mutex.cpp [hunk 3]
```diff
@@ -49,30 +44,45 @@ class Mutex_test : public Test
...
 
+TEST_F(Mutex_test, RepeatedLockAndUnlockWithNonRecursiveMutexReturnsTrue)
+{
+    EXPECT_THAT(sutNonRecursive.lock(), Eq(true));
+    EXPECT_THAT(sutNonRecursive.unlock(), Eq(true));
+    EXPECT_THAT(sutNonRecursive.lock(), Eq(true));
+    EXPECT_THAT(sutNonRecursive.unlock(), Eq(true));
+}
+
+#if !defined(_WIN32) && !defined(QNX) && !defined(QNX__) && !defined(__QNX__) && !defined(__APPLE__)
```
Comment (marthtz) [inline iceoryx_utils/test/moduletests/test_posix_mutex.cpp:83]: I'm getting a bit confused, so, we do **NOT** want to execute this test if the platform is Win, QNX or Apple. Correct?

File: .github/workflows/experimental_build.yml [hunk 4]
```diff
@@ -0,0 +1,79 @@
+# This is a basic workflow to help you get started with Actions
```
Comment (mossmaurice) [inline .github/workflows/experimental_build.yml:1]: Remove this line?

File: .github/workflows/experimental_build.yml [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+
+name: Experimental build
```
Comment (mossmaurice) [inline .github/workflows/experimental_build.yml:3]: Nitpick: What do you think about renaming this workflow to "Specific compiler build"?

**Review by mossmaurice — APPROVED** [review]
LGTM, two nitpicks

File: .github/workflows/experimental_build.yml (hunk 5 above)
Comment (marthtz) [reply .github/workflows/experimental_build.yml:3]: What about "I'm Feeling Lucky Build"? 😄

**Review by marthtz — APPROVED** [review]
