### PR TITLE
Iox #381 Fix flooding the command line and resource leak

### LINKED ISSUE #381: Integration of Unix Domain Sockets
## Brief feature description

Currently the application name has to start with a leading slash. This exposes an implementation details, since that name is used for the message queue name. Since there is already a Unix Domain Abstraction available we can switch now to UDS.

## Detailed information
The default IPC protocol for communication between RouDi and Runtime shall be switched to UDS.
Since the registration at RouDi will happen with with a different IPC mechanism than a message queue, e.g. unix domain sockets, this implementation detail should not be exposed to the user. If the application name is used as name for an IPC channel and this channel has certain requirements for its name, those should be taken care of in the IPC abstraction.

* [x] The check for the leading slash should be removed from the `PoshRuntime`.
* [x] Switch to UDS in `posh_types.hpp` and adapt existing classes and test to the new protocol
  * [x] Rename abstract interface from "MQ" to "IPC" e.g. in RouDi
  * [x] Temporarly disabled outdated and broken `MqInterface*` tests 
* [x] Refactor classes for `MqBase` and `MqInterfaces` to more generic names
  * [x] Split into three hpp/cpp
  * [x] Rename to `IpcInterfaceCreator`, `IpcInterfaceUser`, `IpcBase`, `IpcRuntimeInterface` and `IpcMessage`
  * [x] Delete `mqueue_MOCK`
  * [x] Re-write `iceoryx_posh/test/moduletests/test_mq_interface.cpp` to test only POSH specific functionality of the IpcInterface e.g. `getShmTopic()`, IpcChannel is already covered by `iceoryx_utils/test/moduletests/test_ipc_channel.cpp` (will be addressed in  #332)
* [x] Fix output when publisher or subscriber is started before RouDi, command line is flooded with errors

See also https://github.com/eclipse/iceoryx/pull/373/files#r525981221

### PR DESCRIPTION
**Pull request by mossmaurice**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
* Remove noisy output in `UnixDomainSocket`
* Loop till the `IpcChannelSide::Server` is created, this allows users to be able to start publisher and subscribers before RouDi is started
* Fix two resource leaks by introducting `closeFd(..)`

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [x] Merge

## References

- Partly closes #381 and #542

### CODE REVIEW

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 1]
```diff
@@ -114,6 +114,11 @@ UnixDomainSocket& UnixDomainSocket::operator=(UnixDomainSocket&& other) noexcept
 {
     if (this != &other)
     {
+        if (destroy().has_error())
```
Comment (mossmaurice) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:117]: Writing tests for the move c'tor/move assignment operator is currently not possible due to the missing possibilty to check for an invalidate `expected`.

We need an `is_valid` method:
```
TYPED_TEST(IpcChannel_test, MoveAssignmentLeadsToInvalidation)
{
    auto clientResult =
        TestFixture::IpcChannelType::create(anotherGoodName, IpcChannelMode::BLOCKING, IpcChannelSide::SERVER);
    auto movedValue = std::move(clientResult);

    EXPECT_TRUE(clientResult.is_valid());
    EXPECT_FALSE(movedValue.is_valid());
}
```

Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:117]: @elBoberido suggested either `has_value`, `is_moved`, `is_specified`, `is_valid`, `has_content`, `not_invalidated`. I like `is_valid ` the most.

What do you think @elfenpiff @budrus?

File: iceoryx_posh/source/runtime/message_queue_interface.cpp [hunk 2]
```diff
@@ -158,9 +158,20 @@ bool MqBase::openMessageQueue(const posix::IpcChannelSide channelSide) noexcept
...
+    {
+        IpcChannelType::create(
+            m_interfaceName, posix::IpcChannelMode::BLOCKING, m_channelSide, m_maxMessageSize, m_maxMessages)
+            .and_then([this, &receivedError](auto& mq) {
+                this->m_mq = std::move(mq);
+                receivedError = posix::IpcChannelError::UNDEFINED;
+            })
+            .or_else([&receivedError](posix::IpcChannelError& error) { receivedError = error; });
+
+    } while (receivedError == posix::IpcChannelError::NO_SUCH_CHANNEL);
```
Comment (elBoberido) [inline iceoryx_posh/source/runtime/message_queue_interface.cpp:174]: If you start more applications than cores are available before roudi is running, the whole system becomes unresponsive. Why not wait a few milliseconds? Why not use the previous behavior?

Comment (mossmaurice) [reply iceoryx_posh/source/runtime/message_queue_interface.cpp:174]: Two valid points. While loops without a sleep burns CPU time and the loop is not needed as the state machine already handles it.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 3]
```diff
@@ -370,29 +383,48 @@ cxx::expected<int32_t, IpcChannelError> UnixDomainSocket::createSocket(const Ipc
...
-            return cxx::success<int32_t>(sockfd);
+            auto closeCall = closeFd(sockfd);
+            if (closeCall.has_error())
+            {
+                return cxx::error<IpcChannelError>(closeCall.get_error());
+            }
+            return createErrorFromErrnum(connectCall.getErrNum());
         }
-        else
+        else if (connectCall.getErrNum() == ENOENT)
```
Comment (mossmaurice) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:415]: This is an error/sad path but `hasErrors()` didn't return true, when taking this branch because `ENOENT` shall not be blamed as a error inside `SmartC`. This could be a good first issue, I've added it to #418

Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:415]: maybe we need something like silent errors in SmartC for stuff like this

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 4]
```diff
@@ -370,29 +383,48 @@ cxx::expected<int32_t, IpcChannelError> UnixDomainSocket::createSocket(const Ipc
...
         {
+            auto closeCall = closeFd(sockfd);
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:417]: We have this code snippet at least 3 times in the code here:
```cpp
            auto closeCall = closeFd(sockfd);
            if (closeCall.has_error())
            {
                return cxx::error<IpcChannelError>(closeCall.get_error());
            }
```

I would suggest a lambda like
```cpp
auto callClose = [this](){
            auto closeCall = closeFd(sockfd);
            if (closeCall.has_error())
            {
                return cxx::error<IpcChannelError>(closeCall.get_error());
            }
};

///....

return callClose();
```

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 5]
```diff
@@ -370,29 +383,48 @@ cxx::expected<int32_t, IpcChannelError> UnixDomainSocket::createSocket(const Ipc
...
-        if (!connectCall.hasErrors())
+        if (connectCall.hasErrors())
         {
-            return cxx::success<int32_t>(sockfd);
+            auto closeCall = closeFd(sockfd);
+            if (closeCall.has_error())
+            {
+                return cxx::error<IpcChannelError>(closeCall.get_error());
+            }
+            return createErrorFromErrnum(connectCall.getErrNum());
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:413]: This is weird. Let's say you have an error in your `connectCall` and caused by this you experience also an error maybe in the `close` call. Then we return only the closeCall error and not the connectCall error which led to this trouble. Here in this particular case I would recommend ignoring the error value of the closeCall since it is only a symptom and not the source and always return the `createErrorFromErrnum(connectCall.getErrNum());`

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 6]
```diff
@@ -370,29 +383,48 @@ cxx::expected<int32_t, IpcChannelError> UnixDomainSocket::createSocket(const Ipc
...
         }
-        else
+        else if (connectCall.getErrNum() == ENOENT)
         {
+            auto closeCall = closeFd(sockfd);
+            if (closeCall.has_error())
+            {
+                return cxx::error<IpcChannelError>(closeCall.get_error());
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:420]: Please ignore the closeCall error and return the cause which led to this point: 
`return createErrorFromErrnum(connectCall.getErrNum());`

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 7]
```diff
@@ -412,112 +444,90 @@ cxx::error<IpcChannelError> UnixDomainSocket::createErrorFromErrnum(const int32_
     {
     case EACCES:
     {
-        std::cerr << "permission to create unix domain socket denied \"" << m_name << "\"" << std::endl;
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:415]: Please leave this error messages in here since they are maybe becoming valuable later.
SmartC will return only a generic error message which explains for instance `EACCES` but does not provide context for the user - in this case that it was used for socket creation.

SmartC always provides you with a rough idea and is always good to provide an additional error message to give the user a more detailed context.

**Review by elfenpiff — CHANGES_REQUESTED** [review]
1. closeFd without arguments
2. do not return closeFd errors when it hides the overlapping cause
3. Undelete the detailed error messages.

File: iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp [hunk 8]
```diff
@@ -141,6 +140,10 @@ class UnixDomainSocket : public DesignPattern::Creation<UnixDomainSocket, IpcCha
 
     static bool isNameValid(const UdsName_t& name) noexcept;
 
+    /// @brief Tries to close the given file descriptor
+    /// @return IpcChannelError if error occured
+    cxx::expected<IpcChannelError> closeFd(int32_t fileDescriptor);
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp:145]: I'm disappointed, you missed the missing `noexcept` :P

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 7 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:415]: Well, I came to find that quite noisy for the user. The user is notified via `expected` about `IpcChannelError` and hence the reason why the call failed and can decide to print an info on a higher level. I could agree to just remove the print for the `ENOENT`. This is what the whole pull request is about :monkey:

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 1 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:117]: Yup, I agree, as close to the standard as possible:

Hits on CppRef:
* `has_value` 3
* `is_moved` 0
* `is_specified` 0
* `is_valid` 0
* `has_content` 0
* `not_invalidated` 0
* `has_undefined_state` 0

I'm quite fond of `is_undefined`

We can move this discussion to the follow-up pull request.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 9]
```diff
@@ -155,29 +163,34 @@ cxx::expected<bool, IpcChannelError> UnixDomainSocket::unlinkIfExists(const NoPa
...
+    {
+        return createErrorFromErrnum(closeCall.getErrNum());
+    }
+}
+
+cxx::expected<IpcChannelError> UnixDomainSocket::destroy() noexcept
+{
+    if (m_isInitialized)
+    {
+        return closeFd(m_sockfd);
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:193]: Nope, inside `UnixDomainSocket::createSocket()`,  `closeFd()` is called with a different value. Using a default parameter instead as an alternative, is less readable for me, because I have to be aware of a default param.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:117]: if the `expected` in in an undefined state after moving, we are violating the C++ standard which explicitly tells that the object must be in an unspecified but defined state ;)

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 5 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:413]: You are right. Adapted.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp]: Changed return value of `createSocket()` and rename it to `initalizeSocket()`

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 1 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:115]: Move to #542

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 10]
```diff
@@ -363,7 +361,7 @@ cxx::expected<int32_t, IpcChannelError> UnixDomainSocket::createSocket(const Ipc
         return createErrorFromErrnum(socketCall.getErrNum());
     }
 
-    int32_t sockfd = socketCall.getReturnValue();
+    m_sockfd = socketCall.getReturnValue();
```
Comment (elBoberido) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:364]: this is a source for future bugs. We might end up with a dangling file descriptor which is not set to `INVALID_FD`.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 11]
```diff
@@ -155,29 +161,34 @@ cxx::expected<bool, IpcChannelError> UnixDomainSocket::unlinkIfExists(const NoPa
...
 }
 
-cxx::expected<IpcChannelError> UnixDomainSocket::destroy() noexcept
+cxx::expected<IpcChannelError> UnixDomainSocket::closeFileDescriptor() noexcept
 {
-    if (m_sockfd != INVALID_FD)
-    {
-        auto closeCall = cxx::makeSmartC(
-            closePlatformFileHandle, cxx::ReturnMode::PRE_DEFINED_ERROR_CODE, {ERROR_CODE}, {}, m_sockfd);
+    auto closeCall =
```
Comment (elBoberido) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:166]: what if `m_sockfd == INVALID_FD`?

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (elfenpiff) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:364]: @elBoberido I completely understand you but if you store it in a temporary variable and then use this variable to close the file descriptor again via `closeFd(tempSockFd)` we have there a bigger source for future bugs since `closeFd` needs to invalidate `m_sockfd` and has to set the whole object to `m_isInitialized = false`.

Then you would have to verify in `closeFd` if it is an arbitrary file descriptor or the socket file descriptor and you have to invalidate everything! 

In my opinion this is the cleanest approach and with this abstraction and sufficient tests we should be good to go.

Additionally, in the previous approach you must always assign the sockfd manually after a successful call and with the logic of a source for future bug you could argue that a future developer maybe forgets to assign this and then you would end up with an invalidated file descriptor.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 11 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:166]: Fixed

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:368]: I didn't say the previous approach was better, just that this might be improved if thinking a bit more about it

File: iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp [hunk 12]
```diff
@@ -133,14 +132,18 @@ class UnixDomainSocket : public DesignPattern::Creation<UnixDomainSocket, IpcCha
     /// @brief creates the unix domain socket
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp:132]: Now it initializes the unix domain socket.

File: iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp [hunk 13]
```diff
@@ -133,14 +132,18 @@ class UnixDomainSocket : public DesignPattern::Creation<UnixDomainSocket, IpcCha
...
     /// @param mode blocking or non_blocking
     /// @return int with the socket file descriptor, IpcChannelError if error occured
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp:134]: The return value description is out of sync.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 14]
```diff
@@ -81,18 +81,16 @@ UnixDomainSocket::UnixDomainSocket(const NoPathPrefix_t,
     else
     {
         m_maxMessageSize = maxMsgSize;
-        auto createResult = createSocket(mode);
+        auto initalizeResult = initalizeSocket(mode);
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:84]: The code is correct but this would be a typical use case for the `and_then`/`or_else` pattern to reduce the amount of code and future errors.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 15]
```diff
@@ -114,6 +112,11 @@ UnixDomainSocket& UnixDomainSocket::operator=(UnixDomainSocket&& other) noexcept
 {
     if (this != &other)
```
Comment (elfenpiff) [inline iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:113]: We all implemented the move assignment in the wrong fashion. Please read: https://isocpp.org/wiki/faq/assignment-operators

and we need to add here the move assignment for the creation pattern. Additionally, we have to implement it as well (which is not yet being done but I work on it in a different PR). Could you please add here only the explicit call to the move assignment of the creation:
```cpp
DesignPattern::Creation<UnixDomainSocket, UnixDomainSocketError>::operator=(std::move(other));
```

**Review by elfenpiff — CHANGES_REQUESTED** [review]

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 15 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:113]: Imporant point, thanks for raising it! Fixed.

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:365]: How about the following:
- keep the old name and return the file descriptor
- rename the current `closeFileDescriptor` to `closeAndUnlink`
- create a static `closeFileDescriptor` method which takes a file descriptor as parameter
- call that one in this method and in `closeAndUnlink`

With this, it should not be possible to end up with a dangling file descriptor.

**Review by elBoberido — COMMENTED** [review]
Except the food for thought for `initializeSocket` this looks good

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:365]: For me it doesn't make sense to use a creational pattern aka `createSocket()` here. What you describe perfectly fit for something like a factory, where I say "Hey please bake that object for me". In our case it is different. `sockfd` is a member of the object, hence an integral part and nothing that gets created and is then attached to the object. Think of a car that already has tires and which get pumped up aka initalised at a certain point in the lifetime of the car. What do you think fits better `initializeTires()" or `createTires()`? With the current approach it should also not be possible to end up with dangling pointers.

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:365]: Well it's more like a `check if the tires are flat before mounting it on the car` analogy :)

**Review by elBoberido — APPROVED** [review]

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp (hunk 10 above)
Comment (elBoberido) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:365]: oh, and it's possible run twice through `closeFileDescriptor` if the first call fails. That wouldn't be the case if `m_sockfd` is not set in the first place.
