### PR TITLE
iox-#1365 implement thread wrapper for apple

### LINKED ISSUE #1365: POSIX wrapper for pthreads
## Brief feature description

We need a POSIX wrapper for `pthreads` to get rid of exceptions and undefined behavior. 
For posix platforms the wrapper shall support:

* Set stack address
     * https://man7.org/linux/man-pages/man3/pthread_attr_setstack.3.html
     * consider suggestions in #1400 
* Setting scheduler priority
    * https://man7.org/linux/man-pages/man3/pthread_setschedprio.3.html
* Set CPU affinity
    * https://man7.org/linux/man-pages/man3/pthread_setaffinity_np.3.html
* Set stack size
    * See, https://man7.org/linux/man-pages/man3/pthread_attr_setstack.3.html
    * https://man7.org/linux/man-pages/man3/pthread_attr_setstacksize.3.html
* The destructor shall call join by default, see `std::jthread` https://en.cppreference.com/w/cpp/thread/jthread
* Explicit thread termination:
    * https://man7.org/linux/man-pages/man3/pthread_exit.3.html

Optionally, it would be awesome when it supports

* https://man7.org/linux/man-pages/man3/pthread_equal.3.html
* https://man7.org/linux/man-pages/man3/pthread_self.3.html
* Set the scheduler
    * https://man7.org/linux/man-pages/man3/pthread_attr_setschedparam.3.html
 * Set contention scope:
     * https://man7.org/linux/man-pages/man3/pthread_attr_setscope.3.html
 * Set cleanup handlers
     * https://man7.org/linux/man-pages/man3/pthread_cleanup_push.3.html

## Tasks

* [x] implement Thread class with minimal functionality needed for current code base
* [x] make it work on Windows and Mac
* [ ] replace all `std::thread` occurrences
* [ ] implement must have features
* [ ] add awesome optional features

## Design considerations

* pass an optional to create method
    * current state
    * https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r903375242
* or separate handle and storage
    * proposed API: https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r899220308
    * optional: potential to forget reset on an early return, https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r898375219
    * https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r906079855
* callable with generic signature?
    * can be achieved with a lambda capturing the needed arguments in the current implementation
    * see also https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r899256494
* movable threads?
    *  https://github.com/eclipse-iceoryx/iceoryx/pull/1400#discussion_r898890414
    * easier if thread handle and storage are separated

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer
This PR implements the `iox_pthread_*` functions for Apple. Additionally, the name must now be set on creation.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Partially closes #1365

### CODE REVIEW

File: iceoryx_hoofs/platform/mac/source/pthread.cpp [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+#include <utility>
+
+static std::map<iox_pthread_t, std::string> handleNameMap;
+
+int iox_pthread_setname_np(iox_pthread_t thread, const char* name)
+{
+    const auto result = handleNameMap.insert(std::make_pair(thread, name));
+    if (!result.second)
+    {
+        /// return error code once std::thread is replaced; not possible now because iox_pthread_join is not called
```
Comment (mossmaurice) [inline iceoryx_hoofs/platform/mac/source/pthread.cpp:31]: Nitpick: Maybe add a todo with an issue number.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp [hunk 2]
```diff
@@ -77,6 +77,14 @@ cxx::expected<ThreadError> ThreadBuilder::create(cxx::optional<Thread>& uninitia
         return cxx::error<ThreadError>(Thread::errnoToEnum(createResult.get_error().errnum));
     }
 
+    posixCall(iox_pthread_setname_np)(uninitializedThread->m_threadHandle, m_name.c_str())
+        .successReturnValue(0)
+        .evaluate()
+        .expect("This should never happen! Failed to set thread name.");
+    /// @todo thread specific comm file under /proc/self/task/[tid]/comm is read. Opening this file can fail
+    /// and errors possible for open(2) can be retrieved. Handle them here?
+    /// @todo Do we really want to terminate here?
```
Comment (mossmaurice) [inline iceoryx_hoofs/source/posix_wrapper/thread.cpp:86]: If not here, then where? I would say fail early, hence fail here.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp [hunk 3]
```diff
@@ -77,6 +77,14 @@ cxx::expected<ThreadError> ThreadBuilder::create(cxx::optional<Thread>& uninitia
         return cxx::error<ThreadError>(Thread::errnoToEnum(createResult.get_error().errnum));
     }
 
+    posixCall(iox_pthread_setname_np)(uninitializedThread->m_threadHandle, m_name.c_str())
+        .successReturnValue(0)
+        .evaluate()
+        .expect("This should never happen! Failed to set thread name.");
+    /// @todo thread specific comm file under /proc/self/task/[tid]/comm is read. Opening this file can fail
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp:84]: Nitpick: Maybe link an issue if this todo stays.

**Review by mossmaurice — APPROVED** [review]
LGTM, thanks for the PR! As I don't have a Mac I couldn't run it myself, but I trust the CI in this regard :smile_cat:

File: iceoryx_hoofs/platform/mac/source/pthread.cpp [hunk 4]
```diff
@@ -0,0 +1,53 @@
+// Copyright (c) 2020 by Robert Bosch GmbH. All rights reserved.
+// Copyright (c) 2021 - 2022 by Apex.AI Inc. All rights reserved.
```
[the remark this answers is not in the document]
Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/platform/mac/source/pthread.cpp:2]: Well, it is a new file but parts of the code were just moved from the `.hpp` to the `.cpp`.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp (hunk 2 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp:86]: Maybe the comment is misleading. The question is if we want to terminate just because we cannot set (or below get) the thread name. It could be sufficient to log that the call failed but this depends somehow on how we handle potential errors of the underlying `open` call.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp:84]: According to https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html, a failing `open` call may influence the return value of `pthread_setname_np`.

[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp]: @FerdinandSpitzschnueffler I suppose we should add a note in the docs somewhere about `procfs`. Did you check the QNX manual?

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp (hunk 2 above)
Comment (elfenpiff) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp]: I tend here to just inform the user that the thread-name could not be set. Normally, this does not restrict the functionality in any way.

File: iceoryx_hoofs/platform/mac/source/pthread.cpp [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+#include <string>
+#include <utility>
+
+/// @note Since pthread_setname_np and pthread_getname_np are missing in MacOS, their functionality is simulated via a
+/// map of thread handle and thread name.
+static std::map<iox_pthread_t, std::string> handleNameMap;
+
+int iox_pthread_setname_np(iox_pthread_t thread, const char* name)
+{
+    const auto result = handleNameMap.insert(std::make_pair(thread, name));
```
Comment (elfenpiff) [inline iceoryx_hoofs/platform/mac/source/pthread.cpp:30]: This free function can be called concurrently. For instance it is allowed that multiple threads create again multiple threads and set or get the thread name concurrently.
When all those functions are then not guarded by a mutex we have race conditions.

Could you therefore introduce a global `static std::mutex handleNameMapMutex` and always lock it when you access the map with `std::lock_guard<std::mutex> lock(handleNameMapMutex);`

I think the function `iox_pthread_setname_np`, `iox_pthread_getname_np` and `iox_pthread_join` are affected.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp [hunk 6]
```diff
@@ -77,6 +77,14 @@ cxx::expected<ThreadError> ThreadBuilder::create(cxx::optional<Thread>& uninitia
         return cxx::error<ThreadError>(Thread::errnoToEnum(createResult.get_error().errnum));
     }
 
+    posixCall(iox_pthread_setname_np)(uninitializedThread->m_threadHandle, m_name.c_str())
+        .successReturnValue(0)
+        .evaluate()
+        .expect("This should never happen! Failed to set thread name.");
```
Comment (elfenpiff) [inline iceoryx_hoofs/source/posix_wrapper/thread.cpp:83]: I would not terminate here (this is what `expect` does behind the scenes when it calls `cxx::Ensures` or so). I would handle here the error in detail but still return `cxx::success<>()` later.
The reason is, that in my opinion, the underlying functionality of the thread is not restricted at all when a name could not be set.

The only thing which normally happens, is that one sees no nice thread name in the debugger or in a process monitor like `htop`.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp [hunk 7]
```diff
@@ -119,9 +116,9 @@ ThreadName_t Thread::getName() const noexcept
         .successReturnValue(0)
         .evaluate()
         .expect("This should never happen! Failed to retrieve the thread name.");
```
Comment (elfenpiff) [inline iceoryx_hoofs/source/posix_wrapper/thread.cpp:118]: I would handle the error here in detail but just by providing meaningful error log messages to the user since the underlying functionality of the thread is not compromised.

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp (hunk 6 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp:86]: I agree but would keep it as todo for the moment since the error handling must be adapted anyway to consider the possible `open` errors. @elfenpiff Is that okay for you?

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_hoofs/source/posix_wrapper/thread.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (FerdinandSpitzschnueffler) [reply iceoryx_hoofs/source/posix_wrapper/thread.cpp]: @mossmaurice I think we should be platform independent here. Additionally, I tend to refactor the `getName` and `setName` methods so that we don't terminate in an error case but just log that setting the name didn't work - maybe we don't even have to distinguish the failure causes. But I would like to postpone it to another PR when the free functions will be also removed.
