### PR TITLE
Iox #1049 create iceoryx docker shell script

### LINKED ISSUE #1049: Create shell script to setup docker container for iceoryx development
## Brief feature description

When the CI fails with an error which cannot be debugged on the local machine since the compiler or operating system has a different version one has to use a docker container to reproduce bugs in the CI.
The best way of doing this would be to introduce a simple shell script which starts and setups a container with the correct specifications automatically.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1049

### CODE REVIEW

File: tools/ice_env.sh [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+    local ICEORYX_PATH=$(git rev-parse --show-toplevel)
+    if [[ $(docker container inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null) == "true" ]]; then
+        echo iceoryx development environment already running \(docker container: $CONTAINER_NAME\)
+        exit
+    fi
+
+    docker run --name $CONTAINER_NAME \
+               --mount type=bind,source=${ICEORYX_PATH},target=/iceoryx \
+               --hostname ${OS_VERSION} \
+               -dt --memory "4g" ${OS_VERSION}
```
Comment (dkroenke) [inline tools/ice_env.sh:87]: It would be good to set the possible max. shared memory size with `--shm-size 2g` to a certain value. Default is 64 Mb which is not enough.

**Review by dkroenke — CHANGES_REQUESTED** [review]
The script should be located either in the script or docker folder of tools.
Additionally it would be good to have a small hint to this in the advanced installation guide of the iceoryx documentation

**Review by dkroenke — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -21,6 +21,7 @@
 - Extend cxx::optional constructor for in place construction so that copy/move for values inside the optional even could be deleted[\#967](https://github.com/eclipse-iceoryx/iceoryx/issues/967)
 - Add templated `from`/`into` free functions to formalize conversions from enums and other types [#992](https://github.com/eclipse-iceoryx/iceoryx/issues/992)
 - UniqueId class for unique IDs within a process [#1010](https://github.com/eclipse-iceoryx/iceoryx/issues/1010)
+- Add `/tools/ice_env.sh` shell script to provide simple access to docker containers for CI debugging [#1049](https://github.com/eclipse-iceoryx/iceoryx/issues/1049)
```
Comment (FerdinandSpitzschnueffler) [inline CHANGELOG.md:24]:
```suggestion
- Add `/tools/scripts/ice_env.sh` shell script to provide simple access to docker containers for CI debugging [#1049](https://github.com/eclipse-iceoryx/iceoryx/issues/1049)
```

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

**Review by dkroenke — APPROVED** [review]

**Review by dkroenke — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by dkroenke — APPROVED** [review]
