### PR TITLE
Check for nullptr in c bindings

### LINKED ISSUE #1106: Implement and test `nullptr` check in c binding
## Brief feature description

Most of the C functions get as first argument a pointer to the class which they are handling. It  is possible that this pointer is a `nullptr` but this is in most functions not checked.

* Sometimes even payload pointer or pointer to other structs are provided which have to be also checked.
* `const char * ` arguments have to also be checked for `nullptr`

We have to implement and test such a check for all c binding functions.

## Detailed information

Example from `c_publisher.cpp`:
```c
void iox_pub_release_chunk(iox_pub_t const self, void* const userPayload)
{
    PublisherPortUser(self->m_portData).releaseChunk(ChunkHeader::fromUserPayload(userPayload));
}
```
`self` is the pointer to the publisher and can be a `nullptr`.

## ToDo:
- [x] ~~Implement #1113 first, then verify nullptr checks with an error handler that throws an exception.~~ `EXPECT_FATAL_FAILURE` can be used to test code which would lead to a termination in `Expects/Ensures` calls
- [ ] Check if ToDo list contains all affected constructs (if not add them)
- [ ] `c_chunk.cpp`
- [ ] `c_listener.cpp`
- [ ] `c_notification_info.cpp`
- [ ] `c_publisher.cpp`
- [ ] `c_subscriber.cpp`
- [ ] `c_user_trigger.cpp`
- [ ] `c_wait_set.cpp`
- [ ] Collect bonus points by coming up with a great idea/concept which prohibits such a oversight in the future.

### PR DESCRIPTION
**Pull request by zmostafa**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This is the first trial to address this issue, I would use in comments to this file and then apply them to the rest bindings.

- [x]  c_chunk.cpp
- [x]  c_listener.cpp
- [x]  c_client.cpp
- [x]  c_node.cpp
- [x]  c_notification_info.cpp
- [x]  c_publisher.cpp
- [x]  c_resonse_header.cpp
- [x]  c_request_header.cpp
- [x]  c_server.cpp
- [x]  c_service_discovery.cpp
- [x]  c_subscriber.cpp
- [x]  c_user_trigger.cpp
- [x]  c_wait_set.cpp

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1106

### CODE REVIEW

**Comment by zmostafa** [comment]
@elBoberido @elfenpiff fyi :+1:

**Review by elfenpiff — COMMENTED** [review]
@zmostafa What is with all the other c binding files?

**Comment by zmostafa** [comment]
@elfenpiff I will work my way with the files listed in the todo section of the issue for sure, just wanted to share this initial work with you guys for any comments before I go on with the rest

File: iceoryx_binding_c/test/moduletests/test_client.cpp [hunk 1]
```diff
@@ -139,15 +142,195 @@ TEST_F(iox_client_test, notInitializedOptionsAreUninitialized)
...
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>([&] { iox_client_init(nullptr, SERVICE, INSTANCE, EVENT, &options); },
+                                              iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>([&] { iox_client_init(&sutStorage, nullptr, INSTANCE, EVENT, &options); },
+                                              iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>([&] { iox_client_init(&sutStorage, SERVICE, nullptr, EVENT, &options); },
+                                              iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>(
+        [&] { iox_client_init(&sutStorage, SERVICE, INSTANCE, nullptr, &options); },
+        iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    // IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>(
```
Comment (zmostafa) [inline iceoryx_binding_c/test/moduletests/test_client.cpp:189]:
```cpp
    iox::cxx::Expects(options == nullptr || (options != nullptr && iox_client_options_is_initialized(options)));
```
todo: check how to test this condition.

Comment (elBoberido) [reply iceoryx_binding_c/test/moduletests/test_client.cpp:189]: I guess you can just create a `iox_client_options_t` on the stack. Call `iox_client_init` with that object and the exactly what you did in this commented out code :)

**Review by elBoberido — COMMENTED** [review]
@zmostafa just briefly skimmed over the changes and they look good.

**Comment by elBoberido** [comment]
@zmostafa btw. do you want to handle the remaining files with this PR or do you want to create separate ones? If it is the former I can start with a thorough review. If it is the latter I will wait.

**Comment by zmostafa** [comment]
@elBoberido Thanks for taking a look, you can wait until I make this PR ready for review, I am going through the whole `iceoryx_binding_c` directory, the files are quite big and I think by the end of this week I will be over with all of them.

File: iceoryx_binding_c/test/moduletests/test_notification_info.cpp [hunk 2]
```diff
@@ -250,4 +256,162 @@ TEST_F(iox_notification_info_test, callbackCanBeCalledMultipleTimes)
...
+    EXPECT_TRUE(iox_notification_info_does_originate_from_user_trigger(notificationInfoVector[0U], &m_userTrigger));
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>(
+        [&] { iox_notification_info_does_originate_from_user_trigger(nullptr, &m_userTrigger); },
+        iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>(
+        [&] { iox_notification_info_does_originate_from_user_trigger(notificationInfoVector[0U], nullptr); },
+        iox::HoofsError::EXPECTS_ENSURES_FAILED);
+}
+
+TEST_F(iox_notification_info_test, doesOriginateFromClientWorks)
```
Comment (zmostafa) [inline iceoryx_binding_c/test/moduletests/test_notification_info.cpp:302]: @elBoberido The tests that tries to create a `client`, `server`, or a `service discovery` fails with exception, It seems that the test is not able to create an instance of those on the stack and gtest exits with exception. 
I am not sure what would be the best way to create these instances, can we share the test class from those modules with this module to create the instances, or how should it be done ?

File: iceoryx_binding_c/test/moduletests/test_notification_info.cpp [hunk 3]
```diff
@@ -250,4 +256,162 @@ TEST_F(iox_notification_info_test, callbackCanBeCalledMultipleTimes)
...
+    ASSERT_FALSE(m_waitSet.attachEvent(m_userTrigger, ARBITRARY_EVENT_ID).has_error());
+    m_userTrigger.trigger();
+
+    auto notificationInfoVector = m_waitSet.wait();
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>([&] { iox_notification_info_does_originate_from_client(nullptr, sut); },
+                                              iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    IOX_EXPECT_FATAL_FAILURE<iox::HoofsError>(
+        [&] { iox_notification_info_does_originate_from_client(notificationInfoVector[0U], nullptr); },
+        iox::HoofsError::EXPECTS_ENSURES_FAILED);
+    iox_client_deinit(sut);
```
Comment (elBoberido) [inline iceoryx_binding_c/test/moduletests/test_notification_info.cpp:342]: This can potentially be simplified. You do not need a valid pointer but only an non-nullptr for this test since it is expected to fail early anyway. I'm currently just not sure if it is a good idea or whether is is easy to get such a pointer for this structs like it is done for the subscriber

File: iceoryx_binding_c/test/moduletests/test_notification_info.cpp (hunk 2 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_binding_c/test/moduletests/test_notification_info.cpp:302]: I had a quick look at `test_subscriber.cpp` and there it seems that the `RouDiEnvironment` should be used
```
iox::roudi::RouDiEnvironment roudiEnv;
iox_runtime_init("foo');
```
@elfenpiff can you confirm?

Comment (elfenpiff) [reply iceoryx_binding_c/test/moduletests/test_notification_info.cpp:302]: Ouh ... I actually have no longer an idea. But I think I would try the roudi env first.

Comment (zmostafa) [reply iceoryx_binding_c/test/moduletests/test_notification_info.cpp:302]: @FerdinandSpitzschnueffler Thanks for your suggestion, I will give it a try today !

**Comment by zmostafa** [comment]
@elfenpiff @elBoberido Sorry guys it took that long to get this PR ready, you can take a look on it now.

cc. @mossmaurice

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_binding_c/test/moduletests/test_notification_info.cpp [hunk 4]
```diff
@@ -48,7 +56,7 @@ using namespace iox::posix;
 class iox_notification_info_test : public Test
 {
   public:
-    const iox::capro::ServiceDescription TEST_SERVICE_DESCRIPTION{"a", "b", "c"};
+    const iox::capro::ServiceDescription TEST_TheHoff_DESCRIPTION{"a", "b", "c"};
```
Comment (elBoberido) [inline iceoryx_binding_c/test/moduletests/test_notification_info.cpp:59]: :rofl:

**Review by elBoberido — APPROVED** [review]
