### PR TITLE
Iox #482 add example for complex data types

### LINKED ISSUE #482: Extend documentation for 1.0 release and website
# Documentation epic

# Proposed outline
- index.md
- What is Eclipse iceoryx? (Explain the three pillars easy, safe, fast)
- getting-started
  - overview.md (Split?)
    - General intro (add overview pictures e.g. from [ROSCon slides](https://roscon.ros.org/2019/talks/roscon2019_truezerocopy.pdf), add section "limitations")
    - hello world/quick start: icedelivery c++ typed (without `and_then`?) `icehello`
    - User API (Move into examples)
      - Typed
      - Untyped  
  - installation.md (move colcon to advanced?, usual user just wants to use script and nothing more, link contributor installation guide, move iceoryx_posh options table to advanced, fix markdown no identation before code blocks)
  - examples (overview over examples)
    - Communication with polling for the user /for frameworks
    - Options
    - Listner 
    - Communication without polling
    - Debugging (iceperf, icecrystal)
- API-reference
- (API-cheatsheet.md)
- FAQ.md
- advanced
  - Contriubtor guides 
    - best-practice-for-testing.md
    - Modern C++ error handling (Optional, expected)
    - installation-guide-for-contributors.md 
  - iceoryx_utils.md
  - usage-guide.md

## Documents covering
- [x] Extend installation guide
  - [x] QNX7 with QCC 5.4.0
- [x] Introduction: motivation, goals and capabilities of iceoryx
  - [x] Which data types are allowed to be sent via iceoryx? What are the limitations (virtual, vtable, heap)?
  - [x] Clarify failure cases, e.g.
    - What happens if an application segfaults? If crashes in critical section memleak
    - Does the crash of one application affect the whole system
    - When an application crashes, what happens with its resources like memory chunks, UDS, etc.
  - [x] Update Waitset and Listener section in overview.md and have a use case based comparison 
- [x]  Add new examples
  - [x] README.md in the example 
  - [x] iceoptions 
  - [x] icehello
  - [x] iceensemble: Explain how C and C++ API work together (multiple publishers and subscribers)
  - [x] blocking publisher
  - [x] icecubetray: Add access control documentation (comes from #640)
  - [x] Record asciinema for all examples
- [x] Add example for static RouDi Config with custom mempools and one for the dynamic TOML config, e.b. by just a 
- [x] `@todo` in the code shall not be linked to issues for v1.0
- [x] Add Apex.OS to the framework section

### v2.0 Release (Moved to #743)

- [x] Improve utils documentation (in the long run: find more suitable name for utils, e.g. safe building blocks), see also #468
- [x] Describe all RouDi command line options?
- [x] Add info about release names (ice cream flavours)
- [x] add overview graphic introducing the main players (RouDi, Runtime/user apps, shared Memory, data packages/topics) in overview.md (see suggestions [here](https://github.com/eclipse-iceoryx/iceoryx/pull/646#discussion_r604950011) and [here](https://github.com/eclipse-iceoryx/iceoryx/pull/646#discussion_r604960591))
- [x] Add chunk header example
- [x] Add example sending complex data types
- [x] icedelivery:  Explain lifetime semantics of chunks/samples and user restrictions: loan needs to be followed with publish or release, MAX_CHUNKS_IN_USE on publisher and subscriber side etc., API is not thread-safe

Consolidate current documentation as far as possible (keep the scope of the issue confined to documentation).
Note: doxygen documentation rework is out of scope here and belongs to #468

This is later to be integrated into the website #136

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer
This PR introduces an example for sending/receiving our cxx constructs. The README.md includes only the outline and will be finished once the example code is approved.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Partially closes #743

### CODE REVIEW

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+    while (!killswitch)
+    {
+        publisher.loan()
+            .and_then([&](auto& sample) {
+                for (uint64_t i = 0U; i < sample->capacity(); ++i)
+                {
+                    bool success = sample->emplace_back(static_cast<double>(ct + i));
+                    if (!success)
+                    {
+                        std::cerr << "Failed to insert element." << std::endl;
```
Comment (elfenpiff) [inline iceoryx_examples/complexdata/iox_publisher_vector.cpp:55]: If this happens I think we should `break;` after the error message and send the stuff that was emplaced

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#include "topic_data.hpp"
+
+#include "iceoryx_posh/popo/publisher.hpp"
+#include "iceoryx_posh/runtime/posh_runtime.hpp"
+#include "iceoryx_utils/posix_wrapper/signal_handler.hpp"
+
+bool killswitch = false;
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:23]: please make this atomic

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+
+// push_front (list), push (stack), emplace_back (vector) return a bool - true if the insertion succeeded, false
+// otherwise
+// to keep the example clear, this helper function handles the return values
+void handle(const bool hasSuccess)
+{
+    if (!hasSuccess)
+    {
+        std::cerr << "Failed to insert element." << std::endl;
+        std::terminate();
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:40]: please use `std::exit(EXIT_FAILURE)`

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+{
+    // register sigHandler
+    auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
+    auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);
+
+    // initialize runtime
+    iox::runtime::PoshRuntime::initRuntime(APP_NAME);
+
+    // initialize publisher
+    iox::popo::Publisher<ComplexDataType> publisher({"Radar", "FrontLeft", "Object"});
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:54]: ouch, you stirred up a hornet's nest. This is wrong and should also be checked in the other examples. icedelivery and icehello already have the same ServiceDescription for topics with a different data type.

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+    uint64_t ct = 0;
+    // run until interrupted by Ctrl-C
+    while (!killswitch)
+    {
+        ++ct;
+        publisher.loan()
+            .and_then([&](auto& sample) {
+                // forward_list<string<10>, 5>
+                handle(sample->stringForwardList.push_front("world"));
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:64]: `handle` is quite generic. Could you maybe change this to something more descriptive?

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+                for (uint64_t i = 0U; i < sample->doubleVector.capacity(); ++i)
+                {
+                    handle(sample->doubleVector.emplace_back(static_cast<double>(ct + i)));
+                }
+                // vector<variant<string<10>, double>, 10>;
+                handle(sample->variantVector.emplace_back(in_place_index<0>(), "seven"));
+                handle(sample->variantVector.emplace_back(in_place_index<1>(), 8.0));
+                handle(sample->variantVector.emplace_back(in_place_index<0>(), "nine"));
+
+                sample.publish();
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:90]: a hypnotoad or brain slug is missing

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+{
+    // register sigHandler
+    auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
+    auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);
+
+    // initialize runtime
+    iox::runtime::PoshRuntime::initRuntime(APP_NAME);
+
+    // initialize publisher
+    iox::popo::Publisher<iox::cxx::vector<double, 5>> publisher({"Radar", "FrontLeft", "Object"});
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_vector.cpp:42]: this will result in pink elefants

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp:55]: in this case I would omit the check since the loop doesn't exceed the capacity of the vector and this is unnecessary noise.

But we might think about having
```c++
cxx::vector<uint8_t, 42> foo;

uint8_t counter = 0;
foo.fill_to_capacity([&] {
    return counter++;
});

foo.for_each([](auto& element){
    std::cout << element << std::endl;
});
```

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+                    {
+                        std::cerr << "Failed to insert element." << std::endl;
+                    }
+                }
+
+                sample.publish();
+            })
+            .or_else([](auto& error) {
+                // do something with error
+                std::cerr << "Unable to loan sample, error code: " << static_cast<uint64_t>(error) << std::endl;
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_vector.cpp:63]: this reminds me that we need to implement the stream operator for `AllocationError` and `ChunkReceiveResult`

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+        subscriber.take()
+            .and_then([](auto& sample) {
+                std::stringstream s;
+                s << APP_NAME << " got values:";
+
+                s << std::endl << "stringForwardList: ";
+                for (auto i = sample->stringForwardList.begin(); i != sample->stringForwardList.end(); ++i)
+                {
+                    s << *i << " ";
+                }
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:57]: just a small hint, if you omit the white-space after `stringForwardList: ` and make `s << " " << *i;` there is no superfluous white-space at the end of the line :)

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+                s << std::endl << "integerList: ";
+                for (auto i = sample->integerList.begin(); i != sample->integerList.end(); ++i)
+                {
+                    s << *i << " ";
+                }
+
+                s << std::endl << "optionalList: ";
+                for (auto i = sample->optionalList.begin(); i != sample->optionalList.end(); ++i)
+                {
+                    (i->has_value()) ? s << i->value() << " " : s << "optional is empty, ";
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:68]: `, ` is not necessary

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+                }
+
+                s << std::endl << "floatStack: ";
+                auto stackCopy = sample->floatStack;
+                for (uint64_t i = stackCopy.capacity(); i > 0U; i--)
+                {
+                    auto result = stackCopy.pop();
+                    (result.has_value()) ? s << result.value() << " " : s << "stack is empty";
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:76]: the stack is not full, but you don't know if it's empty

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+                s << APP_NAME << " got values:";
+
+                s << std::endl << "stringForwardList: ";
+                for (auto i = sample->stringForwardList.begin(); i != sample->stringForwardList.end(); ++i)
+                {
+                    s << *i << " ";
+                }
+
+                s << std::endl << "integerList: ";
+                for (auto i = sample->integerList.begin(); i != sample->integerList.end(); ++i)
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:60]: would it be possible to use a range-based for-loop?

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+                }
+
+                s << std::endl << "someString: ";
+                s << sample->someString;
+
+                s << std::endl << "doubleVector: ";
+                for (uint64_t i = 0U; i < sample->doubleVector.size(); ++i)
+                {
+                    s << sample->doubleVector[i] << " ";
+                }
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:86]: it would be nice to have this as coma separated output ... without a superfluous comma at the end of course ;)

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 14]
```diff
@@ -0,0 +1,119 @@
...
+                for (uint64_t i = 0U; i < sample->variantVector.size(); ++i)
+                {
+                    if (sample->variantVector[i].index() == 0)
+                    {
+                        s << *sample->variantVector[i].template get_at_index<0>() << " ";
+                    }
+                    else if (sample->variantVector[i].index() == 1)
+                    {
+                        s << *sample->variantVector[i].template get_at_index<1>() << " ";
+                    }
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:98]: please either add an `else` branch or change to a switch statement with a default case

File: iceoryx_examples/complexdata/README.md [hunk 15]
```diff
@@ -0,0 +1,25 @@
+# complexdata
+
+## Introduction
+
+- to implement zero-copy data transfer we use a shared memory approach
+- this requires that every data structure needs to be stored in the shared memory and that
+  they do not use the heap (link to restrictions chapter in overview.md)
+- most of the STL types cannot be used, but we reimplemented some (link to utils readme/cxx)
+- this example shows a) how to send/receive a iox::cxx::vector b) how to send/receive a
+  complex data structure containing some of our STL container surrogates
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/README.md:10]: The requirement is a bit stronger.
1. Cannot use dynamic memory (I would not write heap, because it is misleading and may have other meanings).
2. Cannot use pointers internally (even if no dynamic memory is used)
3. Cannot reference external data (by index or pointer, since if you do so the external data must be present at the destination as well which adds a lot of complications)

File: iceoryx_examples/complexdata/topic_data.hpp [hunk 16]
```diff
@@ -0,0 +1,42 @@
...
+
+#include "iceoryx_utils/cxx/forward_list.hpp"
+#include "iceoryx_utils/cxx/list.hpp"
+#include "iceoryx_utils/cxx/optional.hpp"
+#include "iceoryx_utils/cxx/stack.hpp"
+#include "iceoryx_utils/cxx/string.hpp"
+#include "iceoryx_utils/cxx/variant.hpp"
+#include "iceoryx_utils/cxx/vector.hpp"
+
+using namespace iox::cxx;
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/topic_data.hpp:28]: ok here in this small example, but usually not a good idea in head files.

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 17]
```diff
@@ -0,0 +1,102 @@
...
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#include "topic_data.hpp"
+
+#include "iceoryx_posh/popo/publisher.hpp"
+#include "iceoryx_posh/runtime/posh_runtime.hpp"
+#include "iceoryx_utils/posix_wrapper/signal_handler.hpp"
+
+std::atomic_bool killswitch{false};
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:23]: I would recommend using it shutdown or similar in all examples, but of course is inconsequential.

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 18]
```diff
@@ -0,0 +1,102 @@
...
+static void sigHandler(int f_sig [[gnu::unused]])
+{
+    // caught SIGINT or SIGTERM, now exit gracefully
+    killswitch = true;
+}
+
+// push_front (list), push (stack), emplace_back (vector) return a bool - true if the insertion succeeded, false
+// otherwise
+// to keep the example clear, this helper function handles the return values
+void handleInsertionReturnVal(const bool hasSuccess)
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:35]: better isSuccessful or success

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 19]
```diff
@@ -0,0 +1,102 @@
...
+{
+    // register sigHandler
+    auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
+    auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);
+
+    // initialize runtime
+    iox::runtime::PoshRuntime::initRuntime(APP_NAME);
+
+    // initialize publisher
+    iox::popo::Publisher<ComplexDataType> publisher({"Group", "Instance", "Topic"});
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:54]: Just putting it here, but I think **Partition** might be a more fitting name than Group (more important in the description), but we need to think about this anyway concept-wise. Especially since this could be used like in DDS or network partitioning.

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp [hunk 20]
```diff
@@ -0,0 +1,102 @@
...
+        ++ct;
+        publisher.loan()
+            .and_then([&](auto& sample) {
+                // forward_list<string<10>, 5>
+                handleInsertionReturnVal(sample->stringForwardList.push_front("world"));
+                handleInsertionReturnVal(sample->stringForwardList.push_front("hello"));
+                // list<uint64_t, 10>;
+                handleInsertionReturnVal(sample->integerList.push_front(ct));
+                handleInsertionReturnVal(sample->integerList.push_front(ct * 2));
+                handleInsertionReturnVal(sample->integerList.push_front(ct + 4));
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:69]: Would remove one of those inserts, does not test or demonstrate anything new. (i.e. is just noise)

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp (hunk 1 above)
Comment (MatthiasKillat) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp:55]: This is one of the cases where we even know that the emplacement cannot fail anyway (barring a a wrong implementation of vector or loan which does not construct a sample with an empty vector, of course). So we should avoid unnecessary checks. 
Also take a look at https://en.cppreference.com/w/cpp/algorithm/iota for similar purposes (since we should even have random access iterators here it would apply). But it would have to operate on a non empty range, which we will not have initially here.

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp [hunk 21]
```diff
@@ -0,0 +1,73 @@
...
+            });
+        ++ct;
+
+        std::this_thread::sleep_for(std::chrono::milliseconds(100));
```
Comment (MatthiasKillat) [inline iceoryx_examples/complexdata/iox_publisher_vector.cpp:68]: I would decrease the frequency somewhat (will flood the console too much).

File: iceoryx_examples/complexdata/topic_data.hpp (hunk 16 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/topic_data.hpp:28]: I decided to use the namespace for better readability, especially in the (not yet finished) readme.md

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp (hunk 17 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:23]: To be consistent with most of the other examples, I would keep the name.

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp (hunk 19 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:54]: For now, I would prefer to be in sync with our overview.md where it is `Group`. But yes, we should think about a better naming, although I'm not sure if we should use the DDS naming.

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp (hunk 13 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp]: Well, I didn't want to add more extra code only used for the output which is not necessary for understanding how to send complex data. But no hard feelings about that. I can add it.

Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp]: Oh, maybe I got you wrong. Can you explain in more detail what you mean with `coma separated`? ;)

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp (hunk 19 above)
Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:54]: could you be a bit more specific with the ServiceDescription, e.g. using `ComplexDataTopic` as event id to prevent accidental matching ServiceDescription with different data

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp [hunk 22]
```diff
@@ -0,0 +1,73 @@
...
+{
+    // register sigHandler
+    auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
+    auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);
+
+    // initialize runtime
+    iox::runtime::PoshRuntime::initRuntime(APP_NAME);
+
+    // initialize publisher
+    iox::popo::Publisher<iox::cxx::vector<double, 5>> publisher({"Radar", "FrontRight", "Object"});
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_publisher_vector.cpp:42]: This is still quite near to our examples with a different data type and my inner chicken feels that this might become a problem. Could you please change this even more, like having `VectorData` as event id?

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp (hunk 13 above)
Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp]: no, you got it right. I meant a comma separated list, but it seems you already did it in an elegant way ... I guess I was in a coma when I wrote that :)

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp (hunk 1 above)
Comment (elfenpiff) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp]: @elBoberido we already have and `.for_each` at our hands.
```cpp
std::for_each(foo.begin(), foo.end(), [](auto e){std::cout << e << std::endl;});
```

Maybe we need a cxx version for it so that it is possible to do this for the whole range whenever it has `.end` and `.begin` as methods like:
```cpp
cxx::for_each(foo, [](auto e){std::cout << e << std::endl;});
```
This would be more like the C++ approach advertised in the STL.


The second problem I would solve like this:
```cpp
cxx::vector<uint8_t, 42> foo(42);
std::generate(foo.begin(), foo.end(), [counter=0]() mutable { return counter++; });
```
Maybe we also need a cxx version of that which would become more readable;
```cpp
cxx::vector<uint8_t, 42> foo(42);
cxx::generate(foo, [counter=0]() mutable { return counter++; });
```

But in the case that the elements are not default constructable we would have to pursue your approach since the containers have different method names to insert another element.

Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp]: removed the check

Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp]: you're example for generate won't work since `foo.begin() == foo.end()`

Comment (elfenpiff) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp]: @elBoberido, see the first line:
```cpp
cxx::vector<uint8_t, 42> foo(42); // this ctor creates 42 elements with the default ctor
```
This is a full vector and `foo.begin() != foo.end()`.

**Review by dkroenke — COMMENTED** [review]
LGTM, just a nitpick from my side.

**Review by dkroenke — DISMISSED** [review]

File: iceoryx_examples/complexdata/iox_publisher_vector.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_publisher_vector.cpp]: @elfenpiff in this case you call the default ctor first, just to afterwards immediately replace the values. Not very efficient ;)

File: iceoryx_examples/complexdata/iox_publisher_complexdata.cpp (hunk 17 above)
Comment (elBoberido) [reply iceoryx_examples/complexdata/iox_publisher_complexdata.cpp:23]: I agree with Matthias. We should promote love, not killing ;)
This should be done in a separate PR, though ... maybe when geoffrey takes care of the syncing ;)

File: iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp [hunk 23]
```diff
@@ -0,0 +1,138 @@
...
+
+                s << std::endl << "variantVector:";
+                separator = " ";
+                for (const auto& i : sample->variantVector)
+                {
+                    switch (i.index())
+                    {
+                    case 0:
+                        s << separator << *i.template get_at_index<0>();
+                        separator = ", ";
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp:105]: this could be moved out of the switch statement

File: iceoryx_examples/complexdata/README.md [hunk 24]
```diff
@@ -0,0 +1,204 @@
...
+
+Our subscriber application iterates over the received vector to print its entries to the console. Note that the `separator` is only
+used for a easy to read output.
+
+```cpp
+for (const auto& entry : *sample)
+{
+    s << separator << entry;
+}
+std::cout << s.str();
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/README.md:55]: this is outdated, please update

File: iceoryx_examples/complexdata/README.md [hunk 25]
```diff
@@ -0,0 +1,204 @@
...
+### Subscriber application receiving a complex data structure
+
+The subscriber application just prints the received data to the console. For the `optionalList` we have to check whether the
+`optional` contains a value. As in the first example, the `separator` is used for a clear output.
+
+```cpp
+for (const auto& entry : sample->optionalList)
+{
+    (entry.has_value()) ? s << separator << entry.value() : s << separator << "optional is empty";
+}
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/README.md:156]: this is also outdated

File: iceoryx_examples/complexdata/README.md [hunk 26]
```diff
@@ -0,0 +1,204 @@
...
+
+To print the elements of the `floatStack`, we pop elements until the stack is empty.
+
+```cpp
+auto stackCopy = sample->floatStack;
+while (stackCopy.size() > 0U)
+{
+    auto result = stackCopy.pop();
+    s << separator << result.value();
+}
```
Comment (elBoberido) [inline iceoryx_examples/complexdata/README.md:167]: same here

File: iceoryx_examples/complexdata/README.md (hunk 24 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/complexdata/README.md:55]: oh my geoffrey... ;)

Comment (elBoberido) [reply iceoryx_examples/complexdata/README.md:55]: you can already use goeffrey if you want. I use it for the user-header example and it helps a lot. There is now also a readme in the geoffrey repo which explains how to use it :)

File: iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py [hunk 27]
```diff
@@ -0,0 +1,99 @@
...
+        process_list[1],
+        process_list[2],
+        process_list[3],
+        roudi_process,
+        launch_testing.actions.ReadyToTest()
+    ]), {'iox-cpp-publisher-vector': process_list[0], 'iox-cpp-subscriber-vector': process_list[1],
+         'iox-cpp-publisher-complexdata': process_list[2], 'iox-cpp-subscriber-complexdata': process_list[3],
+         'roudi_process': roudi_process}
+
+# These tests will run concurrently with the dut process. After this test is done,
```
Comment (MatthiasKillat) [inline iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py:74]: sut? or maybe it is a dud ...

**Review by MatthiasKillat — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]

File: iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py (hunk 27 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py:74]: it's the abbreviation for device under test

File: iceoryx_examples/complexdata/topic_data.hpp (hunk 16 above)
Comment (MatthiasKillat) [reply iceoryx_examples/complexdata/topic_data.hpp:28]: Sure, as I said. Would this be a library header I would reject this argument.

**Review by MatthiasKillat — DISMISSED** [review]

**Review by MatthiasKillat — APPROVED** [review]

**Review by dkroenke — APPROVED** [review]
