### PR TITLE
Iox #713 shared chunk with absolute pointer

### LINKED ISSUE #713: SharedChunk should internally store an absolute pointer
## Brief feature description

The `SharedChunk` should store an absolute pointer to the respective `ChunkManagement` instead of a `iox::rp::RelativePointer`.

## Detailed information

The `SharedChunk` stores internally a `iox::rp::RelativePointer` to the respective `ChunkManagement`. This is not needed since the `SharedChunk` is not used from the shared memory. With the `iox::rp::RelativePointer` there is always an unneeded overhead when accessing the actual chunk.

### LINKED ISSUE #729: loanPreviousChunk is broken
## Required information

**Operating system:**
all

**Compiler version:**
all

**Observed result or behaviour:**
loanPreviousChunk can currently not be used since it does not compile

**Expected result or behaviour:**
Should either compile or be removed from the API.

**Conditions where it occurred / Performed steps:**
Call `loanPreviousChunk` on a publisher.

The decision was to remove the API and add it later if necessary

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer

This started as small optimization to have the `SharedChunk` have an absolute pointer to the `ChunkManagement`. It tuned out that the `SharedChunk` was used in the shared memory, which is not allowed. I refactored the handling of the `UsedChunkList` into the `ShmSafeUnmanagedChunk` and used that one for all the occurrences of `SharedChunks` in the shared memory. This made it also possible to remove the `ChunkTuple`

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #713 
- Closes #729

### CODE REVIEW

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 1]
```diff
@@ -0,0 +1,266 @@
...
+
+TEST_F(ShmSafeUnmanagedChunk_test, ConstructedWithEmptySharedChunkResultsInLogicallyNullptr)
+{
+    SharedChunk sharedChunk;
+    ShmSafeUnmanagedChunk sut(sharedChunk);
+
+    EXPECT_TRUE(sut.isLogicalNullptr());
+}
+
+TEST_F(ShmSafeUnmanagedChunk_test, CallIsLogicalNullptrOnSutConstructedWithSharedChunkResultsNotInLogicalyNullptr)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:83]: ...InLogicalNullptr
same in the following test names

File: iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+#include "iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp"
+
+
+namespace iox
+{
+namespace mepoo
+{
+static_assert(sizeof(ShmSafeUnmanagedChunk) <= 8U, "The ShmSafeUnmanagedChunk size must not exceed 64 bit!");
```
Comment (elfenpiff) [inline iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp:24]: Why that? Is it caused by SoFi which then would not be lock-free anymore? Maybe we should add the reasoning here as a comment.

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 3]
```diff
@@ -0,0 +1,266 @@
...
+    auto sharedChunk = getChunkFromMemoryManager();
+
+    ShmSafeUnmanagedChunk sut(sharedChunk);
+
+    EXPECT_FALSE(sut.isNotLogicalNullptrAndHasNoOtherOwners());
+
+    sut.releaseToSharedChunk();
+}
+
+TEST_F(ShmSafeUnmanagedChunk_test, Foo)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:255]: Foo?

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 4]
```diff
@@ -0,0 +1,266 @@
...
+    static constexpr uint32_t CHUNK_SIZE = 128;
+
+    iox::posix::Allocator m_memoryAllocator{m_memory.get(), MEMORY_SIZE};
+};
+
+TEST_F(ShmSafeUnmanagedChunk_test, DefaultConstructedResultsInLogicallyNullptr)
+{
+    ShmSafeUnmanagedChunk sut;
+
+    EXPECT_TRUE(sut.isLogicalNullptr());
```
Comment (elfenpiff) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:72]: You once suggest (also with an article) that we should test all side effects in one test. In this case I would add here that `getChunkHeader` returns the `nullptr` and all the other methods. This would reduce the tests a bit but I am still unsure if we should pursue this here.

Your approach is nice, readable and we can check that everything is covered but I wanted to mention this to you since it was a suggestion from you.

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 5]
```diff
@@ -0,0 +1,266 @@
...
+    EXPECT_EQ(sut.getChunkHeader(), nullptr);
+}
+
+TEST_F(ShmSafeUnmanagedChunk_test, CallGetChunkHeaderOnConstSutConstructedWithSharedChunkResultsInValidHeader)
+{
+    auto sharedChunk = getChunkFromMemoryManager();
+
+    ShmSafeUnmanagedChunk sut(sharedChunk);
+
+    [&](const ShmSafeUnmanagedChunk& sut) {
```
Comment (elfenpiff) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:205]: This looks freaky - I like it!

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 6]
```diff
@@ -0,0 +1,266 @@
...
+    sut.releaseToSharedChunk();
+}
+
+TEST_F(ShmSafeUnmanagedChunk_test, CallIsNotLogicalNullptrAndHasNoOtherOwnersOnOnSutConstructedWithSharedChunkAndOtherOwnerResultsInFalse)
+{
+    auto sharedChunk = getChunkFromMemoryManager();
+
+    ShmSafeUnmanagedChunk sut(sharedChunk);
+
+    EXPECT_FALSE(sut.isNotLogicalNullptrAndHasNoOtherOwners());
```
Comment (elfenpiff) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:250]: I would add two more tests here.

1. let the `sharedChunk` from this test go out of scope and then `isNotLogicalNullptrAndHasNoOtherOwners` should be true again.
2. call `isNotLogicalNullptrAndHasNoOtherOwners` after you released a valid shared chunk with `releaseToSharedChunk`

File: iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+    /// @note the maximum number of valid ids
+    static constexpr id_t MAX_VALID_ID{ID_RANGE - 1U};
+    /// id_t is 16 bit and the offset consumes the remaining 48 bits -> offset range is 2^48 - 1
+    static constexpr offset_t OFFSET_RANGE{(1ULL << 48U) - 1U};
+    /// @note this represents the offset of a logically nullptr;
+    static constexpr offset_t NULL_POINTER_OFFSET{OFFSET_RANGE};
+    /// @note the maximum offset which can be represented
+    static constexpr offset_t MAX_VALID_OFFSET{OFFSET_RANGE - 1U};
+    /// @note internal representation of a nullptr
+    static constexpr offset_t LOGICAL_NULLPTR{std::numeric_limits<offset_t>::max()};
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp:72]: I would rather write
```
static constexpr offset_t LOGICAL_NULLPTR{NULL_POINTER_ID << 48 + NULL_POINTER_OFFSET};
```

Then we are able to doodle around with the `NULL_POINTER_ID` and `NULL_POINTER_OFFSET` and the logic is not somehow doubled.

File: iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+
+  private:
+    uint64_t m_idAndOffset{LOGICAL_NULLPTR};
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp:75]: Could we make a bitfield out of this like:
```cpp
   id_t id : 16;
   offset_t offset : 48;
```

Then we could get rid of the bitshifts and the code could be maybe more readable?!

File: iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp [hunk 9]
```diff
@@ -0,0 +1,133 @@
...
+
+    RelativePointerData sut{ID, OFFSET};
+
+    EXPECT_FALSE(sut.isLogicalNullptr());
+}
+
+TEST(RealtivePointerData_test, ConstructedWithMaxIdAndOffsetResultsNotInLogicallyNullptr)
+{
+    constexpr uint16_t ID{RelativePointerData::MAX_VALID_ID};
+    constexpr uint64_t OFFSET{RelativePointerData::MAX_VALID_OFFSET};
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp:85]: Could you please add also a test for the limits.
```
    constexpr uint16_t ID{RelativePointerData::MAX_VALID_ID - 1U};
    constexpr uint64_t OFFSET{RelativePointerData::MAX_VALID_OFFSET - 1U};
```
This should result in a non logical nullptr.

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp (hunk 3 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:255]: Not descriptive enough? Shall I add a `Bar`?

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp [hunk 10]
```diff
@@ -36,7 +36,6 @@ class SharedChunk
   public:
     SharedChunk() = default;
     SharedChunk(ChunkManagement* const resource) noexcept;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp:38]: Why? I think it was intentional to have a implicit construction

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+{
+namespace mepoo
+{
+class ShmSafeUnmanagedChunk
+{
+  public:
+    ShmSafeUnmanagedChunk() noexcept = default;
+
+    /// @brief takes a SharedChunk without decrementing the chunk reference counter
+    ShmSafeUnmanagedChunk(SharedChunk chunk) noexcept;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:33]: Same here, it makes it quite cumbersome to use

File: iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp (hunk 2 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp:24]: to prevent Frankenstein Objects when objects are copied, like in the SoFi where we use memcpy. I can add a note.

File: iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp (hunk 8 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp:75]: not if you want to support Window. For some reasons the bitfield you mentioned is larger than 64 bytes. Luckily, the compiler generates exactly the same code like with the bitfield.

File: iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp (hunk 9 above)
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp:85]: I can do it, but I do not see a gain in having this tests. What is your intention with those tests?

**Review by mossmaurice — COMMENTED** [review]
Just had a small glimpse and no full review.

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp:38]: I thought we had this as code rule and I thought the implicit construction was only intentional for the relocatable ptr but maybe you are right ...

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp [hunk 12]
```diff
@@ -0,0 +1,66 @@
...
+
+    /// @brief Creates a SharedChunk without incrementing the chunk reference counter and invalidates itself
+    SharedChunk releaseToSharedChunk() noexcept;
+
+    /// @brief Creates a SharedChunk with incrementing the chunk reference counter and does not invalidate itself
+    SharedChunk duplicateToSharedChunk() noexcept;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:39]: well, it increments the refcount and has to be seen in combination with `releaseToSharedChunk`

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:33]: I agree but I thought there was a code rule somewhere to use explicit to avoid accidental implicit conversions.

File: iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp (hunk 2 above)
Comment (elfenpiff) [reply iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp:24]: Ah but this is not a problem with memcpy! Yeah you would have a Frankenstein object but since you are using only memcpy and never call any methods on the object itself it is alright.

File: iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp (hunk 8 above)
Comment (elfenpiff) [reply iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_pointer_data.hpp:75]: Ah I remember. Thanks to Windows our life never gets boring...

File: iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp (hunk 9 above)
Comment (elfenpiff) [reply iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp:85]: To see that it is really working. Lets assume the limits are wrong it and the MAX_VALID_OFFSET is a 54 bit number then it would override some parts of the id and the whole system could crash.

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:39]: create a new shared chunk without releasing ownership. maybe `copyToSharedChunk` or we use the conversion operator `operator SharedChunk()`. What do you think is more understandable.

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp (hunk 3 above)
Comment (elfenpiff) [reply iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:255]: Please add a something with a hypnotoad and a unicorn or maybe hypnocornunitoad

Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp]: we don't yet have a brain slug

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:39]: copy is ambiguous since this is unmanaged a plain copy would essentially be the same as `releaseToSharedChunk` but with leaving a a dangling pointer behind. I'm open to change it, but it should clearly show that the ref count is incremented

File: iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp (hunk 9 above)
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_relative_pointer_data.cpp:85]: already tested with another test

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp:39]: how about `cloneToSharedChunk`?

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]
