### PR TITLE
[#2516] Fix alignment of `variant` alternatives and `expected` documentation

### LINKED ISSUE #2492: Documentation of iox::cxx::expected is incorrect
## Required information

**Operating system:**
Not applicable

**Compiler version:**
Not applicable

**Eclipse iceoryx version:**
Since `v1.0.0`, and still present in `main` branch

**Observed result or behaviour:**
The documentation for the bool operator of the class iox::cxx::expected is incorrect and states that it returns true if the expected contains an error.
On the main branch, only the documentation of the returned value is incorrect (the description is correct), and the operation has_value also has an incorrect documentation for the returned value.

**Expected result or behaviour:**
The documentation should state that those operations returns true is the expected contains a value.

**Conditions where it occurred / Performed steps:**
Read the documentation located at https://iceoryx.io/v2.0.5/API-reference/hoofs/Classes/classiox_1_1cxx_1_1expected_3_01ValueType_00_01ErrorType_01_4/#function-operator-bool and in the source code.

## Additional helpful information
Not applicable

### LINKED ISSUE #2516: The 'variant' does not apply the alignment of its alternatives
## Required information

**Operating system:**

any

**Compiler version:**

any

**Eclipse iceoryx version:**

`main` branch after the v2.0 release

**Observed result or behaviour:**

The `variant` does not apply alignment of its alternatives.

**Expected result or behaviour:**

The `variant` should apply the alignment of its alternatives.

**Conditions where it occurred / Performed steps:**

Add a type which need an alignment which is larger than 8 on 64 bit or larger than 4 on 32 bit and check the address of the variant alternative.

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Consider a second reviewer for complex new features or larger refactorings
- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #2492 
- Closes #2516

### CODE REVIEW

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

File: iceoryx_hoofs/test/moduletests/test_vocabulary_variant.cpp [hunk 1]
```diff
@@ -729,4 +729,17 @@ TEST_F(variant_Test, TwoVariantsWithUnequalValueAreUnequal)
     EXPECT_FALSE(sut1 == sut2);
 }
 
+TEST_F(variant_Test, VariantUsesMaxAlignment)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_hoofs/test/moduletests/test_vocabulary_variant.cpp:733]: Consider updating the copyright header.

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
