### PR TITLE
iox-#1821 improve error message when creating read-only segment

### LINKED ISSUE #1821: Creating a read-only SharedMemoryObject
## Required information

**Operating system:**
Ubuntu 20.04.3 LTS

**Compiler version:**
gcc 8.4

**Observed result or behaviour:**

The produced error is

```
[ 22 ]  Invalid argument
Unable to create shared memory with the following properties [ name = readOnlyShmMem, access mode = AccessMode::READ_ONLY, open mode = OpenMode::PURGE_AND_CREATE, mode = 0000, sizeInBytes = 100 ]
Requested Shared Memory is larger then the maximum file size or the filedescriptor does not belong to a regular file.
```

**Expected result or behaviour:**

The error message is incorrect: both the size and the file are all right, the problem is that creating the segment involves `truncate`, which requires write permission.

The error should idenfity the READ_ONLY AccessMode as the problem, or the call should not accept AccessMode in the first place.

**Conditions where it occurred / Performed steps:**

```
    auto sut = iox::posix::SharedMemoryObjectBuilder()
                   .name("readOnlyShmMem")
                   .memorySizeInBytes(100)
                   .accessMode(iox::posix::AccessMode::READ_ONLY)
                   .openMode(iox::posix::OpenMode::PURGE_AND_CREATE)
                   .create();
```

### PR DESCRIPTION
**Pull request by tobiasblass**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1821

### CODE REVIEW

File: iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp [hunk 1]
```diff
@@ -82,6 +82,21 @@ TEST_F(SharedMemoryObject_Test, CTorOpenNonExistingSharedMemoryObject)
...
+{
+    ::testing::Test::RecordProperty("TEST_ID", "80684160-b243-4ca1-b285-118d2ef36108");
+    auto sut = iox::posix::SharedMemoryObjectBuilder()
+                   .name("readOnlyShmMem")
+                   .memorySizeInBytes(100)
+                   .accessMode(iox::posix::AccessMode::READ_ONLY)
+                   .openMode(iox::posix::OpenMode::PURGE_AND_CREATE)
+                   .create();
+
+    // TODO(tobias.stark): Check that the right error is returned, not just any error.
```
Comment (elfenpiff) [inline iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp:95]: I think when the shared memory is created read only the `ftruncate` fails which resizes the shared memory to 100 bytes. Therefore it should be `SharedMemoryError::INSUFFICIENT_PERMISSIONS`.

What is the output of the test when you run the code? Since the underlying posix call abstraction handles all the system calls you should see an error output from the line where it fails and the errno code.

File: iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp [hunk 2]
```diff
@@ -142,7 +142,7 @@ cxx::expected<SharedMemory, SharedMemoryError> SharedMemoryBuilder::create() noe
                               << "\". This may be a SharedMemory leak." << std::endl;
                 });
 
-            return cxx::error<SharedMemoryError>(SharedMemory::errnoToEnum(result->errnum));
+            return cxx::error<SharedMemoryError>(SharedMemory::errnoToEnum(result.get_error().errnum));
```
Comment (elfenpiff) [inline iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp:145]: Good fetch!

File: iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp [hunk 3]
```diff
@@ -142,7 +142,7 @@ cxx::expected<SharedMemory, SharedMemoryError> SharedMemoryBuilder::create() noe
                               << "\". This may be a SharedMemory leak." << std::endl;
                 });
```
Comment (elfenpiff) [inline iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp:144]: I think a good solution would be to add a check right before `ftrunctate` in line 122.
If here the shared memory `hasOwnership` and the `m_accessMode == AccessMode::READ_ONLY` it should fail.

For this you could introduce a new `SharedMemoryError` enum value and return it here in combination with an error message. This could then also be verified in the unit test and wouldn't fail in windows.

Or you could do a check right in the beginning of the `create()` method to verify that `OpenMode::**CREATE**` is not combined with `AccessMode::READ_ONLY`.

Comment (tobiasblass) [reply iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp:151]: @elfenpiff I implemented something similar to your suggestion. Checking before the `truncate` would work, but it could potentially hide errors. I believe we want to complain about READ_ONLY + OPEN_OR_CREATE, even if the file happens to already exist.

So I moved the check up, before the open-if-exist attempt. Since `hasOwnership` now has to be in scope during the open-check, I also used the opportunity to simplify the code there (the non-owning success path can now follow the same code path as the owning success path, with `hasOwnership` distinguishing between the two).

Pipeline seems to run throught, the invalid links are not caused by this MR.

/cc @mossmaurice

File: iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp (hunk 1 above)
Comment (tobiasblass) [reply iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp]: I introduced a new error code and moved this test to the `test_posix_shared_memory.cpp` test, where the error-code from `SharedMemory` is available.

**Review by elfenpiff — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]
Looks good. Sorry for the long delay in review.

**Comment by elBoberido** [comment]
@tobiasblass ... oh, and it seems you have to rebase

File: iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp [hunk 4]
```diff
@@ -68,6 +68,16 @@ expected<SharedMemory, SharedMemoryError> SharedMemoryBuilder::create() noexcept
...
     auto nameWithLeadingSlash = addLeadingSlash(m_name);
 
+    bool hasOwnership = (m_openMode == OpenMode::EXCLUSIVE_CREATE || m_openMode == OpenMode::PURGE_AND_CREATE
+                         || m_openMode == OpenMode::OPEN_OR_CREATE);
+
+    if (hasOwnership && (m_accessMode == AccessMode::READ_ONLY))
+    {
+        std::cerr << "Cannot create shared-memory file \"" << m_name << "\" in read-only mode. "
+                  << "Initializing a new file requires write access" << std::endl;
+        return cxx::error<SharedMemoryError>(SharedMemoryError::INCOMPATIBLE_OPEN_AND_ACCESS_MODE);
```
Comment (elBoberido) [inline iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp:78]: @tobiasblass we moved some code around to create a flat include structure and namespace. `iox::cxx::error` is now just `iox::error`. Removing the `cxx::` should fix the CI

**Review by elBoberido — APPROVED** [review]

**Comment by tobiasblass** [comment]
@elfenpiff I've rebased to latest master. Can you re-approve for the second approval?

**Review by elfenpiff — APPROVED** [review]

**Comment by elBoberido** [comment]
@tobiasblass took quite some time but finally it is merged. For the next PR we have to improve our review time :)
