### PR TITLE
iox-#1108 Fix potential segfault in string

### LINKED ISSUE #1108: `cxx::string` initialization with nullptr leads to segfault
## Brief feature description

When using the `cxx::string` with a `nullptr` as constructor argument the constructor segfaults.

## Detailed information

The problem lies in using `strnlen` in combination with a `nullptr` which leads to a segfault.
Example code:
```cpp
iox::cxx::string<100> myString(iox::cxx::TruncateToCapacity, nullptr);
```

This should create an empty string and not lead to a segfault.

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

This PR fixes a potential segfault in `string(TruncateToCapacity_t, const char* const other)` when `other` is a `nullptr`. Actually `strnlen` should fail when called with a `nullptr` but it seems that it is not invoked before delegating to the other c'tor.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1108

### CODE REVIEW

**Review by elBoberido — APPROVED** [review]

File: iceoryx_hoofs/test/moduletests/test_cxx_string.cpp [hunk 1]
```diff
@@ -308,6 +308,17 @@ TYPED_TEST(stringTyped_test, UnsafeCharToStringConvConstrWithSizeGreaterCapaResu
     EXPECT_THAT(testSubject.size(), Eq(STRINGCAP));
 }
 
+TYPED_TEST(stringTyped_test, UnsafeCharToStringConvConstrWithNullPtrResultsEmptyString)
```
Comment (elBoberido) [inline iceoryx_hoofs/test/moduletests/test_cxx_string.cpp:311]: Oh, I was a little bit fast. Please update the copyright date

**Review by elfenpiff — DISMISSED** [review]

**Review by elfenpiff — APPROVED** [review]

**Review by MatthiasKillat — APPROVED** [review]
