### PR TITLE
iox-#542 creation pattern detailed doxygen docu

### LINKED ISSUE #542: Fix resource leak caused by move ctor/assignment
## Required information

All versions

**Observed result or behaviour:**
The classes:
 - [x] `unix_domain_socket` (fixed by https://github.com/eclipse-iceoryx/iceoryx/pull/550)
 - [x] `shared_memory`
 - [x] `memory_map`
 - [x] `GenericRAII`

are not cleaning up the resources while performing move. This could lead to a resource leak when for instance the following pseudo code is executed.

```cpp
SharedMemory mySharedMemory; // create a shared memory file A
SharedMemory anotherSharedMemory; // create a shared memory file B

mySharedMemory = std::move(anotherSharedMemory); // mySharedMemory takes ownership of B without releasing A

// at this point the shared memory file A is leaked

```

**Classes with correct move resource handling:**
- `Semaphore`
- `MessageQueue`
- `optional`
- `variant`

**Handle undefined state:**
- [x] `optional`
- [x] `expected`

**creation pattern:**
- [x] `shared_memory`
- [x] `shared_memory_object`
- [x] `memory_map`

**Fix incorrect move CTor/assigned in all classes derived from `DesignPattern::Creation`**
According to: https://isocpp.org/wiki/faq/assignment-operators every move ctor/assignment operator has to be implemented like
```cpp
Derived& Derived::operator= (Derived&& d)
{
  // self-assignment is not allowed in move assignment
  Base::operator= (std::move(d));
  // Do the rest of your assignment operator here...
  return *this;
}
```
- [x] `shared_memory`
- [x] `shared_memory_object`
- [x] `memory_map`
- [x] `semaphore`
- [x] `message_queue`
- [x] `unix_domain_socket`
- [x] Write a detailed documentation how to use the creation pattern correctly - especially the assignment operator part!

**Fix sighandler**
- [x] Write mini `sigaction` abstraction and put it into utils to remove the 5 lines of code.
- [x] Use `posix::SignalHandler` everywhere

### Details
* Consider [this](https://github.com/eclipse-iceoryx/iceoryx/pull/550#discussion_r573629792) discussion

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [x] Merge

## References

- Closes #542

### CODE REVIEW

File: iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp [hunk 1]
```diff
@@ -23,6 +23,68 @@
...
+///       }
+///
+///       // the creation pattern is the only one which should be allowed to construct
+///       // the class, therefore it has to be friend of that class
+///       friend class Creation<MyResourceAbstraction, MyResourceAbstractionError>;
+///     private:
+///       MyResourceAbstraction(int a) {
+///         if ( a > 0) {
+///           // we are able to initialize the class an set m_isInitialized to true
+///           m_isInitialized = true;
```
Comment (dkroenke) [inline iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp:61]: `m_isInitialized` is not declared because it is provided by the `Creation` class. We should maybe explicitly state that the user need to set this bool when the constructor completes successfully.

**Review by dkroenke — APPROVED** [review]

File: iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp [hunk 2]
```diff
@@ -23,6 +23,77 @@
 
 namespace DesignPattern
 {
+/// @brief This pattern can be used if you write an abstraction where you have
+///        to throw an exception in the constructor when you for instance would
```
Comment (mossmaurice) [inline iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp:27]: Nitpick: We are never throwing exceptions in iceoryx. What about "..you have to signal an error in the constructor.."?

File: iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp [hunk 3]
```diff
@@ -23,6 +23,77 @@
...
+///        returned, otherwise an error value which describes the error.
+///        Additionally, this class is providing two protected member variables
+///        `m_isInitialized` and `m_errorValue`. The user always has to set
+///        `m_isInitialized` to true when the object construction was successful
+///        otherwise one sets it to false and write the corresponding error cause
+///        in the provided `m_errorValue` variable which is then returned to
+///        the user.
+/// @code
+///   enum class MyResourceAbstractionError {
+///     ResourceNotAvailable,
```
Comment (mossmaurice) [inline iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp:43]: `ALL_CAPS`?

**Review by mossmaurice — APPROVED** [review]
