### PR TITLE
Iox #408 offer and subscribe on create

### LINKED ISSUE #408: Refine modern pub/sub API
_Originally posted by @budrus in https://github.com/eclipse/iceoryx/pull/360#discussion_r535725529_

How do we prevent this? With the old API people were more aware that they should not copy pointers that are coming from the middleware. In ara::com it's a unique ptr to make this even harder. I guess our Sample is also just an advanced unique_ptr but when I look at this code I fear that people think they must call `sample.get()` to be able to work with the payload. But in fact `get()` is the most dangerous method. 

We need `get` for frameworks where you get a Sample from the iceoryx API and have to pass e.g. a void* to the next layer (like in ROS). Then this layer has to return the pointer and the sample must be released with the iceoryx API. 
How would this look like? @elBoberido @ithier 

- take a sample
- get the raw pointer with `sample.get()`
- release the sample for not releasing the chunk when it goes out of scope, `sample.release()`
- pass the raw pointer to the next layer
- something happens
- raw pointer is returned from the next layer
- create a Sample with the raw pointer
- let the Sample go out of scope for releasing the chunk  

Shoud we make an example for this? This is a use case a lot people have. Would it be better to have a `release()` that releases the ownersip but additionally returns the pointer like in the STL and to remove the get() method? Having a get() that gives you a pointer to a shared memory chunk which is released when the Sample goes out of scope is a dangerous thing . The STL unique_ptr also has it but maybe people are more aware there 

Here in iceperf we want to copy the payload. How can we do something like `auto receivedSample = *(static_cast<const PerfTopic*>(receivedChunk));`?

With the `Sample` class, the `get` method and the fact that the subscriber has no `releaseChunk` method any more, the lifetime and ownership question has some complexity. This must be well documented in the new API docu @elfenpiff @FerdinandSpitzschnueffler @MatthiasKillat

**To-do:**
- [ ] Add offerAndSubscribeOnCreate to `PublisherOptions` and enable it as default (will close #575)
- [x] Remove `Sample` from untyped API and make it feel similar to the C-API (releaseChunk called by user)
- [x] Simplify the typed API, but not returning an `expected` but instead an `optional` and do the error handling for the user under the hood (fail fast & hard)
- [x] ~~Rename CaPro strings and add terminology table in overview.md~~
- [x]   Create a follow up issue that covers open points 
   - ~~define a payload_t or use void*?~~
   - using the header with the C API -> follow-up #585 
   - [x ]add a releaseChunk to the untyped publisher?

### LINKED ISSUE #575: example multi publisher, subscriber -> missing some data
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.3.0

**Observed result or behaviour:**
The multi-subscriber always miss the two "counter 0" data sent from the publisher.
Counter Instance sending: id 1 counter 0
Counter Instance sending: id 2 counter 0

**Expected result or behaviour:**
Multi-subscriber shall receive all the data sent by the publisher.

**Conditions where it occurred / Performed steps:**
Ran the applications in the following order.
1. iox-roudi
2. iox-multi-subscriber
3. iox-multi-publisher

### PR DESCRIPTION
**Pull request by budrus**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer
This introduces the offer on create for publishers and subscribe on create for subscribers. This is available in the options for publishers and subscribers. The default is now to immediately offer a publisher when creating it and to immediately request subscription when creating a subscriber.  I.e. when using the default options it is no more necessary to call offer() and subscribe(). If people do not want this behavior (e.g. for ara::com) they have to disable it in the options for publishers and subscriber. 
NOTE: The C API is not yet adapted as it makes sense to first merge the PR that introduces the options structs there #580 

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #408 
- Closes #575

### CODE REVIEW

File: iceoryx_binding_c/test/moduletests/test_publisher.cpp [hunk 1]
```diff
@@ -116,9 +116,9 @@ class iox_pub_test : public Test
     cpp2c_Publisher m_sut;
 };
```
Comment (elfenpiff) [inline iceoryx_binding_c/test/moduletests/test_publisher.cpp:118]: Please adjust copyright header!

**Review by mossmaurice — COMMENTED** [review]
I've not yet reviewed the tests.

File: iceoryx_posh/source/roudi/port_manager.cpp [hunk 2]
```diff
@@ -171,36 +148,42 @@ void PortManager::handlePublisherPorts() noexcept
     }
 }
 
+void PortManager::doDiscoveryForPublisherPort(PublisherPortRouDiType& publisherPort) noexcept
+{
+    publisherPort.tryGetCaProMessage().and_then([this, &publisherPort](auto caproMessage) {
```
[the remark this answers is not in the document]
Comment (budrus) [reply iceoryx_posh/source/roudi/port_manager.cpp:153]: Did we? I had a big refactoring some months ago to introduce it here. What is you flavor of the week?

File: iceoryx_examples/iceperf/iceoryx.cpp [hunk 3]
```diff
@@ -37,9 +37,6 @@ void Iceoryx::initFollower() noexcept
 
 void Iceoryx::init() noexcept
 {
```
Comment (elfenpiff) [inline iceoryx_examples/iceperf/iceoryx.cpp:39]: Please adjust copyright header!

File: iceoryx_posh/source/roudi/roudi.cpp [hunk 4]
```diff
@@ -181,19 +181,20 @@ void RouDi::processMessage(const runtime::IpcMessage& message,
...
         else
         {
             capro::ServiceDescription service(cxx::Serialization(message.getElementAtIndex(2)));
-            cxx::Serialization portConfigInfoSerialization(message.getElementAtIndex(5));
+            cxx::Serialization portConfigInfoSerialization(message.getElementAtIndex(6));
 
             popo::PublisherOptions options;
             options.historyCapacity = std::stoull(message.getElementAtIndex(3));
             options.nodeName = NodeName_t(cxx::TruncateToCapacity, message.getElementAtIndex(4));
+            options.offerOnCreate = (0U == std::stoull(message.getElementAtIndex(5))) ? false : true;
```
Comment (elfenpiff) [inline iceoryx_posh/source/roudi/roudi.cpp:197]: Nice and clean :D

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 5]
```diff
@@ -72,51 +72,74 @@ class PublisherPort_test : public Test
     iox::posix::Allocator m_memoryAllocator{m_memory, MEMORY_SIZE};
     iox::mepoo::MePooConfig m_mempoolconf;
     iox::mepoo::MemoryManager m_memoryManager;
```
Comment (elfenpiff) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:74]: Please adjust copyright header!

File: iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp [hunk 6]
```diff
@@ -57,13 +57,24 @@ class SubscriberPortSingleProducer_test : public Test
 
     iox::cxx::GenericRAII m_uniqueRouDiId{[] { iox::popo::internal::setUniqueRouDiId(0); },
                                           [] { iox::popo::internal::unsetUniqueRouDiId(); }};
```
Comment (elfenpiff) [inline iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp:59]: Please adjust copyright header!

File: iceoryx_posh/source/roudi/port_manager.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_posh/source/roudi/port_manager.cpp:153]: I think we shouldn't make a rule here and leave it at artistic freedom....

File: iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp [hunk 7]
```diff
@@ -32,6 +32,10 @@ struct PublisherOptions
 
     /// @brief The name of the node where the publisher should belong to
     iox::NodeName_t nodeName{""};
+
+    /// @brief The option whether the publisher should already be offered when creating it
+    bool offerOnCreate = {true};
```
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp:37]: But I like `bool offerOnCreate = true` since it is better readable...

File: iceoryx_examples/icedelivery/iox_publisher_with_options.cpp [hunk 8]
```diff
@@ -36,13 +36,23 @@ int main()
     auto signalIntGuard = iox::posix::registerSignalHandler(iox::posix::Signal::INT, sigHandler);
```
[the remark this answers is not in the document]
Comment (budrus) [reply iceoryx_examples/icedelivery/iox_publisher_with_options.cpp:36]: For me this is extra effort without much benefit. The extended _history example also was there and the untyped example is also in this folder. And one cool thing is that they all can be mixed, as they have the same CaPro IDs. This is maybe also more clear when they are all in one folder

File: iceoryx_binding_c/test/moduletests/test_publisher.cpp (hunk 1 above)
Comment (budrus) [reply iceoryx_binding_c/test/moduletests/test_publisher.cpp:118]: This was just a test if you check the headers ;-)

Comment (elfenpiff) [reply iceoryx_binding_c/test/moduletests/test_publisher.cpp:119]: You are testing me, or?! :scientist: 

Only one company per line in the copyright header.

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp (hunk 5 above)
Comment (elfenpiff) [reply iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:75]: Every company gets its own line in the copyright header ... I hate it too....

File: iceoryx_binding_c/test/moduletests/test_publisher.cpp (hunk 1 above)
Comment (budrus) [reply iceoryx_binding_c/test/moduletests/test_publisher.cpp:119]: Arrrhhh. second

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 9]
```diff
@@ -356,6 +356,27 @@ TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithSameServiceDescriptionsAndOne
     }
 }
 
+TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithoutOfferOnCreate)
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_posh_runtime.cpp:359]: `..LeadsToNoOffer`?

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 10]
```diff
@@ -356,6 +356,27 @@ TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithSameServiceDescriptionsAndOne
...
+    iox::popo::PublisherOptions publisherOptions;
+    publisherOptions.offerOnCreate = false;
+
+    const auto publisherPortData = m_runtime->getMiddlewarePublisher(
+        iox::capro::ServiceDescription(99U, 1U, 20U), publisherOptions, iox::runtime::PortConfigInfo(11U, 22U, 33U));
+
+    EXPECT_FALSE(publisherPortData->m_offeringRequested);
+}
+
+TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithOfferOnCreate)
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_posh_runtime.cpp:370]: `..LeadsToOffer`?

File: iceoryx_examples/icecrystal/Readme.md [hunk 11]
```diff
@@ -51,11 +51,9 @@ The process view will show you the processes (incl. PID), which are currently re
     --port            Subscribe to port introspection data.
 
 The port view shows both publisher and subscriber ports that are created by RouDi in the shared memory. Their respective
-service description (service, instance, event) is shown to identify them uniquely. The columns `Process` and
-`used by process` display to which process the ports belong and how they are currently connected. Size in bytes of
-both sample size and chunk size (sample size + meta data) and statistical data of `Chunks [/Minute]` is provided as
-well. When a publisher port instantly provides data to a subscriber with the `subscribe()` call, the `Field` column is
-ticked. The service discovery protocol allows you to define the `Propagation scope` of the data. This can enable
+service description (service, instance, event) is shown to identify them uniquely. The columns `Process`  displays to which process the ports.
```
[the remark this answers is not in the document]
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/icecrystal/Readme.md:54]: It was actually my fault to not update this documentation. There will be more changes when merging #586, so I will update this document there.

**Review by mossmaurice — COMMENTED** [review]
Tests reviewed

File: iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp [hunk 12]
```diff
@@ -87,13 +100,22 @@ TEST_F(SubscriberPortSingleProducer_test, initialStateNoChunksLost)
...
     auto maybeCaproMessage = m_sutRouDiSideSingleProducer.tryGetCaProMessage();
 
     EXPECT_FALSE(maybeCaproMessage.has_value());
 }
 
+TEST_F(SubscriberPortSingleProducer_test, initialStateReturnsSubCaProMessageWithDefaultOptions)
+{
+    auto maybeCaproMessage = m_sutRouDiSideDefaultOptions.tryGetCaProMessage();
+
+    EXPECT_TRUE(maybeCaproMessage.has_value());
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp:114]: Please use ``ASSERT_TRUE`` otherwise we could enter undefined behavior land in the next line.

File: iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp [hunk 13]
```diff
@@ -360,11 +382,13 @@ TEST_F(SubscriberPortMultiProducer_test, initialStateNotSubscribed)
     EXPECT_THAT(m_sutUserSideMultiProducer.getSubscriptionState(), Eq(iox::SubscribeState::NOT_SUBSCRIBED));
 }
 
-TEST_F(SubscriberPortMultiProducer_test, initialStateReturnsNoCaProMessage)
+TEST_F(SubscriberPortMultiProducer_test, initialStateReturnsSubCaProMessageWithDefaultOptions)
 {
     auto maybeCaproMessage = m_sutRouDiSideMultiProducer.tryGetCaProMessage();
 
-    EXPECT_FALSE(maybeCaproMessage.has_value());
+    EXPECT_TRUE(maybeCaproMessage.has_value());
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp:389]: Please use ``ASSERT_TRUE``.

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp [hunk 14]
```diff
@@ -314,6 +314,80 @@ TEST_F(PortManager_test, doDiscovery_rightOrdering)
     EXPECT_THAT(subscriber2.getSubscriptionState(), Eq(iox::SubscribeState::SUBSCRIBED));
 }
 
+TEST_F(PortManager_test, subscribeOnCreate_subscribesWithoutDiscoveryLoopWhenPublisherAvailable)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp:317]: Please use UpperCamelCase for the test names.

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 15]
```diff
@@ -72,51 +73,75 @@ class PublisherPort_test : public Test
...
+    EXPECT_FALSE(m_sutNoOfferOnCreateUserSide.hasSubscribers());
 }
 
-TEST_F(PublisherPort_test, initialStateReturnsNoCaProMessage)
+TEST_F(PublisherPort_test, initialStateReturnsOfferCaProMessageWithDefaultOptions)
 {
-    auto maybeCaproMessage = m_sutRouDiSide.tryGetCaProMessage();
+    auto maybeCaproMessage = m_sutWithDefaultOptionsRouDiSide.tryGetCaProMessage();
+
+    EXPECT_TRUE(maybeCaproMessage.has_value());
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:120]: Please use ``ASSERT_TRUE``, otherwise there might be undefined behavior in the next line.

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 16]
```diff
@@ -72,51 +73,75 @@ class PublisherPort_test : public Test
...
 
 TEST_F(PublisherPort_test, offerCallResultsInOfferCaProMessage)
 {
-    m_sutUserSide.offer();
+    m_sutNoOfferOnCreateUserSide.offer();
 
-    auto maybeCaproMessage = m_sutRouDiSide.tryGetCaProMessage();
+    auto maybeCaproMessage = m_sutNoOfferOnCreateRouDiSide.tryGetCaProMessage();
 
     EXPECT_TRUE(maybeCaproMessage.has_value());
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:146]: Please use ``ASSERT_TRUE``.

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 17]
```diff
@@ -417,6 +438,28 @@ TEST_F(PoshRuntime_test, GetMiddlewareSubscriberSubscriberlistOverflow)
     EXPECT_TRUE(subscriberlistOverflowDetected);
 }
 
+TEST_F(PoshRuntime_test, GetMiddlewareSubscriberWithoutSubscribeOnCreate)
+{
+    iox::popo::SubscriberOptions subscriberOptions;
+    subscriberOptions.subscribeOnCreate = false;
+
+    auto subscriberPortData = m_runtime->getMiddlewareSubscriber(
+        iox::capro::ServiceDescription(99U, 1U, 20U), subscriberOptions, iox::runtime::PortConfigInfo(11U, 22U, 33U));
```
[the remark this answers is not in the document]
Comment (budrus) [reply iceoryx_posh/test/moduletests/test_posh_runtime.cpp:447]: @mossmaurice. I also thought about and came to the conclusion that it's totally don't care but OK, let's role the dices

File: iceoryx_examples/icecrystal/Readme.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (budrus) [reply iceoryx_examples/icecrystal/Readme.md:54]: Fine. I already saw your changes. I guess the last one has to merge.

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp (hunk 14 above)
Comment (budrus) [reply iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp:317]: I have adapted to my surroundings like a chameleon. So I'll go "all in" in this file

**Review by mossmaurice — DISMISSED** [review]
LGTM

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 18]
```diff
@@ -356,6 +356,27 @@ TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithSameServiceDescriptionsAndOne
     }
 }
 
+TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithoutOfferOnCreateLeadsToNotOfferedSubscriberBeingCreated)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_posh_runtime.cpp:359]: Please update the name: it's a publisher instead of a subscriber.

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 19]
```diff
@@ -356,6 +356,27 @@ TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithSameServiceDescriptionsAndOne
...
+    iox::popo::PublisherOptions publisherOptions;
+    publisherOptions.offerOnCreate = false;
+
+    const auto publisherPortData = m_runtime->getMiddlewarePublisher(
+        iox::capro::ServiceDescription(69U, 96U, 1893U), publisherOptions, iox::runtime::PortConfigInfo(11U, 22U, 33U));
+
+    EXPECT_FALSE(publisherPortData->m_offeringRequested);
+}
+
+TEST_F(PoshRuntime_test, GetMiddlewarePublisherWithOfferOnCreateLeadsToOfferedSubscriberBeingCreated)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_posh_runtime.cpp:370]: same here

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp [hunk 20]
```diff
@@ -207,10 +207,10 @@ void setDestroyFlagAndClearContainer(vector& container)
     container.clear();
 }
 
-TEST_F(PortManager_test, doDiscovery_singleShotPublisherFirst)
+TEST_F(PortManager_test, DoDiscoveryWithSingleShotPublisherFirst)
 {
-    PublisherOptions publisherOptions{1, "node"};
-    SubscriberOptions subscriberOptions{1, 1, "node"};
+    PublisherOptions publisherOptions{1, "node", false};
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp:212]: I guess @dkroenke would say: 'the big U is your friend' ;)

File: iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp [hunk 21]
```diff
@@ -87,20 +100,29 @@ TEST_F(SubscriberPortSingleProducer_test, initialStateNoChunksLost)
     EXPECT_FALSE(m_sutUserSideSingleProducer.hasLostChunksSinceLastCall());
 }
 
-TEST_F(SubscriberPortSingleProducer_test, initialStateReturnsNoCaProMessage)
+TEST_F(SubscriberPortSingleProducer_test, initialStateReturnsNoCaProMessageWhenNoSubOnCreate)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp:103]: The test names should be written in UpperCamelCase

File: iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp [hunk 22]
```diff
@@ -72,53 +73,77 @@ class PublisherPort_test : public Test
...
+    // publisher port w/ default options
+    iox::popo::PublisherOptions m_withDefaultPublisherOptions{};
+    iox::popo::PublisherPortData m_publisherPortDataDefault{
+        iox::capro::ServiceDescription("x", "y", "z"), "myApp", &m_memoryManager, m_withDefaultPublisherOptions};
+    iox::popo::PublisherPortUser m_sutWithDefaultOptionsUseriSide{&m_publisherPortDataDefault};
+    iox::popo::PublisherPortRouDi m_sutWithDefaultOptionsRouDiSide{&m_publisherPortDataDefault};
 };
 
-TEST_F(PublisherPort_test, initialStateIsNotOffered)
+TEST_F(PublisherPort_test, initialStateIsOfferedWithDefaultOptions)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp:100]: The test names should be written in UpperCamelCase.

**Review by FerdinandSpitzschnueffler — COMMENTED** [review]
Looks good. Only some minor findings but only change them if you feel like a pathfinder ;)

File: iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp (hunk 21 above)
Comment (budrus) [reply iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp:103]: And this one will be dedicated to @FerdinandSpitzschnueffler and to Ronny because of his birthday

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp (hunk 20 above)
Comment (budrus) [reply iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp]: OK, this one is dedicated to @dkroenke

**Review by mossmaurice — APPROVED** [review]

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp [hunk 23]
```diff
@@ -314,10 +314,84 @@ TEST_F(PortManager_test, doDiscovery_rightOrdering)
...
+}
+
+
 TEST_F(PortManager_test, AcquiringOneMoreThanMaximumNumberOfPublishersFails)
 {
     iox::ProcessName_t processName = "test1";
-    PublisherOptions publisherOptions{1, "run1"};
+    PublisherOptions publisherOptions{1U, "run1"};
 
     for (unsigned int i = 0; i < iox::MAX_PUBLISHERS; i++)
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp:396]: "The big U is your..." :D

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

File: iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp (hunk 23 above)
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp:396]: @dkroenke Longing for Axivion to find these with a CI check :smile:

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_posh/source/runtime/posh_runtime.cpp [hunk 24]
```diff
@@ -261,6 +262,12 @@ PoshRuntime::getMiddlewareSubscriber(const capro::ServiceDescription& service,
                   << ", limiting from " << subscriberOptions.queueCapacity << " to " << MAX_QUEUE_CAPACITY;
         options.queueCapacity = MAX_QUEUE_CAPACITY;
     }
+    else if (0U == options.queueCapacity)
+    {
+        LogWarn() << "Requested queue capacity of 0 doesn't make sense as no data would be received,"
+                  << " the capacyity is set to 1";
```
Comment (mossmaurice) [inline iceoryx_posh/source/runtime/posh_runtime.cpp:268]: Nitpick: typo

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]

**Review by mossmaurice — APPROVED** [review]

File: iceoryx_examples/icedelivery_in_c/README.md [hunk 25]
```diff
@@ -56,12 +56,7 @@ Let's take a look at the `receiving` function which comes with the
     iox_sub_t subscriber = iox_sub_init(&subscriberStorage, "Radar", "FrontLeft", "Object", &options);
     ```
 
-  3. We subscribe to the service.
-     ```c
-     iox_sub_subscribe(subscriber);
-     ```
-
-  4. In this loop we receive samples as long the `killswitch` is not
+  3. In this loop we receive samples as long the `killswitch` is not
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_examples/icedelivery_in_c/README.md:59]: Please update the steps (l. 23-29).

File: iceoryx_examples/icedelivery_in_c/README.md [hunk 26]
```diff
@@ -126,12 +116,8 @@ Let's take a look at the `sending` function which comes with the
     iox_pub_storage_t publisherStorage;
     iox_pub_t publisher = iox_pub_init(&publisherStorage, "Radar", "FrontLeft", "Object", &options);
     ```
- 3. We offer our service to the world.
-    ```c
-    iox_pub_offer(publisher);
-    ```
 
- 4. Till an external signal sets `killswitch` to `true` we will send an
+ 3. Till an external signal sets `killswitch` to `true` we will send an
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_examples/icedelivery_in_c/README.md:120]: Please update the steps in l. 94 - 100.

**Review by FerdinandSpitzschnueffler — CHANGES_REQUESTED** [review]
Please update the readme of icedelivery_in_c

**Comment by budrus** [comment]
> Please update the readme of icedelivery_in_c

Ahh, Sorry I just saw it after the merge :-(
