### PR TITLE
iox-#1425 create convenience macro for newtype

### LINKED ISSUE #1425: Create convenience macro for NewType
## Brief feature description

The `NewType` class helps to avoid the [Primitive Obsession](https://refactoring.guru/smells/primitive-obsession) and saves you from crashing your [mars orbiter](https://en.wikipedia.org/wiki/Mars_Climate_Orbiter) into a planet. But there is some boilerplate needed which leads to use primitives instead of a new type. A convenience macro like

```cpp
IOX_NEW_TYPE(Foo, uint64_t, iox::cxx::newtype::ConstructByValueCopy)
IOX_NEW_TYPE(Bar, uint64_t, iox::cxx::newtype::ConstructByValueCopy)
```

could boost the usage of new types.

## Detailed information

The macro would basically look like this.

```cpp
#define IOX_NEW_TYPE(TypeName, Type, ...)                            \
    struct TypeName : public iox::cxx::NewType<Type, __VA_ARGS__>    \
    {                                                                \
        using ThisType::ThisType;                                    \
        using ThisType::operator=;                                   \
                                                                     \
        TypeName() noexcept = default;                               \
        TypeName(const TypeName&) noexcept = default;                \
        TypeName(TypeName&&) noexcept = default;                     \
        TypeName& operator=(const TypeName&) noexcept = default;     \
        TypeName& operator=(TypeName&&) noexcept = default;          \
    };
```

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This PR adds a convenience macro for `NewType` to reduce the amount of boilerplate code for basic new types.

```cpp
// before
struct Foo : public iox::cxx::NewType<uint64_t, iox::cxx::newtype::ConstructByValueCopy>
{
    using ThisType::ThisType;
    // more boilerplate code for depending on policies, e.g. move/copy assignment, comparison, etc.
};

// after
IOX_NEW_TYPE(Foo, uint64_t, iox::cxx::newtype::ConstructByValueCopy)
```

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1425

### CODE REVIEW

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp [hunk 1]
```diff
@@ -119,6 +122,40 @@ class NewType : public Policies<NewType<T, Policies...>>...
...
+    {                                                                                                                  \
+        using ThisType::ThisType;                                                                                      \
+        using ThisType::operator=;                                                                                     \
+                                                                                                                       \
+        TypeName() noexcept = default;                                                                                 \
+        TypeName(const TypeName&) noexcept = default;                                                                  \
+        TypeName(TypeName&&) noexcept = default;                                                                       \
+        TypeName& operator=(const TypeName&) noexcept = default;                                                       \
+        TypeName& operator=(TypeName&&) noexcept = default;                                                            \
+    };
```
Comment (elBoberido) [inline iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp:157]: The big question, semicolon or not. Without the semicolon the macro usage would look like this
```cpp
IOX_NEW_TYPE(Foo, uint64_t, newtype::ConstructByValueCopy, newtype::Comparable);
```
It is more familiar to the manual creation via the struct and the error message is ` error: expected ';' after struct`, which is also clear. Therefore I would remove the semicolon from the macro. What do you think

**Review by elfenpiff — COMMENTED** [review]
Looks good as soon as the semicolon is removed I would approve it

**Review by mossmaurice — APPROVED** [review]
Thanks!

**Review by elfenpiff — APPROVED** [review]
