### PR TITLE
iox-#570 fixed variant move ctor and assignment behavior

### LINKED ISSUE #570: `cxx::variant` move assignment invalidates sources
## Required information

**Observed result or behaviour:**
The move assignment operator of the `cxx::variant` invalidates the source which is incorrect C++ idiomatic. The variant has to leave the contained object in a destructable state.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [x] Merge

## References

- Closes #570

### CODE REVIEW

**Review by elBoberido — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]

File: iceoryx_utils/test/moduletests/test_cxx_variant.cpp [hunk 1]
```diff
@@ -291,7 +295,7 @@ TEST_F(variant_Test, MoveCTorWithValue)
     iox::cxx::variant<int, char> ignatz(std::move(schlomo));
     ASSERT_THAT(ignatz.get<int>(), Ne(nullptr));
     EXPECT_THAT(*ignatz.get<int>(), Eq(123));
-    EXPECT_THAT(schlomo.index(), Eq(iox::cxx::INVALID_VARIANT_INDEX));
+    EXPECT_THAT(schlomo.index(), Eq(0));
```
Comment (dkroenke) [inline iceoryx_utils/test/moduletests/test_cxx_variant.cpp:298]: size_t is unsigned

**Review by dkroenke — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]

**Review by mossmaurice — APPROVED** [review]
