### PR TITLE
iox-#1613 Remove EXPECT_DEATH

### LINKED ISSUE #898: MacOS tests that use EXPECT_DEATH stuck
## Required information

Jobs that failed
https://github.com/eclipse-iceoryx/iceoryx/runs/3250456083
https://github.com/eclipse-iceoryx/iceoryx/runs/3249546327
https://github.com/eclipse-iceoryx/iceoryx/runs/3242681619

**Operating system:**
macos-10.14 (and macos-latest) (github actions machines)

**Compiler version:**
Apple clang version 12.0.0 (clang-1200.0.32.29) Target: x86_64-apple-darwin19.6.0 Thread model: posix InstalledDir: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Observed result or behaviour:**
On MacOS seems we hit deadlock or some other glitches (e.g. described [here](https://github.com/google/googletest/blob/master/docs/advanced.md#caveats)) in tests that use EXPECT_DEATH

e.g. jobs above stuck on
* RouDiEnvironment_test.StartingRouDiTwiceLeadsToError (2x)
* BindingC_Runtime_test.RuntimeNameIsNullptr

**Expected result or behaviour:**
What do you expect to happen?

No stuck tests

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.

Rerun CI at least 3-5 times, if macos job is running 30+ minutes it means it stuck (6h timeout from github)

## Related

 #1422

### LINKED ISSUE #1613: Remove `EXPECT_DEATH`
## Required information

In our cases using `EXPECT_DEATH` come often with undefined behavior which is unacceptable for certified tests. Possible approaches are:

* Create thread and call `pthread_exit` inside the error handler, would require the implementation of that feature in #1365 
* Throw an exception in the error handler, would require heavy refactoring and feature #1392 
* Another nifty idea.

## ToDo
- [x] (high prio) Define an alternative technique to `EXPECT_DEATH` and document it in the iceoryx testing document
- [x] (high prio) Remove all occurrences of `EXPECT_DEATH` in cxx tests
- [x] (medium prio) Remove all occurrences of `EXPECT_DEATH` in remaining hoofs
- [ ] (low prio) Remove all occurrences of `EXPECT_DEATH` in the remaining iceoryx repo
  - Using `EXPECT_FATAL_FAILURE` in combination with the `RouDiEnvironment` results in triggering the leak sanitizer
  - The same is the case when the SUT allocate in the call which leads to the fatal failure, e.g. the ctor of `FileReader`

Can be split up in further issues when required.

Extracted from: #1196

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This PR replaces the last remaining `EXPECT_DEATH` with `IOX_EXPECT_FATAL_FAILURE` where feasible. There are a few remaining occurrences which cannot be replaced, e.g. tests for `PoshRuntime` which has a singleton. These tests now use `GTEST_FLAG(death_test_style) = "threadsafe";` to prevent stucking threads.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1613
- Closes #898

### CODE REVIEW

File: iceoryx_posh/source/mepoo/mem_pool.cpp [hunk 1]
```diff
@@ -62,7 +62,8 @@ MemPool::MemPool(const greater_or_equal<uint32_t, CHUNK_MEMORY_ALIGNMENT> chunkS
     else
     {
         IOX_LOG(FATAL) << "Chunk size must be multiple of '" << CHUNK_MEMORY_ALIGNMENT << "'! Requested size is "
-                       << chunkSize << " for " << numberOfChunks << " chunks!";
+                       << static_cast<uint32_t>(chunkSize) << " for " << static_cast<uint32_t>(numberOfChunks)
```
Comment (elBoberido) [inline iceoryx_posh/source/mepoo/mem_pool.cpp:65]: I just discovered that the logger currently does not invoke implicit conversion of `greater_or_equal<T>` to `T` correctly due to SFINEA on `LogStream& operator<<(const T value)` for arithmetic typs. `LogStream& operator<<(const bool value)` does not have SFINEA so `greater_or_equal<uint32>` gets implicitly converted into bool. I guess we should replace the SFINEA implementation for arithmetic types with explicit methods.

Comment (FerdinandSpitzschnueffler) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:65]: @elBoberido Can you please open an issue for this?

**Review by mossmaurice — APPROVED** [review]
LGTM, thanks for the PR! If you create the follow-up issue for the SFINAE thingy we can merge this.

**Comment by elBoberido** [comment]
@mossmaurice I added a task to #1755

File: iceoryx_posh/source/mepoo/mem_pool.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_posh/source/mepoo/mem_pool.cpp:65]: @elfenpiff I added a task to #1755

**Review by elfenpiff — APPROVED** [review]
