### PR TITLE
iox-#1382 Fix build on FreeBSD

### LINKED ISSUE #1382: FreeBSD build is broken
## Required information

**Operating system:**
FreeBSD

**Compiler version:**
Clang 11

**Observed result or behaviour:**
The compilation of the tests fails with
```
test_concurrent_fifo.cpp:66:30: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'const int' [-Werror,-Wshorten-64-to-32]
```

**Expected result or behaviour:**
Tests should compile

**Conditions where it occurred / Performed steps:**
Build iceoryx on FreeBSD on the CI

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This PR fixes the FreeBSD
- build the branch from the PR instead of master
- set warnings for tests depending on compiler instead of the platform
- fix conversion warnings in FIFO test

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1382

### CODE REVIEW

File: iceoryx_hoofs/test/moduletests/test_concurrent_fifo.cpp [hunk 1]
```diff
@@ -19,14 +19,15 @@
 
 #include <gmock/gmock.h>
 #include <gtest/gtest.h>
-#include <stdlib.h>
+
```
Comment (mossmaurice) [inline iceoryx_hoofs/test/moduletests/test_concurrent_fifo.cpp:22]: Could you please adapt the year in the copyright header?

**Review by mossmaurice — COMMENTED** [review]
LGTM, thanks for the PR!

**Review by dkroenke — APPROVED** [review]

**Review by mossmaurice — APPROVED** [review]
