### PR TITLE
Iox #190 fixed point types for duration internal representation

### LINKED ISSUE #190: nanoseconds in units::Duration are truncated
## Required information

**Operating system:**
on aarch64 targets like Raspberry PI

**Compiler version:**
E.g. GCC 9.3.0

**Observed result or behaviour:**
The Posix Timer is getting double values on the API which are then converted into int64_t internally. This conversion leads to a loss of data because the compiler will truncate the value. This can lead to abnormal behaviour when using small numbers like 1 nanoseconds.

**Expected result or behaviour:**
Remove the double literals from the posix timer API and expect only integer als time values. Then we avoid this constraint and have a clean calculation.

**Conditions where it occurred / Performed steps:**
Try to start a timer with 1 nanosecond waiting time. It will no execute because the time is internally set to zero. This disarms the timer and it is not proceeding.

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer

This replaces the `long double` internal representation of `units::Duration` with `uint64_t` for seconds and `uint32_t` for nanoseconds.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [ ] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- Closes #190

### CODE REVIEW

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 1]
```diff
@@ -37,127 +37,206 @@ class Duration;
...
+    static constexpr Duration milliseconds(const T value);
+
+    /// @brief Constructs a new Duration object from seconds
+    /// @tparam T is an integer type for the value
+    /// @param[in] value as seconds
+    /// @return a new Duration object
+    /// @attention since negative durations are not allowed, the duration will be capped to 0
     template <typename T>
-    static constexpr Duration seconds(const T seconds);
+    static constexpr Duration seconds(const T value);
```
Comment (elBoberido) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:108]: We have also a `seconds` getter method. I would like to rename the creation methods in a follow up PR and add a `from` prefix, e.g. `fromSeconds` and make the getter methods all lower case.

It would be different from `chrono`, but the alternative would be to have something like a `units_duration_cast`, which I wouldn't like that much all over the code base.

Any objections?

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 2]
```diff
@@ -186,49 +265,59 @@ class Duration
...
+    multiplyNanoseconds(const uint32_t nanoseconds,
+                        const std::enable_if_t<!std::is_floating_point<T>::value, T>& right) const;
+    template <typename T>
+    inline constexpr Duration
+    multiplyNanoseconds(const uint32_t nanoseconds,
+                        const std::enable_if_t<std::is_floating_point<T>::value, T>& right) const;
+
+  private:
+    uint64_t m_seconds{0};
+    uint32_t m_nanoseconds{0};
```
Comment (bishibashiB) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: Next to the `double` implementation I found the inability to calculate _negative_ durations (like in received expected vs. actual).
In design you will have chosen for `unsigned` for reasons *)... But it came unexpected to me as there is no such limitation e.g. with `chrono`. (*No negative offsets for timers?)
Did I over-read the documentation explaining it (kindfully point me there, thanks~)?

Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: This was just a straight port to integer types without changing the previous behavior. @elfenpiff once told me why he did it this way, but I forgot it in the meantime. Maybe he can enlighten you.
Regarding the documentation, that's unfortunately missing. This is something we have to improve the next months.

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 3]
```diff
@@ -18,218 +18,686 @@
...
+
+TEST(Duration_test, CompareTwoEqualDurations)
 {
     auto time1 = 200_us;
-    auto time2 = 200.0_us;
-    EXPECT_EQ(time1.seconds<double>(), time2.seconds<double>());
+    auto time2 = 200000_ns;
+    EXPECT_TRUE(time1 == time2);
+    EXPECT_TRUE(time2 == time1);
+}
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:502]: Please add also a test where the equality operator returns false. A paranoid part of me fears that someone in the future might change the behavior of the operator so that it always returns true.

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 4]
```diff
@@ -18,218 +18,686 @@
...
 
-    auto time3 = 0.21_ms;
-    EXPECT_LT(time1, time3);
-    EXPECT_GT(time3, time2);
+TEST(Duration_test, CompareTwoNonEqualDurations)
+{
+    auto time1 = 1_s + 200_us;
+    auto time2 = 1_ns;
+    EXPECT_TRUE(time1 != time2);
+    EXPECT_TRUE(time2 != time1);
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:509]: Please add also a test where the inequality operator returns false.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 5]
```diff
@@ -21,47 +21,102 @@ namespace iox
...
 template <typename T>
-constexpr Duration Duration::nanoseconds(const T ns)
+constexpr Duration Duration::nanoseconds(const T value)
 {
-    return operator"" _ns(ns);
+    static_assert(std::numeric_limits<T>::is_integer, "only integer are supported");
+
+    if (value < 0)
+    {
+        return Duration{0U, 0U};
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:30]: I think a warning that the duration is set to 0 would be good. Same for the other c'tors.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 6]
```diff
@@ -186,49 +265,59 @@ class Duration
...
+    inline constexpr Duration
+    multiplyNanoseconds(const uint32_t nanoseconds,
+                        const std::enable_if_t<!std::is_floating_point<T>::value, T>& right) const;
+    template <typename T>
+    inline constexpr Duration
+    multiplyNanoseconds(const uint32_t nanoseconds,
+                        const std::enable_if_t<std::is_floating_point<T>::value, T>& right) const;
+
+  private:
+    uint64_t m_seconds{0};
```
Comment (dkroenke) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:308]: Are U correctly initialized? ;-)

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 7]
```diff
@@ -21,47 +21,102 @@ namespace iox
...
+    return operator"" _d(value);
+}
+
+
+inline constexpr Duration::Duration(const uint64_t seconds, const uint32_t nanoseconds)
+    : m_seconds(seconds)
+    , m_nanoseconds(nanoseconds)
 {
-    return operator"" _d(days);
+    if (nanoseconds >= 1000000000U)
```
Comment (dkroenke) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:106]: `1000000000U` is used quite often as conversion factor in the code, maybe it make sense to make a constexpr of it?
Proposal: `CONV_NANOSECONDS`

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 8]
```diff
@@ -37,127 +37,206 @@ class Duration;
...
 
     /// @brief Construct a Duration object from itimerspec
+    /// @param[in] value as itimespec
+    /// @note only it_interval from the itimerspec is used
     constexpr explicit Duration(const struct itimerspec& value);
 
     /// @brief Construct a Duration object from std::chrono::milliseconds
+    /// @param[in] value as milliseconds
+    /// @attention since negative durations are not allowed, the duration will be capped to 0
     constexpr explicit Duration(const std::chrono::milliseconds& value);
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:159]: In a follow up pull request we should templatize this somehow so that all `std::chrono::` timetypes are allowed.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 2 above)
Comment (elfenpiff) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: Duration is a measurement unit for the distance of two time points and it does not make sense to have a negative distance. It is like the distance of two points in space, negative distance is weird.

I think `std::chrono::duration` behaves identical when you call for instance `count`.

But maybe we have to rethink `duration`. For me `units::time` would make more sense somehow with a `units::duration` specialization. It would be very helpful for methods like this:
```cpp
mySemaphore.sleep_until(units::time pointInTIme);
mySemaphore.sleep_for(units::duration duration);
```

@elBoberido what do you think, would this be something for a follow up PR?

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 9]
```diff
@@ -21,47 +21,102 @@ namespace iox
...
+constexpr Duration Duration::nanoseconds(const T value)
 {
-    return operator"" _ns(ns);
+    static_assert(std::numeric_limits<T>::is_integer, "only integer are supported");
+
+    if (value < 0)
+    {
+        return Duration{0U, 0U};
+    }
+    return operator"" _ns(value);
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:32]: Too much code,
```cpp
return (value < 0 ) ? Duration(0U, 0U) : operator""_ns(value);
```

Would spare us of the four additional lines. Could you please change that for this and all the other methods.

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 10]
```diff
@@ -18,218 +18,686 @@
...
+    constexpr uint64_t SECONDS{13U};
+    constexpr uint64_t NANOSECONDS{GIGA};
+    constexpr uint64_t EXPECTED_DURATION_IN_NANOSECONDS{(SECONDS + 1U) * GIGA};
+
+    auto sut = Duration{SECONDS, NANOSECONDS};
+
+    EXPECT_THAT(sut.nanoSeconds<uint64_t>(), Eq(EXPECTED_DURATION_IN_NANOSECONDS));
+}
+
+TEST(Duration_test, ConstructDurationWithMoreNanosecondsThanOneSecond)
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:49]: I would add a test where you also construct  a duration object with 3 billion + x nanoseconds which should you then give you 3 seconds.
Additionally, when you think of:
- zero
- one
- many
- corner cases
- limits

You maybe should also construct a duration object with zero nanoseconds, both seconds and nanoseconds are zero, nanoseconds is `std::numeric_limits<uint32_t>::max` and where seconds and nanoseconds are both `std::numeric_limits<T>::max`

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 11]
```diff
@@ -71,211 +126,298 @@ inline constexpr Duration::Duration(const struct itimerspec& value)
...
+    if (right < static_cast<T>(0))
+    {
+        return Duration{0U, 0U};
+    }
+
+    auto result = m_seconds / right;
+    double seconds{0.0};
+    double secondsFraction = modf(result, &seconds);
+    auto nanoseconds =
+        static_cast<uint64_t>(secondsFraction * 1000000000U) + static_cast<uint64_t>(m_nanoseconds / right);
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:361]: I am disappointed, so disappointed!!! ;)

What happens when `right == 0`??

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 12]
```diff
@@ -18,218 +18,686 @@
...
+    EXPECT_THAT(2.95 * time, Eq(17_s + 110_ms));
 
-    Duration result(value);
-    EXPECT_EQ(result.microSeconds<uint64_t>(), 42 + 1000000 * 1337);
+    EXPECT_THAT(time * -1, Eq(0_s));
+    EXPECT_THAT(time * -1.0, Eq(0_s));
 }
 
-TEST(Duration_test, isZeroWhenConstructedFromNegativeChronoMilliSeconds)
+TEST(Duration_test, DivideDuration)
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:691]: We should test:
- division by zero!
- division with negative number
- division with 0.0000000001f and a large duration type so that you run into an overflow

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 13]
```diff
@@ -18,218 +18,686 @@
...
     auto time4 = 10_s;
 
-    result = result / time4;
-    EXPECT_NEAR(result.seconds<double>(), 8.666666666666666, tenTimesEpsilon);
+    result = result - time4;
+    EXPECT_EQ(result.milliSeconds<uint64_t>(), 0U);
 }
 
-TEST(Duration_test, constructFromTimespec)
+TEST(Duration_test, MultiplyDuration)
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:675]: We should test:
- multiplication with negative number
- multiplication with 1000000000 and a large duration type so that you run into an overflow

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 14]
```diff
@@ -18,218 +18,686 @@
...
+    EXPECT_EQ(result.milliSeconds<uint64_t>(), 5400U);
 
-    result = result * time4;
-    EXPECT_NEAR(result.seconds<double>(), 3.12, tenTimesEpsilon);
+    result = result + time3;
+    EXPECT_EQ(result.microSeconds<uint64_t>(), 6100000U);
 }
 
-TEST(Duration_test, divideDuration)
+TEST(Duration_test, SubtractDuration)
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:655]: Overflow test?

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 15]
```diff
@@ -18,218 +18,686 @@
...
+    EXPECT_FALSE(time3 >= time2);
+    EXPECT_FALSE(time4 >= time3);
 }
 
-TEST(Duration_test, multiplyDuration)
+// END COMPARISON TESTS
+
+// BEGIN ARITHMETIC TESTS
+
+TEST(Duration_test, AddDuration)
```
Comment (elfenpiff) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:640]: Overflow test?

**Review by elfenpiff — CHANGES_REQUESTED** [review]
Please add the mentioned test cases.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 6 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:308]: yes, it's initialized with 64 bits set to 0 😉

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 2 above)
Comment (mossmaurice) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: Seems like Rust's also [not allowing](https://docs.rs/chrono/0.4.6/chrono/struct.Duration.html) a negative duration:

> As standard library implementation is limited to non-negative values.

I'm still unsure on why `std::chrono::duration` can be negative. We might ping @ [HowardHinnant](https://github.com/HowardHinnant) the creator of `chrono` :-)

**Review by mossmaurice — COMMENTED** [review]
Thanks for this pull request and the increased test coverage. I love seeing technical debt being addressed :rocket: 

However, when starting to think about it, I'm wondering if we're on the right path here.

Why are we reinventing the wheel here? Tried to summarize:

| | :heavy_plus_sign: | :heavy_minus_sign: |
|----|----|----|
|`units::Duration`| Conversion operator needed for `timeval` and `timespec` | Many additional LoC for test |
| | | More certification effort |
| `chrono::duration` | Lower complexity | No user-friendly conversion  |
| | Less certification effort | | 
| | Keeps it simple and stupid| | 

So my conclusion is, why not having the best of both world by wrapping `chrono::duration` and maybe later `chrono::time_point` as wished by @elfenpiff?

**Comment by elfenpiff** [comment]
> Thanks for this pull request and the increased test coverage. I love seeing technical debt being addressed 
> 
> However, when starting to think about it, I'm wondering if we're on the right path here.
> 
> Why are we reinventing the wheel here? Tried to summarize:
> 
> 	
> `units::Duration`	Conversion operator for `timeval` and `timespec`	Many additional LoC for test
> More certification effort
> `chrono::duration`	Lower complexity	No user-friendly conversion
> Less certification effort	
> Keeps it simple and stupid	
> So my conclusion is, why not having the best of both world by wrapping `chrono::duration` and maybe later `chrono::time_point` as wished by @elfenpiff?

I would also prefer `std::chrono`. For the conversion to `timeval` and `timespec` we could write some custom conversion function but before we do that we have to evaluate the following points:
- Exceptions in `std::chrono`, where, why and how?
- Is heap used in `std::chrono`?
- The c++ `std::chrono` library is huge and we only require a small portion of it - is it possible to certify this subset or do we have to pay for the whole thing.

But I think that switching to `std::chrono` is something for the far future and at the moment I would stick to our approach.

**Comment by mossmaurice** [comment]
> [snip]
> ...before we do that we have to evaluate the following points:
> 
>     * Exceptions in `std::chrono`, where, why and how?
> 
>     * Is heap used in `std::chrono`?
> 
>     * The c++ `std::chrono` library is huge and we only require a small portion of it - is it possible to certify this subset or do we have to pay for the whole thing.

Good point and important questions!

Maybe @MichaelOrlov or @sumanth-nirmal already can across this topic and can answer some of the questions.

@elBoberido Shall we maybe start with a design document, which briefly describes our requirements and the path that we wanna take, before merging this PR?

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 2 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: @elfenpiff I like the idea. The difference of two `time` objects would be a `duration`. It would need to be truncated to 0 for negative values. Maybe that's also the reason why `chrono::duration` supports negative values.

I think we should follow @mossmaurice suggestion and first fully explore if chrono is an option before we add more features.

@mossmaurice just for completeness. The link you added was to the `chrono` crate and that does allow negative durations. The standard library has `std::time::Duration` which does not allow negative durations, though.

Comment (mossmaurice) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: @elBoberido Ok, thanks for clarifying that. My Rust knowledge is still quite rusty 🤡

Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:309]: @mossmaurice time to change that and make Ferris the 🦀 happy 😁

**Comment by elBoberido** [comment]
> @elBoberido Shall we maybe start with a design document, which briefly describes our requirements and the path that we wanna take, before merging this PR?

@mossmaurice I think a design document is a good idea but I wouldn't wait to merge this PR. It doesn't add new features but is just a refactoring and improves the current situation. Also, regardless if we choose `chrono` as internal representation, I would still keep the current `Duration` class as wrapper. I currently also don't have time to write this design document since I have other things to finish first. So if you don't mind I would continue with this PR and do the design document before new features are added.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 6 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp]: btw, what do you think of
```c++
#define 0 0U
```
or
```c++
constexpr unsigned U{0U};
```

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 9 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl]: there is now a print to inform the user of the clamping, therefore your proposal cannot be used anymore

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 11 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl]: Which division by zero? There is no `operator/` for `Duration` 😉

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp (hunk 12 above)
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_unit_duration.cpp]: can't do, there is no `operator/` for `Duration` 😁

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 16]
```diff
@@ -37,200 +37,299 @@ class Duration;
...
+    /// @return a new Duration object
+    /// @attention since negative durations are not allowed, the duration will be capped to 0
+    constexpr Duration operator-(const Duration& right) const noexcept;
+
+    /// @brief creates Duration object by multiplication
+    /// @tparam T is an arithmetic type for the multiplicator
+    /// @param[in] right is the multiplicator
+    /// @return a new Duration object
+    /// @attention since negative durations are not allowed, the duration will be capped to 0
+    /// @note there is no explicit division operator, if you want a fraction of of a Duration, either multiply with the
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:226]: instead of skipping letters I'm now duplication words :D

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 17]
```diff
@@ -37,200 +37,299 @@ class Duration;
 
 inline namespace duration_literals
 {
-/// @brief constructs a new Duration object in nanoseconds
-constexpr Duration operator"" _ns(long double);
+/// @brief Constructs a new Duration object from nanoseconds
+constexpr Duration operator"" _ns(unsigned long long int) noexcept; // PRQA S 48
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:41]: only `long double` and `unsigned long long int` are allowed for user defined literals

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 18]
```diff
@@ -37,200 +37,299 @@ class Duration;
...
 class Duration
 {
   public:
+    // BEGIN CREATION FROM STATIC FUNCTIONS
+
+    /// @brief Constructs a new Duration object from nanoseconds
+    /// @tparam T is an integer type for the value
+    /// @param[in] value as nanoseconds
+    /// @return a new Duration object
+    /// @attention since negative durations are not allowed, the duration will be capped to 0
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:82]: How about "clamped to"?

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 19]
```diff
@@ -37,200 +37,299 @@ class Duration;
...
 
   private:
-    /// @brief constructor needs to be private to ensure a unit safe usage of duration
-    constexpr explicit Duration(const long double durationInSeconds);
-    long double durationInSeconds{0.0};
-};
+    template <typename T>
+    inline constexpr Duration
+    multiplySeconds(const uint64_t seconds,
+                    const std::enable_if_t<!std::is_floating_point<T>::value, T>& right) const noexcept;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:290]: there is already a check for arithmetic types in `operator*(const T& lhs, const Duration& rhs)`. These are some helper functions for integer and floating point multiplicators

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 20]
```diff
@@ -37,200 +37,299 @@ class Duration;
...
+    static constexpr uint32_t HOURS_PER_DAY{24U};
+
+    static constexpr uint32_t MILLISECS_PER_SEC{1000U};
+    static constexpr uint32_t MICROSECS_PER_SEC{MILLISECS_PER_SEC * 1000U};
+
+    static constexpr uint32_t NANOSECS_PER_MICROSEC{1000U};
+    static constexpr uint32_t NANOSECS_PER_MILLISEC{NANOSECS_PER_MICROSEC * 1000U};
+    static constexpr uint32_t NANOSECS_PER_SEC{NANOSECS_PER_MILLISEC * 1000U};
+
+    static_assert(NANOSECS_PER_SEC == 1000U * MICROSECS_PER_SEC, "Mismatch in calculation for conversion constants!");
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:315]: yes, it's just my inner chicken

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 21]
```diff
@@ -21,261 +21,410 @@ namespace iox
...
+    constexpr uint64_t MAX_SECONDS_BEFORE_OVERFLOW{std::numeric_limits<T>::max() / NANOSECS_PER_SEC};
+    constexpr uint64_t MAX_NANOSECONDS_BEFORE_OVERFLOW{std::numeric_limits<T>::max() % NANOSECS_PER_SEC};
+    constexpr Duration MAX_DURATION_BEFORE_OVERFLOW{MAX_SECONDS_BEFORE_OVERFLOW, MAX_NANOSECONDS_BEFORE_OVERFLOW};
+
+    if (*this > MAX_DURATION_BEFORE_OVERFLOW)
+    {
+        std::clog << __PRETTY_FUNCTION__ << ": Result of conversion would overflow, clamping to max value!"
+                  << std::endl;
+        return std::numeric_limits<T>::max();
+    }
```
Comment (elBoberido) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:176]: @elfenpiff this is the price we are paying for the overflow detection. I think it's not too bad and could be disabled for release builds if necessary

**Comment by elBoberido** [comment]
@mossmaurice a `chrono::duration` as member deletes the defaulted noexcept ctor
```c++
#include <chrono>
#include <iostream>
#include <type_traits>

struct Foo {
    Foo() noexcept = default;

    Foo(const Foo&) noexcept = default;
    Foo(Foo&&) noexcept = default;

    std::chrono::duration<uint64_t, std::nano> duration{0U};
};
int main() {
    std::cout << "Is nothrow default constructible: " << std::is_nothrow_default_constructible<Foo>::value << std::endl;
    std::cout << "Is nothrow move constructible   : " << std::is_nothrow_move_constructible<Foo>::value << std::endl;
}
```
output
```
Is nothrow default constructible: 0
Is nothrow move constructible   : 1
```

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (dkroenke) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:83]: will be fixed to 0?

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 2 above)
Comment (bishibashiB) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp]: Thanks all for giving inputs on this! Will follow the discussion interested~!

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:83]: other possibilities would be
- bounded to 0
- limited to 0
- narrowed to 0

Maybe we need the help of a native speaker @ithier

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 22]
```diff
@@ -37,200 +38,298 @@ class Duration;
...
+    constexpr bool operator>=(const Duration& rhs) const noexcept;
+
+    // END COMPARISON
+
+    // BEGIN ARITHMETIC
+
+    /// @brief Creates Duration object by addition
+    /// @param[in] rhs is the second summand
+    /// @return a new Duration object
+    constexpr Duration operator+(const Duration& rhs) const noexcept;
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:214]: Oh ... what about `operator+=`, `operator-=` and `operator*=`?
These are my most favorite operators :D

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 23]
```diff
@@ -21,261 +21,490 @@ namespace iox
 namespace units
 {
 template <typename T>
-constexpr Duration Duration::nanoseconds(const T ns)
+constexpr Duration Duration::nanoseconds(const T value) noexcept
 {
-    return operator"" _ns(ns);
+    static_assert(std::numeric_limits<T>::is_integer, "only integer are supported");
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:26]: Typo: integers

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 24]
```diff
@@ -21,261 +21,490 @@ namespace iox
...
+
+    if (value < 0)
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:28]: Since this code is always the same I would create a free function to handle this error handling, otherwise we have a lot of code duplications.

What do you think of the following approach:
```cpp
template<typename T, typename OnSuccessFactory>
Duration createDurationFromValue(const T value, const OnSuccessFactory) {
    static_assert(std::numeric_limits<T>::is_integer, "only integer are supported");
    if (value < 0)
    {
        std::clog << __PRETTY_FUNCTION__ << ": Clampling negative value '" << value << "' to zero!" << std::endl;
        return Duration{0U, 0U};
    }
    return OnSuccessFactory(static_cast<unsigned long long int>(value));
}

template <typename T>
constexpr Duration Duration::nanoseconds(const T value) noexcept {
    return createDurationFromValue(value, [this](const unsigned long long int value){ return operator"" _ns(value)' });
}

```

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 25]
```diff
@@ -21,261 +21,490 @@ namespace iox
...
-template <typename T>
-inline constexpr T Duration::nanoSeconds() const
+inline constexpr uint64_t Duration::nanoSeconds() const noexcept
 {
-    return static_cast<T>(durationInSeconds * 1000000000.0);
+    constexpr uint64_t MAX_SECONDS_BEFORE_OVERFLOW{std::numeric_limits<uint64_t>::max() / NANOSECS_PER_SEC};
+    constexpr uint64_t MAX_NANOSECONDS_BEFORE_OVERFLOW{std::numeric_limits<uint64_t>::max() % NANOSECS_PER_SEC};
+    constexpr Duration MAX_DURATION_BEFORE_OVERFLOW{MAX_SECONDS_BEFORE_OVERFLOW, MAX_NANOSECONDS_BEFORE_OVERFLOW};
+
+    if (*this > MAX_DURATION_BEFORE_OVERFLOW)
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:168]: Here I would maybe also write an internal free function to avoid code duplication.

```cpp
template<typename OnSuccessFunc>
uint64_t performConversion(const Duration & currentDuration, const Duration & maxDuration, const OnSuccessFunc & func) {
  if ( currentDuration > maxDuration ) {
        std::clog << __PRETTY_FUNCTION__ << ": Result of conversion would overflow, clamping to max value!"
                  << std::endl;
        return std::numeric_limits<uint64_t>::max();
  } 
  return OnSuccessFunc();
}

inline constexpr uint64_t Duration::nanoSeconds() const noexcept {
   // ...
   performConversion(*this, 
                      {MAX_SECONDS_BEFORE_OVERFLOW, MAX_NANOSECONDS_BEFORE_OVERFLOW}, 
                      [&]{ return m_seconds * NANOSECS_PER_SEC + m_nanoseconds; } );
}

```

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 26]
```diff
@@ -37,200 +38,298 @@ class Duration;
...
+    static constexpr Duration days(const T value) noexcept;
+
+    // END CREATION FROM STATIC FUNCTIONS
+
+    // BEGIN CONSTRUCTORS AND ASSIGNMENT
+
+    /// @brief Constructs a Duration from seconds and nanoseconds
+    /// @param[in] seconds portion of the duration
+    /// @param[in] nanoseconds portion of the duration
+    constexpr Duration(const uint64_t seconds, const uint32_t nanoseconds) noexcept;
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:142]: I would make this ctor private since it somehow defeats the purpose of the readability.

```cpp
// good
auto blubb = Duration::seconds(123);
// bad
auto bla = Duration(123, 123); // what is it?
```

If this is really needed I would recommend using the conversion ctor which takes `timeval` or `itimerspec`.

**Review by elfenpiff — CHANGES_REQUESTED** [review]

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 22 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:209]: That's a new feature, this PR just replaces the internal double representation with a fixed point one. Feel free to create a PR with your most favorite operator :P

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 24 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:28]: use a similar approach without the lambda

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 25 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:175]: In this case I'd rather live with minimal code duplication

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (MatthiasKillat) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:83]: I do not really care too much about the wording, it just caught my attention while reading. I think clamp is popular in computer graphics but maybe otherwise unheard of. Do whatever.

File: iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp [hunk 27]
```diff
@@ -14,22 +15,25 @@
 
 #include "test.hpp"
 
-#define private public
-#define protected public
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp:18]: only 4 of the old sins left :)

Comment (elfenpiff) [reply iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp:18]: One of the hereditary sins of iceoryx...

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp [hunk 28]
```diff
@@ -37,200 +38,311 @@ class Duration;
...
-    friend constexpr Duration duration_literals::operator"" _d(long double);
-    friend constexpr Duration duration_literals::operator"" _d(unsigned long long int); // PRQA S 48
+    template <typename T>
+    constexpr Duration multiplyWith(const std::enable_if_t<std::is_floating_point<T>::value, T>& rhs) const noexcept;
 
   private:
-    /// @brief constructor needs to be private to ensure a unit safe usage of duration
-    constexpr explicit Duration(const long double durationInSeconds);
-    long double durationInSeconds{0.0};
+    SECONDS_TYPE m_seconds{0U};
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp:331]: I think we should use UpperCamelCase with a postfix _t for type aliases. UPPER_SNAKE_CASE are for compile time constants and enum values.

@elBoberido  And according to my faint and wrinkled memory you introduced also the string type aliases like `ProcessName_t` ... How could you forget this?! ;) 

I need to verify that it is really you, what do you say to this
```cpp
if ( bla )
   while ( fuu )
       doStuff();
```

Please answer with at least two Bobs and a Pöhnl!

File: iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp (hunk 27 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp:18]: I added a task to the issue with the Windows port. I think two of them are quite trivial to fix, the other two might need some time.

**Review by elfenpiff — CHANGES_REQUESTED** [review]
Please change all `using` type aliases to UpperCamelCase_t

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 29]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
 }
 
-inline constexpr Duration operator"" _ms(long double value)
+template <typename T>
+inline constexpr Duration Duration::fromFloatingPointSeconds(const T floatingPointSeconds) const noexcept
 {
-    return Duration{value / 1000.0};
+    static_assert(std::is_floating_point<T>::value, "only floating point is allowed");
+
+    if (std::isinf(floatingPointSeconds))
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:382]: Mmhhh. What if Duration == 0? Then you have 0 * infinity? This could become really really weird.

But we get in either case a warning!

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 30]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
 
-inline constexpr Duration operator"" _ms(unsigned long long int value) // PRQA S 48
+template <typename T>
+inline constexpr Duration
+Duration::multiplyWith(const std::enable_if_t<std::is_floating_point<T>::value, T>& rhs) const noexcept
 {
-    return Duration{static_cast<long double>(value) / 1000.0};
+    // operator*(...) takes care of negative values for rhs
+
+    if (std::isnan(rhs))
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:408]: When you assume that not a number is like infinity, what about the case when Duration == 0? In this case duration should not be set to max - after the operation it should still be zero.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 29 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:382]: Well, I decided by a coin flip. Will change it to 0 if Duration is 0

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 31]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
 
-template <typename T>
-inline constexpr T Duration::microSeconds() const
+inline constexpr uint64_t Duration::microSeconds() const noexcept
 {
-    return static_cast<T>(durationInSeconds * 1000000.0);
+    constexpr Seconds_t MAX_SECONDS_BEFORE_OVERFLOW{std::numeric_limits<Seconds_t>::max() / MICROSECS_PER_SEC};
+    constexpr Nanoseconds_t MAX_NANOSECONDS_BEFORE_OVERFLOW{(std::numeric_limits<Seconds_t>::max() % MICROSECS_PER_SEC)
+                                                            * NANOSECS_PER_MICROSEC};
+    constexpr Duration MAX_DURATION_BEFORE_OVERFLOW =
```
Comment (MatthiasKillat) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:159]: We could move the computation of the critical overflow boundary duration to a constexpr function only depending on the ratio (MICROSECS_PER_SEC etc.) Just a minor code duplication reduction though. Not really worth it for 3 uses.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 32]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+
+    return m_seconds * NANOSECS_PER_SEC + m_nanoseconds;
 }
 
-template <typename T>
-inline constexpr T Duration::microSeconds() const
+inline constexpr uint64_t Duration::microSeconds() const noexcept
 {
-    return static_cast<T>(durationInSeconds * 1000000.0);
+    constexpr Seconds_t MAX_SECONDS_BEFORE_OVERFLOW{std::numeric_limits<Seconds_t>::max() / MICROSECS_PER_SEC};
```
Comment (MatthiasKillat) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:156]: I am not sure the overflow duration is correct in general in this way, since it actually depends on the return type (uint64_t). If this is a type larger than Seconds_t the boundary would be to pessimistic I think. Returning max of uint64 is also generally not correct in those cases (it might actually fit into uint64_t and be less).

Currently it is fine since Seconds_t is uint64_t.

I would not think this is a bug for this reason. Moving on.

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 30 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:413]: done

File: iceoryx_utils/source/units/duration.cpp [hunk 33]
```diff
@@ -47,21 +55,26 @@ struct timespec Duration::timespec(const TimeSpecReference& reference) const
         }
         else
         {
-            int64_t timeInNanoSeconds = this->nanoSeconds<int64_t>();
-            int64_t remainingNanoSecondsTimeout = timeInNanoSeconds % NanoSecondsPerSecond;
-            int64_t sumOfNanoSeconds = remainingNanoSecondsTimeout + referenceTime.tv_nsec;
-            int64_t additionalSeconds = sumOfNanoSeconds / NanoSecondsPerSecond;
-            int64_t seconds = timeInNanoSeconds / NanoSecondsPerSecond + referenceTime.tv_sec + additionalSeconds;
-            int64_t nanoSeconds = sumOfNanoSeconds - additionalSeconds * NanoSecondsPerSecond;
+            auto targetTime = Duration(referenceTime) + *this;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/source/units/duration.cpp:58]: yes, that's correct

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 34]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+    return Duration(seconds, nanoseconds);
+}
+
+inline constexpr Duration Duration::max() noexcept
+{
+    return Duration{std::numeric_limits<Seconds_t>::max(), NANOSECS_PER_SEC - 1U};
+}
+
+template <typename T, typename String>
+inline constexpr unsigned long long int Duration::positiveValueOrClampToZero(const T value,
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:61]: even if it takes time, it's just in the unhappy path and logging itself has some costs

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 35]
```diff
@@ -160,9 +160,13 @@ class Mepoo_IntegrationTest : public Test
 
     void PrintTiming(iox::units::Duration start)
     {
-        std::cerr << "RouDi startup took " << start.milliSeconds<int>() << " milliseconds, "
-                  << "(which is " << start.seconds<int>() << " seconds)"
-                  << "(which is " << start.minutes<int>() << " minutes)" << std::endl;
+        auto totalMillisconds = start.milliSeconds();
+        auto millisceonds = totalMillisconds % 1000U;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:165]: oh, that's refreshing. I did a pöhnl, not a bob :D

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 31 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:164]: yes, elfenpiff also suggested it, but the reduction of code would be minimal and I had the feeling it looked uglier.

**Review by elfenpiff — DISMISSED** [review]

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 34 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:61]: Oh wait. You are right. It was in the unhappy path until there was a request to reduce code duplication :D

[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:61]: On the other hand. It's possible to use it in constexpr, so it shouldn't have any extra costs

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 32 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:161]: you are right, it should be the return type

**Review by elfenpiff — DISMISSED** [review]

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 36]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+    constexpr uint64_t SECONDS_PER_FULL_BLOCK{LEAST_COMMON_MULTIPLE / NANOSECS_PER_SEC};
+
+    uint64_t multiplicatorHigh = static_cast<uint32_t>(multiplicator >> 32U);
+    auto nanosecondsFromHigh = m_nanoseconds * multiplicatorHigh;
+    auto fullBlocksOfSecondsOnly = nanosecondsFromHigh / ONE_FULL_BLOCK_OF_SECONDS_ONLY;
+    auto remainingBlockWithFullAndFractionalSeconds = nanosecondsFromHigh % ONE_FULL_BLOCK_OF_SECONDS_ONLY;
+
+    auto durationFromNanosecondsHigh = Duration{fullBlocksOfSecondsOnly * SECONDS_PER_FULL_BLOCK, 0U}
+                                       + Duration::nanoseconds(remainingBlockWithFullAndFractionalSeconds << 32);
+
```
Comment (MatthiasKillat) [inline iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:364]: OK.
1) nanosecondsFromHigh fits into 64 bits.
2) fullBlocksOfSecondsOnly fits into 64 Bits, counts only some seconds and no leftover nanoseconds in multiples of ONE_FULL_BLOCK_OF_SECONDS_ONLY
3) remainingBlockWithFullAndFractionalSeconds fits into 64 bit and contains the remaining nanoseconds, may exceed 10⁹ i.e. contain some full seconds

4) fullBlocksOfSecondsOnly * SECONDS_PER_FULL_BLOCK should still fit into 64 bit
5) Can we guarantee that remainingBlockWithFullAndFractionalSeconds << 32 always fits into 64 bits as well?
Otherwise we might have a problem in certain edge cases.

I need to rethink this ...

If 5) causes no problem, it should be correct (operator+ deals with potential further overflows)

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 37]
```diff
@@ -18,218 +18,1919 @@
...
+
+    multiply(duration, -1, EXPECTED_DURATION);
+    multiply(duration, -1.0, EXPECTED_DURATION);
+}
+
+TEST(Duration_test, MultiplyDurationLessThanOneSecondResultsInMoreNanosecondsThan64BitCanRepresent)
+{
+    constexpr uint64_t MULTIPLICATOR{(1ULL << 32U) * 42U + 73U};
+    constexpr Duration DURATION = 473_ms + 578_us + 511_ns;
+    auto EXPECTED_RESULT = DurationFactory{85428177141U, 573034055U};
```
Comment (MatthiasKillat) [inline iceoryx_utils/test/moduletests/test_unit_duration.cpp:1781]: Hard to follow without calculator. Ideally would be computed (constexpr) from the multiplicator and the individual parts (nanoseconds and seconds) of Duration.

The point is, the nanoseconds overflow. :-)

**Review by MatthiasKillat — DISMISSED** [review]

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 38]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+    // the result;
+    // this cannot be done by dividing through NANOSECS_PER_SEC, since that one is base 1_000_000_000 and the result is
+    // base 2^32, therefore the least common multiple must be used to get blocks of full seconds represented as 2^32
+    // nanoseconds per bit;
+    // this can then safely be converted to seconds as well as nanoseconds without loosing precision
+
+    // least common multiple of 2^32 and NANOSECONDS_PER_SECOND
+    constexpr uint64_t LEAST_COMMON_MULTIPLE{8388608000000000};
+    static_assert(LEAST_COMMON_MULTIPLE % (1ULL << 32) == 0, "invalid multiple");
+    static_assert(LEAST_COMMON_MULTIPLE % NANOSECS_PER_SEC == 0, "invalid multiple");
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:352]: for the following calculation it's not important to be the least common multiple, any common multiple which can be represented in 64 bits will do

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 39]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+    // m_nanoseconds(uint32_t) would fit into 64 bits;
+    // to accurately determine the result, the calculation is split into a multiplication with the lower 32 bits of the
+    // multiplicator and another one with the upper 32 bits;
+
+    // this is the easy part with the lower 32 bits
+    uint64_t multiplicatorLow = static_cast<uint32_t>(multiplicator);
+    auto durationFromNanosecondsLow = Duration::nanoseconds(m_nanoseconds * multiplicatorLow);
+
+    // this is the complicated part with the upper 32 bits;
+    // the m_nanoseconds are multiplied with the upper 32 bits of the multiplicator shifted by 32 bit to the left, thus
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:339]: fixed

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl [hunk 40]
```diff
@@ -20,262 +20,511 @@ namespace iox
...
+    // having again a multiplication of two 32 bit values whose result fits into a 64 bit variable;
+    // one bit of the result represents 2^32 nanoseconds;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:341]: clarified

File: iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl (hunk 36 above)
Comment (elBoberido) [reply iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl:364]: yes, it is the modulo of a number less than 2^32 therefore it can safely be shifted

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp (hunk 37 above)
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_unit_duration.cpp:1781]: yes, the problem is the nanoseconds overflow. It's easier to calculate it with a calculator which supports big numbers :)

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 41]
```diff
@@ -18,218 +18,1919 @@
...
-    result = result / time3;
-    EXPECT_NEAR(result.seconds<double>(), 86.666666666666666, tenTimesEpsilon);
+    EXPECT_THAT(sut1, Eq(DurationFactory::max()));
+    EXPECT_THAT(sut2, Eq(DurationFactory::max()));
+}
+
+TEST(Duration_test, AddDurationResultsInSaturationFromSeconds)
+{
+    auto duration1 =
+        DurationFactory{std::numeric_limits<DurationFactory::Seconds_t>::max() - 2U, NANOSECS_PER_SECOND - 1U};
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_unit_duration.cpp:1479]: fixed

File: iceoryx_utils/test/moduletests/test_unit_duration.cpp [hunk 42]
```diff
@@ -18,218 +18,1919 @@
...
 
-TEST(Duration_test, convertDays)
+constexpr uint64_t MILLISECS_PER_SECOND = Duration::MILLISECS_PER_SEC;
+constexpr uint64_t MICROSECS_PER_SECONDS = Duration::MICROSECS_PER_SEC;
+
+constexpr uint64_t NANOSECS_PER_MICROSECOND = Duration::NANOSECS_PER_MICROSEC;
+constexpr uint64_t NANOSECS_PER_MILLISECOND = Duration::NANOSECS_PER_MILLISEC;
+constexpr uint64_t NANOSECS_PER_SECOND = Duration::NANOSECS_PER_SEC;
+
+struct DurationFactory : public Duration
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_utils/test/moduletests/test_unit_duration.cpp]: renamed to `DurationAccessor`

**Review by MatthiasKillat — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]
