### PR TITLE
iox-#1249 Fix tests on QNX

### LINKED ISSUE #1249: Tests are failing on QNX
## Required information

**Operating system:**
QNX

**Compiler version:**
all

**Observed result or behaviour:**
Some tests are failing on QNX
- the smart lock tests trigger the watchdog on slow hardware
- the UDS uses a wrong max buffer size constant
- some tests blow up the stack size
  - use heap where appropriate and disable when heap usage is not possible
- enable semaphore tests on QNX

**Expected result or behaviour:**
Tests pass on QNX

**Conditions where it occurred / Performed steps:**
Any condition

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This tests fixes some test failures on QNX
- smart lock tests triggered the watchdog on slow hardware
- UDS tests failed due to a too large max message size
- some tests blew up the stack size
  - use heap were appropriate
  - disable TOML gateway config tests due to returning 1MB large `iox::config::GatewayConfig`
- enable semaphore tests on QNX

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1249

### CODE REVIEW

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/platform_settings.hpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ constexpr uint64_t IOX_MAX_PATH_LENGTH = 1023U;
 constexpr bool IOX_SHM_WRITE_ZEROS_ON_CREATION = true;
 constexpr uint64_t IOX_MAX_SHM_NAME_LENGTH = 1024U;
 constexpr const char IOX_PATH_SEPARATORS[] = "/";
-constexpr uint64_t IOX_UDS_SOCKET_MAX_MESSAGE_SIZE = 4096;
+constexpr uint64_t IOX_UDS_SOCKET_MAX_MESSAGE_SIZE = 3990;
```
Comment (elfenpiff) [inline iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/platform_settings.hpp:35]: This is a weird number. Is this QNX specific or is it defined for QNX on a specific target?

**Review by elfenpiff — DISMISSED** [review]

**Review by elfenpiff — APPROVED** [review]

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
