### PR TITLE
iox-#781 update icedelivery output and readme

### LINKED ISSUE #781: Wrong Values of  iox-cpp-subscriber and iox-cpp-publisher
## Required information

**Operating system:**
Debian bullseye

**Compiler version:**
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

**Observed result or behaviour:**
Wrong value from the iox-cpp-subscriber application with iox-cpp-publisher

iox-cpp-publisher
2021-05-08 14:43:23.167 [ Debug ]: Application registered management segment 0x7fb5d4262000 with size 60126248 to id 1
2021-05-08 14:43:23.168 [ Debug ]: Application registered payload data segment 0x7fb5cb3c7000 with size 149264720 to id 2
iox-cpp-publisher sent five times value: 1
iox-cpp-publisher sent five times value: 2
iox-cpp-publisher sent five times value: 3
iox-cpp-publisher sent five times value: 4
iox-cpp-publisher sent five times value: 5
iox-cpp-publisher sent five times value: 6
iox-cpp-publisher sent five times value: 7
iox-cpp-publisher sent five times value: 8
iox-cpp-publisher sent five times value: 9

iox-cpp-subscriber
2021-05-08 14:43:25.775 [ Debug ]: Application registered management segment 0x7fdff2fcf000 with size 60126248 to id 1
2021-05-08 14:43:25.775 [ Debug ]: Application registered payload data segment 0x7fdfea134000 with size 149264720 to id 2
iox-cpp-subscriber got value: 93
iox-cpp-subscriber got value: 148
iox-cpp-subscriber got value: 237
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 381
iox-cpp-subscriber got value: 94
iox-cpp-subscriber got value: 149
iox-cpp-subscriber got value: 238
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 382
iox-cpp-subscriber got value: 95
iox-cpp-subscriber got value: 150
iox-cpp-subscriber got value: 239
iox-cpp-subscriber got value: 6
iox-cpp-subscriber got value: 383
iox-cpp-subscriber got value: 96
iox-cpp-subscriber got value: 151
iox-cpp-subscriber got value: 240

**Expected result or behaviour:**
The correct values should be received in the subscriber side. 

iox-cpp-subscriber
2021-05-08 14:43:25.775 [ Debug ]: Application registered management segment 0x7fdff2fcf000 with size 60126248 to id 1
2021-05-08 14:43:25.775 [ Debug ]: Application registered payload data segment 0x7fdfea134000 with size 149264720 to id 2
iox-cpp-subscriber got value: 3
iox-cpp-subscriber got value: 3
iox-cpp-subscriber got value: 3
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 4
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 5
iox-cpp-subscriber got value: 6
iox-cpp-subscriber got value: 6
iox-cpp-subscriber got value: 6
iox-cpp-subscriber got value: 6
iox-cpp-subscriber got value: 6

**Conditions where it occurred / Performed steps:**
- Build the iceoryx with ./tools/iceoryx_build_test.sh clean debug examples build-test
- Run the ./build/install/prefix/bin/iox-roudi
- Run the ./build/install/prefix/bin/iox-cpp-publisher
- Run the  ./build/install/prefix/bin/iox-cpp-subscriber

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
Signed-off-by: Marika Lehmann <marika.lehmann@apex.ai>

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #781

### CODE REVIEW

File: iceoryx_examples/icedelivery/iox_publisher_untyped.cpp [hunk 1]
```diff
@@ -38,30 +40,45 @@ int main()
...
     iox::popo::UntypedPublisher publisher({"Radar", "FrontLeft", "Object"});
+    //! [create untyped publisher]
 
     double ct = 0.0;
     while (!killswitch)
     {
         ++ct;
 
         // Loan chunk and provide logic to populate it via a lambda
+        //! [loan]
```
Comment (elBoberido) [inline iceoryx_examples/icedelivery/iox_publisher_untyped.cpp:58]: could this two lines maybe be combined?

File: iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp [hunk 2]
```diff
@@ -39,23 +40,38 @@ int main()
     auto signalTermGuard = iox::posix::registerSignalHandler(iox::posix::Signal::TERM, sigHandler);
 
     // initialize runtime
+    //! [runtime initialization]
```
Comment (elBoberido) [inline iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp:43]: also here and following

File: iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp [hunk 3]
```diff
@@ -39,23 +40,38 @@ int main()
...
     // run until interrupted by Ctrl-C
+    //! [loop]
     while (!killswitch)
     {
-        subscriber.take()
+        subscriber
+            .take()
+            //! [chunk happy path]
             .and_then([&](const void* userPayload) {
+                //! [and_then]
```
Comment (elBoberido) [inline iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp:61]: is the `and_then` snippet really necessary?

File: iceoryx_examples/icedelivery/iox_publisher.cpp [hunk 4]
```diff
@@ -45,65 +47,85 @@ int main()
...
+        double sampleValue2 = ct + 144;
+        double sampleValue3 = ct + 233;
+        double sampleValue4 = ct + 377;
 
         // API Usage #1
         //  * Retrieve a typed sample from shared memory.
         //  * Sample can be held until ready to publish.
         //  * Data is default constructed during loan
+        //! [usage1]
         publisher.loan()
```
Comment (elBoberido) [inline iceoryx_examples/icedelivery/iox_publisher.cpp:68]: have you thought about including the comments? It's not directly described in the README so it might help to have it inlcuded.

File: iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp (hunk 3 above)
Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp:61]: Well, I basically used it to elide everything inside the `and_then`path when the while loop is described in the readme (l. 163...). Otherwise the comments regarding the release of the release of the chunk would be visible. I first decided against wrapping those comments inside the release tags since it is already described in the readme, but now I think the `and_then` snippet reduces the readability of the example...

Comment (elBoberido) [reply iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp:61]: I think the comment would also be valuable in the README, maybe a little bit rephrased. The README itself only mention the release and not that a later access will be undefined behavior.

File: iceoryx_examples/icedelivery/iox_publisher.cpp [hunk 5]
```diff
@@ -60,11 +60,11 @@ int main()
         double sampleValue3 = ct + 233;
         double sampleValue4 = ct + 377;
 
+        //! [usage1]
         // API Usage #1
```
Comment (elBoberido) [inline iceoryx_examples/icedelivery/iox_publisher.cpp:64]: I almost don't dare to say it, but could these two lines be combined ;)

Comment (FerdinandSpitzschnueffler) [reply iceoryx_examples/icedelivery/iox_publisher.cpp:64]: Doh!

**Comment by FerdinandSpitzschnueffler** [comment]
I added a task for updating the asciinema record to #743.

**Review by dkroenke — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]
