### PR TITLE
iox-#1230 Introduce barrier in queue stress tests

### LINKED ISSUE #1230: Ensure lock-free queue stress-tests have sufficient resources
## Brief feature description

The lock-free queue stress tests start multiple threads, perform test specific work for a configured time and then check several invariants to decide whether the test passed or failed.

The problem is that under heavy load the threads will not have enough time to perform the work (or be even started), especially on Windows (for some reason).

We can make those test more robust to ensure the timeout only starts when all threads are up and running. However, the OS can arbitrarily suspend threads and will do so if it lacks resources. There is no way to fully ensure it works under load in **any finite time**.

## Detailed information

Use a barrier to wait for all threads.

### PR DESCRIPTION
**Pull request by MatthiasKillat**
Signed-off-by: Matthias Killat <matthias.killat@apex.ai>

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1230

### CODE REVIEW

**Review by elfenpiff — APPROVED** [review]

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp [hunk 1]
```diff
@@ -45,11 +46,58 @@ struct Data
     uint64_t count{0};
 };
 
+class Barrier
```
Comment (elBoberido) [inline iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:49]: Could you move this into testing? I'm sure we could make use of this in other tests as well.

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp [hunk 2]
```diff
@@ -45,11 +46,58 @@ struct Data
...
+    {
+        std::unique_lock<std::mutex> lock(m_mutex);
+        auto cond = [&]() { return m_count >= m_requiredCount; };
+        m_condVar.wait(lock, cond);
+    }
+
+    void reset(uint32_t requiredCount)
+    {
+        m_requiredCount = requiredCount;
+        m_count = 0;
```
Comment (elBoberido) [inline iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:80]: Please guard this changes by a mutex and notify potentially waiting threads.

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp [hunk 3]
```diff
@@ -45,11 +46,58 @@ struct Data
...
+    }
+
+  private:
+    std::atomic<uint32_t> m_count{0};
```
Comment (elBoberido) [inline iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:84]: Does not need to be an atomic since it is guarded by a mutex

**Review by elBoberido — COMMENTED** [review]
Looks good, only minor stuff.

Would it make sence to add a watchdog to prevent deadlocking the CI, e.g. `stress time + 60s`?

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp (hunk 1 above)
Comment (MatthiasKillat) [reply iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:49]: Can do, but it was just a quick draft to try whether this is useful. Will move later but I do not think we want this in 2.0 do we?

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp (hunk 3 above)
Comment (MatthiasKillat) [reply iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:84]: Wanted to avoid the mutex but cannot with condvar.

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:49]: I don't think it's necessary for v2. This problem only occurs under high load and if really necessary, we could still backport to the v2 branch.

**Review by elBoberido — DISMISSED** [review]

**Comment by MatthiasKillat** [comment]
Added the watch dog. The problem is that this can also lead to failure if the system is very busy

File: iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp [hunk 4]
```diff
@@ -336,6 +339,8 @@ class ResizeableLockFreeQueueStressTest : public ::testing::Test
     Queue sut;
 
     std::chrono::seconds runtime{3};
+    const iox::units::Duration m_fatalTimeout = 60_s;
+    Watchdog m_watchdog{m_fatalTimeout};
```
Comment (elBoberido) [inline iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:343]: Something like `const iox::units::Duration m_fatalTimeout = 60_s + ox::units::Duration(runtime);` might save our future self from swearing

Comment (MatthiasKillat) [reply iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp:343]: In principle a good idea, but this does not work with the given conversions. I could introduce another var but would prefer not to.

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

File: iceoryx_posh/source/roudi/port_manager.cpp [hunk 5]
```diff
@@ -67,11 +67,16 @@ PortManager::PortManager(RouDiMemoryInterface* roudiMemoryInterface) noexcept
     registryPortOptions.nodeName = iox::NodeName_t("Service Registry");
     registryPortOptions.offerOnCreate = true;
 
-    m_serviceRegistryPublisherPortData = acquireInternalPublisherPortData(
+    // we cannot /fully) perform discovery without this port
```
Comment (MatthiasKillat) [inline iceoryx_posh/source/roudi/port_manager.cpp:70]: This is needed, otherwise we get the warning that the registry cannot be sent at startup all the time.

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by dkroenke — APPROVED** [review]
