### PR TITLE
Use `GTEST_SKIP` in tests and restructure stress tests

### LINKED ISSUE #1274: Stress Test should not be running on the CI
## Required information

When the CI is under heavy load stress test tend to fail with timeouts. Furthermore, the goal of a stress test to test the system under high contention which is not the case when a CI target has only one core and is under heavy load.

We need to enable the stress test in:
* `iceoryx_hoofs/test/integrationtests/test_lockfree_queue_stresstest.cpp`
* `iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp`

again and find a better way of running them on a target which has enough cores and really run the stress test in a way they were meant to run.

### LINKED ISSUE #1635: Use `GTEST_SKIP` for disabled tests
## Brief feature description

In iceoryx we currently disable google tests by setting `DISABLED_` as prefix in the name of the test case.
A better option is to use: 
```
GTEST_SKIP() << "Some reason to skip this test with ticket number iceoryx/#10200";
```

- [ ] Update all disabled test cases with the macro
- [ ] Update documentation for Contributors

### PR DESCRIPTION
**Pull request by dkroenke**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1274 
- Closes #1635

### CODE REVIEW

File: iceoryx_hoofs/test/stresstests/test_hoofs_stress.cpp [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+#include "iceoryx_hoofs/testing/test.hpp"
+
+using namespace ::testing;
+
+int main(int argc, char* argv[])
+{
+    ::testing::InitGoogleTest(&argc, argv);
+    return RUN_ALL_TESTS();
+}
```
Comment (elBoberido) [inline iceoryx_hoofs/test/stresstests/test_hoofs_stress.cpp:26]: Can you please add a `/// @todo iox-#1345 init testing logger`. I've done this in all existing main test files in the PR for the refactored logger. Just that I don't forget it when once this is merged

File: iceoryx_binding_c/test/moduletests/main.cpp [hunk 2]
```diff
@@ -27,10 +27,10 @@ using ::testing::_;
 
 // in case this isn't executed before the other tests, just call
 // 'checkIceoryxBindingCStorageSizes' directly in main
-/// @todo iox-#308 enable this check once the stack is used to store the objects
-TEST(SanityCheck, DISABLED_CheckStorageSizeAndAlingment)
+TEST(SanityCheck, CheckStorageSizeAndAlingment)
 {
     ::testing::Test::RecordProperty("TEST_ID", "879abe49-6cfb-43f8-a9a1-b6c20b99293f");
+    GTEST_SKIP() << "Enable this check once the stack is used to store the objects iox-#308";
```
Comment (elBoberido) [inline iceoryx_binding_c/test/moduletests/main.cpp:33]: You did not remove the todo from the other files. Was this intentional?

Another question. What do you think about this format `GTEST_SKIP() << "todo iox-#0815 Bla bla`? We might reduce duplication.

Comment (elfenpiff) [reply iceoryx_binding_c/test/moduletests/main.cpp:33]: But we could also remove the todo. In the end we never would like to skip tests, so what about the simple format `GTEST_SKIP() << "iox-#1234 blalall"`

And since every rule needs an exception, the exception here would be if we disable tests for a certain platform. 
`GTEST_SKIP() << "not supported for windows"` with an `ifdef`. But here we could also introduce a small function `SUPPORTED_PLATFORMS(__WIN32, __LINUX__)` or `SKIP_FOR_PLATFORM(__QNX__)`.

File: iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp [hunk 3]
```diff
@@ -193,12 +193,11 @@ TEST_F(variant_Test, EmplaceSecondValidElementWorks)
...
 }
 
-TEST_F(variant_Test, DISABLED_emplaceInvalidElement)
+TEST_F(variant_Test, EmplaceInvalidElementCompileTimeCheck)
 {
     ::testing::Test::RecordProperty("TEST_ID", "6fa3b290-8249-4825-8eac-72235a06710e");
-    // this is a compile time check, if you uncomment this the compiler will
-    // fail
-    //    EXPECT_THAT(sut.emplace< unsigned int >(0), Eq(false));
+    GTEST_SKIP() << "Compile time check, if you uncomment this test, the compiler will fail";
```
Comment (elfenpiff) [inline iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp:199]: You broke your own rule here :smirk: 

Where is the issue number :smile:

File: iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp [hunk 4]
```diff
@@ -15,7 +15,7 @@
 //
 // SPDX-License-Identifier: Apache-2.0
 
-#include "test.hpp"
+#include "iceoryx_hoofs/testing/test.hpp"
```
Comment (elfenpiff) [inline iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp:18]: Are those stress tests executed on the CI?

**Review by elfenpiff — COMMENTED** [review]
Looks good so far. When the question is answered if we add the `iox-#1234` in front of the message we can merge it.

Since there are still disabled tests in iceoryx with macro `ifdef`s I wouldn't close the issue just yet and maybe introduce a function which uses `GTEST_SKIP()`, maybe we could also name it `GTEST_SKIP_ON_PLATFORM(__WIN32)` or so.

**Review by elBoberido — DISMISSED** [review]

File: iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp (hunk 4 above)
Comment (dkroenke) [reply iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp:18]: Not in this CI since it cannot give us guarantees regarding hardware resources.

File: iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp (hunk 3 above)
Comment (dkroenke) [reply iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp:199]: I would be glad if you can help me finding the right ticket for this particular case. I'm also fine with removing that test.

File: iceoryx_binding_c/test/moduletests/main.cpp (hunk 2 above)
Comment (dkroenke) [reply iceoryx_binding_c/test/moduletests/main.cpp]: The `todo` indicates here that there is some follow-up work still left and should be tracked. Otherwise you are forced to add a doxygen todo near to the test.

**Review by elBoberido — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]
