### PR TITLE
Iox #404 Fix verbose output and introduce CmdLineArgs_t struct

### LINKED ISSUE #404: Wrong handling of applications that are started multiple times in parallel
## Required information

**Operating system:**
Gentoo LInux

**Compiler version:**
GCC 9.3.0

**Observed result or behaviour:**
When a second instance of application is started with the same Runtime name we have a wrong handling 
With Monitoring: The second application tries to register again an again as there is no response until it gets a timeout that says there is no RouDi. RouDi ignores the registration as this app is already registered but does not send an error response
Without Monitoring: The second application is accepted. For the first one the shared memory resources are removed. But the first application is still running an on a nice trip to undefined behavior

**Expected result or behaviour:**
RouDi should prevent that multiple instances of applications with the same runtime name are running in parallel and also instantly report a clear error

**Conditions where it occurred / Performed steps:**
Start RouDi and the first instance of the application. Then start another instance of the application

## Bugfix steps

* [x] Fix verbose output when iox-roudi --help
* [ ] Extend timeout info in runtime if RouDi is not answering b/c keepalive limit was not yet reached
* [ ] Send de-register message from runtime d'tor
* [ ] Add APP_ALREADY_REGISTERED message and inform user via runtime

### PR DESCRIPTION
**Pull request by mossmaurice**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
* Fix output when calling `./iox-roudi --help`
* Print command line args in `RouDiApp` instead of in main
* Change interface from `CmdLineParser&` to `CmdLineArgs_t` struct to make RouDi more modular
* Add `CmdLineParser*` unit tests

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [x] Merge

## References

- Partly closes #404

### CODE REVIEW

File: iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp [hunk 1]
```diff
@@ -28,12 +28,12 @@ namespace iox
...
 {
-TomlRouDiConfigFileProvider::TomlRouDiConfigFileProvider(CmdLineParserConfigFileOption& cmdLineParser)
+TomlRouDiConfigFileProvider::TomlRouDiConfigFileProvider(config::CmdLineArgs_t& cmdLineArgs)
 {
     /// don't print additional output if not running
-    if (cmdLineParser.getRun())
+    if (cmdLineArgs.run)
     {
-        if (cmdLineParser.getConfigFilePath().size() == 0)
+        if (cmdLineArgs.configFilePath.size() == 0)
```
Comment (elfenpiff) [inline iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp:36]: In general it is better to write here `cmdLineArgs.configFilePath.empty()`.

File: iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+{
+namespace config
+{
+struct CmdLineArgs_t
+{
+    roudi::MonitoringMode monitoringMode{roudi::MonitoringMode::ON};
+    iox::log::LogLevel logLevel{iox::log::LogLevel::kWarn};
+    version::CompatibilityCheckLevel compatibilityCheckLevel{version::CompatibilityCheckLevel::PATCH};
+    units::Duration processKillDelay{roudi::PROCESS_DEFAULT_KILL_DELAY};
+    cxx::optional<uint16_t> uniqueRouDiId{0};
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp]: Using the default c'tor now.

File: iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp (hunk 1 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp]: Fixed

File: iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp [hunk 3]
```diff
@@ -0,0 +1,59 @@
+// Copyright (c) 2019, 2021 by Robert Bosch GmbH, Apex.AI Inc. All rights reserved.
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp:1]: Please check the copyright header, seems to be wrong for a new file.

Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp:1]: Fixed

File: iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp [hunk 4]
```diff
@@ -24,7 +24,7 @@ namespace iox
 {
 namespace config
 {
-void CmdLineParser::parse(int argc, char* argv[], const CmdLineArgumentParsingMode cmdLineParsingMode) noexcept
+CmdLineArgs_t CmdLineParser::parse(int argc, char* argv[], const CmdLineArgumentParsingMode cmdLineParsingMode) noexcept
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:27]: I'm wondering if this should be a `cxx::expected<CmdLineArgs_t>`? But we would only partially get rid of the `run` member, since it is still needed for `--help`

File: iceoryx_posh/source/roudi/application/roudi_main.cpp [hunk 5]
```diff
@@ -38,9 +39,7 @@ int main(int argc, char* argv[])
             })
             .value();
 
-    cmdLineParser.printParameters();
-
-    IceOryxRouDiApp roudi(cmdLineParser, roudiConfig);
+    IceOryxRouDiApp roudi(cmdLineArgs, roudiConfig);
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/application/roudi_main.cpp:42]: It would be nice to only have the `roudiConfig` here. Ideally such things like the LogLevel could also set by TOML but the cmd line would have a higher precedence. Maybe something for another PR.

**Review by elBoberido — APPROVED** [review]
Do we have tests for the `CmdLineParser`?

File: iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp (hunk 4 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:27]: I had the same though last week. However, I came to the conclusion a parser taking `argc` and `argv` can not fail. If the args are not supported we inform the user and return a defaulted `CmdLineArgs_t`.

File: iceoryx_posh/source/roudi/application/roudi_main.cpp (hunk 5 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/application/roudi_main.cpp:42]: Yeah, good point. For me this is related to the RouDi refactorings for safety certificiation. This epic should be started with #230

File: iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp (hunk 4 above)
Comment (elBoberido) [reply iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:27]: well, wrong args result in RouDi not running. I would consider this as fail ;)

Comment (mossmaurice) [reply iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:27]: When writing the test I realised it's better to switch to an `expected`. We should write more tests :P

File: iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp [hunk 6]
```diff
@@ -24,20 +24,20 @@ namespace iox
...
-                                      {"ignore-version", required_argument, nullptr, 'i'},
                                       {"unique-roudi-id", required_argument, nullptr, 'u'},
-                                      {"compatibility", required_argument, nullptr, 'c'},
+                                      {"compatibility", required_argument, nullptr, 'x'},
                                       {"kill-delay", required_argument, nullptr, 'k'},
                                       {nullptr, 0, nullptr, 0}};
 
     // colon after shortOption means it requires an argument, two colons mean optional argument
-    constexpr const char* shortOptions = "hvm:l:u:c:k:";
+    constexpr const char* shortOptions = "hvm:l:u:x:k:";
```
Comment (mossmaurice) [inline iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:40]: Hope this change won't lead to misfortune :laughing:

Comment (elBoberido) [reply iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp:40]: oh no, the luck is gone :laughing:

File: iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp [hunk 7]
```diff
@@ -0,0 +1,429 @@
...
+    EXPECT_THAT(result.value().run, Eq(false));
+}
+
+TEST_F(CmdLineParser_test, UniqueIdLongOptionLeadsToCorrectUniqueId)
+{
+    constexpr uint8_t numberOfArgs{3U};
+    char* args[numberOfArgs];
+    char appName[] = "./foo";
+    char option[] = "--unique-roudi-id";
+    char wrongValue[] = "4242";
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp:380]: c&p error. I guess this should be only `value`

File: iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp [hunk 8]
```diff
@@ -0,0 +1,429 @@
...
+    EXPECT_THAT(result.value().uniqueRouDiId.value(), Eq(4242));
+}
+
+TEST_F(CmdLineParser_test, UniqueIdShortOptionLeadsToCorrectUniqueId)
+{
+    constexpr uint8_t numberOfArgs{3U};
+    char* args[numberOfArgs];
+    char appName[] = "./foo";
+    char option[] = "-u";
+    char wrongValue[] = "4242";
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp:399]: same here

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp [hunk 9]
```diff
@@ -25,7 +25,13 @@ int main(int argc, char* argv[])
...
 
     iox::config::CmdLineParserConfigFileOption cmdLineParser;
-    cmdLineParser.parse(argc, argv);
+    auto cmdLineArgs = cmdLineParser.parse(argc, argv).or_else([](iox::config::CmdLineParserResult& error) {
+        if (error == iox::config::CmdLineParserResult::UNKNOWN_OPTION_USED)
+        {
+            iox::LogFatal() << "Unable to parse command line arguments!";
+            std::terminate();
+        }
+    });
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:34]: Agree, switched to an early exit, that fits best to our existing code base.

File: iceoryx_posh/source/roudi/application/roudi_main.cpp [hunk 10]
```diff
@@ -24,9 +25,15 @@ int main(int argc, char* argv[])
     using iox::roudi::IceOryxRouDiApp;
 
     iox::config::CmdLineParserConfigFileOption cmdLineParser;
-    cmdLineParser.parse(argc, argv);
+    auto cmdLineArgs = cmdLineParser.parse(argc, argv).or_else([](iox::config::CmdLineParserResult& error) {
+        if (error == iox::config::CmdLineParserResult::UNKNOWN_OPTION_USED)
+        {
+            iox::LogFatal() << "Unable to parse command line arguments!";
+            std::terminate();
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/application/roudi_main.cpp:32]: Fixed. Did the same thing for `configFileProvider.parse()`

File: iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp (hunk 8 above)
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp:399]: Done

File: iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp (hunk 7 above)
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp:380]: Done

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp [hunk 11]
```diff
@@ -25,7 +25,15 @@ int main(int argc, char* argv[])
     static constexpr uint32_t ONE_MEGABYTE = 1024U * 1024;
 
     iox::config::CmdLineParserConfigFileOption cmdLineParser;
-    cmdLineParser.parse(argc, argv);
+    auto cmdLineArgs = cmdLineParser.parse(argc, argv);
+    if (cmdLineArgs.has_error())
```
Comment (ithier) [inline iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Should we have a default case ?  What information does the user get back when the error is not `UNKNOWN_OPTION_USED` ?

File: iceoryx_posh/source/roudi/application/roudi_main.cpp [hunk 12]
```diff
@@ -24,23 +25,28 @@ int main(int argc, char* argv[])
...
-                                                                 parseResult);
-                std::terminate();
-            })
-            .value();
-
-    cmdLineParser.printParameters();
-
-    IceOryxRouDiApp roudi(cmdLineParser, roudiConfig);
+    auto cmdLineArgs = cmdLineParser.parse(argc, argv);
+    if (cmdLineArgs.has_error())
```
Comment (ithier) [inline iceoryx_posh/source/roudi/application/roudi_main.cpp:29]: Again, do we need default behaviour in case of error ?

**Review by ithier — APPROVED** [review]
Only one minor point to consider otherwise looks good.

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp (hunk 11 above)
Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: This is a topic for a future pull request. `m_run` in `CmdLineArgs_t` could be replaced with `CmdLineParserResult::INFO_OUTPUT_ONLY`. Currently no other error that `UNKNOWN_OPTION_USED` is used. So it's fine.

File: iceoryx_posh/source/roudi/application/roudi_main.cpp (hunk 12 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/application/roudi_main.cpp:29]: See in previous comment. Topic for a follow-up pull request

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp (hunk 11 above)
Comment (ithier) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Currently yes.. but what happens when someone adds another error and forgets to update this? 
All good if covered later though.

Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Created #539

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp [hunk 13]
```diff
@@ -25,7 +25,15 @@ int main(int argc, char* argv[])
...
+    {
+        if (cmdLineArgs.get_error() == iox::config::CmdLineParserResult::UNKNOWN_OPTION_USED)
```
Comment (elBoberido) [inline iceoryx_examples/iceperf/roudi_main_static_config.cpp:31]: how about using `if (cmdLineArgs.get_error() != iox::config::CmdLineParserResult::INFO_OUTPUT_ONLY)` then we are safe if we forget to adjust this.
The two if statements could also be combined in a single one with `&&`

Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp]: Good idea, adapted as proposed.

**Review by elBoberido — APPROVED** [review]

File: iceoryx_examples/iceperf/roudi_main_static_config.cpp [hunk 14]
```diff
@@ -25,7 +25,12 @@ int main(int argc, char* argv[])
     static constexpr uint32_t ONE_MEGABYTE = 1024U * 1024;
 
     iox::config::CmdLineParserConfigFileOption cmdLineParser;
-    cmdLineParser.parse(argc, argv);
+    auto cmdLineArgs = cmdLineParser.parse(argc, argv);
+    if (cmdLineArgs.has_error() && (cmdLineArgs.get_error() != iox::config::CmdLineParserResult::INFO_OUTPUT_ONLY))
```
Comment (ithier) [inline iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Is `INFO_OUTPUT_ONLY` an error or success result ?

Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Neither an error nor a success, but something inbetween. This is why I called it `CmdLineParserResult` and not `CmdLineParserError`. We did the same for removing the `optional` inside a `expected` for the new v1.0 API. However, the methods are still called `get_error()`. We might consider renaming them to `get_result()`.

Comment (ithier) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Yeah... but then `get_error` can be a lie !

Comment (mossmaurice) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: Rust uses the same terminology as we currently do.

@elBoberido What's your take on this?

Comment (elBoberido) [reply iceoryx_examples/iceperf/roudi_main_static_config.cpp:29]: both of you are right ... and I have to leave 😁
`get_unexpected` might be a better name is this case, but I'm not quite sure what's in the `expected` proposal.
As mossmaurice pointed out, Rust does it the same way, although it would be more idiomatic to use a `Result<Option<CmdLineArgs>, E>` in this case.
I'm slightly leaning towards being pragmatic and keep it as it is, since we are doing the same with `takeResult` in the `Subscriber`. We could think of renaming the method, though.

**Review by ithier — APPROVED** [review]
