### PR TITLE
Iox #495 compile iceoryx on gcc 5

### LINKED ISSUE #495: fail build on ubuntu 16.04 with g++ 5.4.0
## Required information

**Operating system:**
PRETTY_NAME="Ubuntu 16.04.7 LTS"

**Compiler version:**
Target: x86_64-linux-gnu
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Observed result or behaviour:**
See attached log file [compiler_log_BH1SCW.txt](https://github.com/eclipse-iceoryx/iceoryx/files/6090535/compiler_log_BH1SCW.txt)

**Expected result or behaviour:**
build with no error 

**Conditions where it occurred / Performed steps:**
git commit id:
current master (original f1c4b31c54cc7fccb352fc3cdda562d9a22fe638)

---

Issues:
- [ ] Unsupported compiler command line option `-Wno-noexcept-type`
- [ ] Call to ostream from constexpr function; basically all `clog` calls in `duration.inl`; added in PR #501
   Error: `call to non-constexpr function ‘std::basic_ostream`

### PR DESCRIPTION
**Pull request by dkroenke**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
@BH1SCW This is the PR for compiling iceoryx on GCC 5.4, please check out if it works on your side. Please note that i installed manually a newer CMake version on Ubuntu 16 for building.

- add namespace to SubscribeState in C-Binding
- initialize NodeName_t in posh_runtime correctly
- rework lambda in PortManager for capturing this instead of reference

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [ ] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- Closes #495

### CODE REVIEW

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp [hunk 1]
```diff
@@ -120,9 +121,10 @@ class PortManager
     void addEntryToServiceRegistry(const capro::IdString_t& service, const capro::IdString_t& instance) noexcept;
     void removeEntryFromServiceRegistry(const capro::IdString_t& service, const capro::IdString_t& instance) noexcept;
 
+    // clang-format off
```
Comment (dkroenke) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:124]: Maybe one word why i did this:
Problem is that noexcept is put into a new line because of the 120 char limit. When i try to reduce it with `using ServiceDescription = capro::ServiceDescription` then i solve it here but have the same problem with the function below.

Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:124]: which version of clang-format are you using? I get the following
```
    template <typename T, std::enable_if_t<std::is_same<T, iox::build::OneToManyPolicy>::value>* = nullptr>
    cxx::optional<ProcessName_t>
    doesViolateCommunicationPolicy(const capro::ServiceDescription& service) const noexcept;
```
Essentially what it was before

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp [hunk 2]
```diff
@@ -78,7 +78,8 @@ class PortManager
 
     popo::InterfacePortData* acquireInterfacePortData(capro::Interfaces interface,
                                                       const ProcessName_t& processName,
-                                                      const NodeName_t& node = "") noexcept;
+                                                      const NodeName_t& node = NodeName_t(cxx::TruncateToCapacity,
+                                                                                          "default")) noexcept;
```
Comment (elBoberido) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp:82]: why `"default"?`

From my point of view, the initialization adds noise and does uglify the code for a not supported compiler. Could you check if `const NodeName_t& node = {""}` works with GCC 5?

File: iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp [hunk 3]
```diff
@@ -109,15 +109,16 @@ class PoshRuntime
...
                             const PortConfigInfo& portConfigInfo = PortConfigInfo()) noexcept;
 
     /// @brief request the RouDi daemon to create an interface port
     /// @param[in] interface interface to create
     /// @param[in] nodeName name of the node where the interface should belong to
     /// @return pointer to a created interface port data
     popo::InterfacePortData* getMiddlewareInterface(const capro::Interfaces interface,
-                                                    const NodeName_t& nodeName = "") noexcept;
+                                                    const NodeName_t& nodeName = NodeName_t(cxx::TruncateToCapacity,
+                                                                                            "default")) noexcept;
```
Comment (elBoberido) [inline iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp:121]: again, why `"default"`? It's not changed for `getMiddlewarePublisher` or `getMiddlewareSubscriber`

File: iceoryx_posh/test/moduletests/test_roudi_process.cpp [hunk 4]
```diff
@@ -40,7 +40,7 @@ class MqInterfaceUser_Mock : public iox::roudi::RouDiProcess
 class RouDiProcess_test : public Test
 {
   public:
-    const iox::ProcessName_t processname = "TestRoudiProcess";
+    const iox::ProcessName_t processname = iox::ProcessName_t(iox::cxx::TruncateToCapacity, "TestRoudiProcess");
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_process.cpp:43]: same here, please check if `{"TestRoudiProcess"}` works

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp (hunk 1 above)
Comment (dkroenke) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp]: sorry mistake on my side

**Review by elBoberido — APPROVED** [review]

**Comment by BH1SCW** [comment]
This patch works for me!
All of you guys, I really thank you.

**Review by elfenpiff — APPROVED** [review]

**Comment by elBoberido** [comment]
@BH1SCW you're welcome. We cannot promise that we don't break it again, since we don't have a CI for GCC5.

**Comment by BH1SCW** [comment]
> @BH1SCW you're welcome. We cannot promise that we don't break it again, since we don't have a CI for GCC5.

Never mind :) Maybe I will keep building the code from time to time.
