### PR TITLE
Iox #404 Extend timeout registration info and send termination request on destruction

### LINKED ISSUE #404: Wrong handling of applications that are started multiple times in parallel
## Required information

**Operating system:**
Gentoo LInux

**Compiler version:**
GCC 9.3.0

**Observed result or behaviour:**
When a second instance of application is started with the same Runtime name we have a wrong handling 
With Monitoring: The second application tries to register again an again as there is no response until it gets a timeout that says there is no RouDi. RouDi ignores the registration as this app is already registered but does not send an error response
Without Monitoring: The second application is accepted. For the first one the shared memory resources are removed. But the first application is still running an on a nice trip to undefined behavior

**Expected result or behaviour:**
RouDi should prevent that multiple instances of applications with the same runtime name are running in parallel and also instantly report a clear error

**Conditions where it occurred / Performed steps:**
Start RouDi and the first instance of the application. Then start another instance of the application

## Bugfix steps

* [x] Fix verbose output when iox-roudi --help
* [ ] Extend timeout info in runtime if RouDi is not answering b/c keepalive limit was not yet reached
* [ ] Send de-register message from runtime d'tor
* [ ] Add APP_ALREADY_REGISTERED message and inform user via runtime

### PR DESCRIPTION
**Pull request by mossmaurice**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer

* Addresses all points of #404 
* Refactor `ProcessManager`
  * Move it into its own `hpp` 
  * Replace `getProcessFromList` with `searchForProcessAndThen`
* Wrap `m_prcMgr` in `smart_lock` and get rid of internal mutex

### Todo

* Remove `RouDiLock` in follow-up pull request

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- closes #404

### CODE REVIEW

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp [hunk 1]
```diff
@@ -0,0 +1,95 @@
+// Copyright (c) 2019 by Robert Bosch GmbH. All rights reserved.
```
Comment (mossmaurice) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp:1]: This is not a new file. Finally managed to nicely split a file with ful history :sunglasses: Try `git blame` locally.

File: iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+
+TEST_F(IpcInterfaceCreator_test, CreateWithDifferentNameWorks)
+{
+    IpcInterfaceCreator m_sut{goodName};
+    IpcInterfaceCreator m_sut2{anotherGoodName};
+    EXPECT_TRUE(m_sut.isInitialized());
+    EXPECT_TRUE(m_sut2.isInitialized());
+}
+
+TEST_F(IpcInterfaceCreator_test, CreateWithSameNameLeadsToError)
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp:63]: My first idea was to put the `posix::FileLock` into `IpcInterfaceCreator`. However, it might be better placed into `PoshRuntime` directly. Then these test cases should be moved to the `PoshRuntime`

File: iceoryx_posh/source/runtime/posh_runtime.cpp [hunk 3]
```diff
@@ -87,11 +87,28 @@ PoshRuntime::PoshRuntime(cxx::optional<const ProcessName_t*> name, const bool do
     {
         LogWarn() << "Running applications on 32-bit architectures is not supported! Use at your own risk!";
     }
+
+    /// @todo #404 Use posix::FileLock here
+    //
+    // if (m_fileLock.hasError())
```
Comment (mossmaurice) [inline iceoryx_posh/source/runtime/posh_runtime.cpp:93]: Other ideas discussed in #404 included a ping pong between RouDi and the app or even some sort of protocol. IMHO a file lock solution is straight forward, no communication with RouDi is necessary. Resources like the UNIX domain socket or the message queue should not be cleaned up by RouDi, but instead by its owner.

File: iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp [hunk 4]
```diff
@@ -51,6 +51,7 @@ namespace iox
     error(POSH__RUNTIME_ROUDI_GET_MW_APPLICATION_WRONG_IPC_MESSAGE_RESPONSE) \
     error(POSH__RUNTIME_ROUDI_CONDITION_VARIABLE_CREATION_UNDEFINED_BEHAVIOR) \
     error(POSH__RUNTIME_ROUDI_EVENT_VARIABLE_CREATION_UNDEFINED_BEHAVIOR) \
+    error(POSH__RUNTIME_APP_WITH_SAME_NAME_STILL_RUNNING) \
```
Comment (elfenpiff) [inline iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp:54]: Please remove this - we explicitly want that! What we do not want that two applications (with a random name initialize a runtime with the same name)

**Review by elfenpiff — DISMISSED** [review]
I am confused here but let me state it clearly, I think most of the problem I mention in the review comments are not your fault and not caused by you! But here we have to do some heavy refactoring since we have several severe issues.
1. Lifetime of processes are not handled with RAII
2. Ownership is not as it should be Process/ProcessManager
    1. ProcessManager owns Processes
    2. Processes owns Nodes
    3. Nodes owns Ports, Condition Variables etc.
3. Error prone and unecessary complex structures like `searchForProcessAndThen` causes by the problems above (I understand and agree with the idea but we should not abstract here to much since it overcomplicates things - we need a total refactoring)

Because of those problems mentioned above I would prefer if the pull request would change as little as possible and only implements the feature (even when it is in a dirty way).

But here we introducing some abstraction, new error codes and maybe new behavior (or maybe the ProcessName stuff just confuses me too much which is a sign that this is to complex) which can make the refactoring even harder.

File: iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp [hunk 5]
```diff
@@ -51,6 +51,7 @@ enum class IpcMessageType : int32_t
     NOTYPE = 0,
     REG, // register app
     REG_ACK,
+    REG_FAIL_APP_ALREADY_REGISTERED,
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp:54]: Ctrl-F is your friend ;) It's in `ipc_runtime_interface.cpp:257`. This line can be reached if a process crashed and re-registers during the monitoring window (currently <1.5s).

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+    /// @brief This class represents an application which has registered at RouDi and manages the communication to the
+    /// application
+    /// @param [in] name of the process; this is equal to the IPC channel name, which is used for communication
+    /// @param [in] pid is the host system process id
+    /// @param [in] payloadMemoryManager is a pointer to the payload memory manager for this process
+    /// @param [in] isMonitored indicates if the process should be monitored for being alive
+    /// @param [in] payloadSegmentId is an identifier for the shm payload segment
+    /// @param [in] sessionId is an ID generated by RouDi to prevent sending outdated IPC channel transmission
+    Process(const ProcessName_t& name,
+            int32_t pid,
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp:50]: Done. AFAICT `const mepoo::MemoryManager` (const data) is not possible because of `ChunkSenderData(cxx::not_null<mepoo::MemoryManager* const> memoryManager,..)`

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+
+    /// @brief The session ID which is used to check outdated IPC channel transmissions for this process
+    /// @return the session ID for this process
+    uint64_t getSessionId() noexcept;
+
+    void setTimestamp(const mepoo::TimePointNs_t timestamp) noexcept;
+
+    mepoo::TimePointNs_t getTimestamp() noexcept;
+
+    mepoo::MemoryManager* getPayloadMemoryManager() const noexcept;
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp:77]: Agree, changed the return type. However, did not completely refactor it. It goes down as deep as into e.g. the `ChunkSenderData(cxx::not_null<mepoo::MemoryManager* const> memoryManager,..)`

File: iceoryx_posh/source/runtime/ipc_runtime_interface.cpp [hunk 8]
```diff
@@ -253,6 +254,14 @@ IpcRuntimeInterface::RegAckResult IpcRuntimeInterface::waitForRegAck(int64_t tra
                     LogWarn() << "Received a REG_ACK with an outdated timestamp!";
                 }
             }
+            else if (stringToIpcMessageType(cmd.c_str()) == IpcMessageType::REG_FAIL_APP_ALREADY_REGISTERED)
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/runtime/ipc_runtime_interface.cpp:257]: I think you misunderstood something here. This error is sent if the `RuntimeName` used as param for `PoshRuntime::initRuntime(RuntimeName)` was already used before. One could e.g. start the same binary and pass the RuntimeName as command line parameter. Reworded the error.

File: iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp (hunk 2 above)
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp:63]: Slept over it. Think I'll move `m_fileLock` back to the `IpcInterfaceCreator`. This is the requirement for exclusivity comes from. There should only be one `Creator` with the same RuntimeName.

**Comment by mossmaurice** [comment]
> I am confused here but let me state it clearly, I think most of the problem I mention in the review comments are not your fault and not caused by you! But here we have to do some heavy refactoring since we have several severe issues.
> 
>     1. Lifetime of processes are not handled with RAII
> 
>     2. Ownership is not as it should be Process/ProcessManager
>        
>        1. ProcessManager owns Processes
>        2. Processes owns Nodes
>        3. Nodes owns Ports, Condition Variables etc.
> 
>     3. Error prone and unecessary complex structures like `searchForProcessAndThen` causes by the problems above (I understand and agree with the idea but we should not abstract here to much since it overcomplicates things - we need a total refactoring)
> 
> 
> Because of those problems mentioned above I would prefer if the pull request would change as little as possible and only implements the feature (even when it is in a dirty way).
> 
> But here we introducing some abstraction, new error codes and maybe new behavior (or maybe the ProcessName stuff just confuses me too much which is a sign that this is to complex) which can make the refactoring even harder.

Definitely agree with you! Our own guidelines like RAII or a clear responsibility are not considered by `ProcessManager`. However, I disagree with you on tackle this in a "dirty way". This builds up technical debt and can make things even more difficult in the end. I think "drive-by-refactorings" are an important step. Rome wasn't built in a day, either.

Long term: I've created both #611 and a [design draft](https://github.com/ApexAI/iceoryx/commit/c6685e7b40ad364338a5b7b69b409e29b443fcff) on how to tackle this topic with a future release. Please review and feel free to edit.

FYI @budrus @elBoberido

File: iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+
+    EXPECT_FALSE(unregisterResult);
+}
+
+TEST_F(ProcessManager_test, RegisterAndUnregisterWorks)
+{
+    auto registerResult = m_sut->registerProcess(m_processname, m_pid, m_user, m_isMonitored, 1U, 1U, m_versionInfo);
+    auto unregisterResult = m_sut->unregisterProcess(m_processname);
+
+    EXPECT_TRUE(registerResult);
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp:118]: this is unnecessary, since we already know that it works

File: iceoryx_posh/source/runtime/posh_runtime.cpp [hunk 10]
```diff
@@ -87,11 +87,28 @@ PoshRuntime::PoshRuntime(cxx::optional<const ProcessName_t*> name, const bool do
...
 PoshRuntime::~PoshRuntime() noexcept
 {
+    // Inform RouDi that we're shuting down
+    IpcMessage shutdown;
+    shutdown << IpcMessageTypeToString(IpcMessageType::TERMINATION) << m_appName;
+    m_ipcChannelInterface.sendMessageToRouDi(shutdown);
+
     if (m_applicationPort)
     {
         m_applicationPort.destroy();
```
Comment (elBoberido) [inline iceoryx_posh/source/runtime/posh_runtime.cpp:114]: This is a race. RouDi already cleans up the application port and might have already delivered it to another application. `sendMessageToRouDi` is also not used anywhere else. Please consider using `sendRequestToRoudi`, then let RouDi respond with an `ACK` and cleanup the ports. The runtime wouldn't do anything.
`sendMessageToRouDi` should probably be removed.

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 11]
```diff
@@ -434,20 +355,29 @@ bool ProcessManager::addProcess(const ProcessName_t& name,
...
-    std::lock_guard<std::mutex> lockGuard(m_mutex);
     // we need to search for the process (currently linear search)
-
     auto it = m_processList.begin();
     while (it != m_processList.end())
     {
         auto otherName = it->getName();
         if (name == otherName)
         {
-            if (removeProcess(lockGuard, it))
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/process_manager.cpp:448]: please don't remove the safety net with the lock guard

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 12]
```diff
@@ -472,321 +406,269 @@ bool ProcessManager::removeProcess(const std::lock_guard<std::mutex>& lockGuard
...
-    }
-    else
-    {
-        LogWarn() << "Unknown process " << processName << " requested a node.";
-    }
+    searchForProcessAndThen(
+        processName,
+        [&](Process& process) {
+            m_portManager.acquireNodeData(processName, nodeName)
+                .and_then([&](auto nodeData) {
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/process_manager.cpp:493]: I thought we had a rule to not call a lambda within a lambda. Not sure though.

File: iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp (hunk 4 above)
Comment (mossmaurice) [reply iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp]: Added to #611

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 12 above)
Comment (elfenpiff) [reply iceoryx_posh/source/roudi/process_manager.cpp:493]: @elBoberido I think we can never enforce such a rule. Just think of a lambda which is calling a function, which is calling a function, which is calling a function, which is calling a function, which is calling a function, which is calling a function,
which is calling a lambda.

Comment (elBoberido) [reply iceoryx_posh/source/roudi/process_manager.cpp:493]: @elfenpiff well, you can if you forbid calling functions in lambdas :laughing: ... it would be impractical, though

Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp:493]: Thanks for raising this point @elBoberido IIRC there is a MISRA rule. Couldn't find it by a quick search. However, the AUTOSAR guideline states on [P93](https://www.autosar.org/fileadmin/user_upload/standards/adaptive/18-10/AUTOSAR_RS_CPP14Guidelines.pdf), that nested lambdas reduce the readablity of the code. It is tagged _Advisory_ and not _Required_. In general I agree with this statement, on the other side with our error handling conception `cxx::expected` I'm already aware of a dozen of occurences. I'd also vote not to forbid nesting lambdas. Longing for Axivion CI scan...

File: iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp [hunk 13]
```diff
@@ -149,7 +149,11 @@ cxx::expected<bool, IpcChannelError> UnixDomainSocket::unlinkIfExists(const NoPa
     if (!unlinkCall.hasErrors())
     {
         // ENOENT is set if this socket is not known
-        return cxx::success<bool>(unlinkCall.getErrNum() != ENOENT);
+        if (unlinkCall.getErrNum() == ENOENT)
+        {
+            return cxx::error<IpcChannelError>(IpcChannelError::NO_SUCH_CHANNEL);
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp]: Correct, that was an necessary left-over. Reverted and rebased.

TIL: `git rebase -i HASH --rebase-merges` makes it super easy to rebase and old branch with lots of origin/master merge commits.

FYI @JimmyBch

File: iceoryx_utils/source/posix_wrapper/message_queue.cpp [hunk 14]
```diff
@@ -140,7 +140,11 @@ cxx::expected<bool, IpcChannelError> MessageQueue::unlinkIfExists(const IpcChann
     if (!mqCall.hasErrors())
     {
         // ENOENT is set if the message queue could not be unlinked
-        return cxx::success<bool>(mqCall.getErrNum() != ENOENT);
+        if (mqCall.getErrNum() == ENOENT)
+        {
+            return cxx::error<IpcChannelError>(IpcChannelError::NO_SUCH_CHANNEL);
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_utils/source/posix_wrapper/message_queue.cpp]: Reverted and rebased

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 15]
```diff
@@ -645,3 +645,10 @@ TEST(PoshRuntimeFactory_test, DISABLED_SetEmptyRuntimeFactoryFails)
     // just in case the previous test doesn't die and breaks the following tests
     PoshRuntimeTestAccess::resetRuntimeFactory();
 }
+
+TEST_F(PoshRuntime_test, DISABLED_DestructionLeadsToUnregisterCall)
+{
+    m_runtime->~PoshRuntime();
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_posh_runtime.cpp]: This was just meant to be an example for @dkroenke on what kind of SWE.6 tests would be great. I use draft pull requests to doodle around sometimes :smile:

File: iceoryx_posh/source/runtime/posh_runtime.cpp (hunk 10 above)
Comment (mossmaurice) [reply iceoryx_posh/source/runtime/posh_runtime.cpp:114]: You're right, done. I hope we can solve this even cleaner with inter-process RAII in #611

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp [hunk 16]
```diff
@@ -140,7 +141,7 @@ class RouDi
     /// RouDiMemoryManager outlives some MemoryBlocks
     cxx::GenericRAII m_roudiMemoryManagerCleaner{[]() {}, [this]() { this->m_roudiMemoryInterface->destroyMemory(); }};
     PortManager* m_portManager;
```
Comment (dkroenke) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp:143]: I know you didn't touched the code, but would you add a nullptr init here?

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 17]
```diff
@@ -120,7 +67,7 @@ class ProcessManager : public ProcessManagerInterface
     /// @param [in] transmissionTimestamp is an ID for the application to check for the expected response
     /// @param [in] sessionId is an ID generated by RouDi to prevent sending outdated IPC channel transmission
     /// @param [in] versionInfo Version of iceoryx used
-    /// @return Returns if the process could be added successfully.
+    /// @return true if unknown process was registered, false if process is already known
     bool registerProcess(const ProcessName_t& name,
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:71]: I agree, the `ProcessManager` needs some proper rework. Created design draft in #620 We can tackle this for v1.x

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 18]
```diff
@@ -200,6 +155,11 @@ class ProcessManager : public ProcessManagerInterface
     /// @return Returns true if the process was found and removed from the internal list.
     bool removeProcess(const ProcessName_t& name) noexcept;
 
+    /// @brief Removes the given process from the managed client process list without taking the list's lock!
+    /// @param [in] processIter The process which should be removed.
+    /// @return Returns true if the process was found and removed from the internal list.
+    bool removeProcess(ProcessList_t::iterator& processIter) noexcept;
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp]: Done, wrapped the `ProcessManager` object in a `smart_lock`.

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 19]
```diff
@@ -804,7 +686,7 @@ void ProcessManager::run() noexcept
 popo::PublisherPortData* ProcessManager::addIntrospectionPublisherPort(const capro::ServiceDescription& service,
                                                                        const ProcessName_t& process_name) noexcept
 {
-    std::lock_guard<std::mutex> g(m_mutex);
+    std::lock_guard<std::mutex> g(m_mutex); /// @todo can safely be removed?
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp]: Right. Wrapped the `ProcessManager` object in a `smart_lock` and removed the internal mutex.

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 20]
```diff
@@ -881,7 +771,7 @@ void ProcessManager::monitorProcesses() noexcept
 
 void ProcessManager::discoveryUpdate() noexcept
 {
-    std::lock_guard<std::mutex> g(m_mutex);
+    std::lock_guard<std::mutex> g(m_mutex); /// @todo can safely be removed?
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp]: :+1:  Wrapped the `ProcessManager` object in a `smart_lock` and removed the internal mutex.

File: iceoryx_posh/test/moduletests/test_posh_runtime.cpp [hunk 21]
```diff
@@ -645,3 +645,10 @@ TEST(PoshRuntimeFactory_test, DISABLED_SetEmptyRuntimeFactoryFails)
...
+    // EXPECT_CALL(m_roudiEnv.m_roudiApp, unregisterProcess).Times(1);
+    PoshRuntimeTestAccess::resetRuntimeFactory();
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_posh_runtime.cpp]: See answer [here](https://github.com/eclipse-iceoryx/iceoryx/pull/598#discussion_r595854941).

File: iceoryx_posh/source/runtime/ipc_interface_base.cpp [hunk 22]
```diff
@@ -189,12 +189,11 @@ bool IpcInterfaceBase::hasClosableIpcChannel() const noexcept
     return m_ipcChannel.isInitialized();
 }
 
-void IpcInterfaceBase::cleanupOutdatedIpcChannel(const ProcessName_t& name) noexcept
+bool IpcInterfaceBase::cleanupOutdatedIpcChannel(const ProcessName_t& name) noexcept
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/runtime/ipc_interface_base.cpp]: You're right. Didn't fully revert some temporary changes. Reverted & rebased.

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 11 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp]: Locking is now done via `smart_lock` around the `ProcessManager` object.

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp [hunk 23]
```diff
@@ -19,7 +19,7 @@
 #include "iceoryx_posh/internal/log/posh_logging.hpp"
 #include "iceoryx_posh/internal/mepoo/memory_manager.hpp"
 #include "iceoryx_posh/internal/roudi/port_manager.hpp"
-#include "iceoryx_posh/internal/roudi/roudi_process.hpp"
+#include "iceoryx_posh/internal/roudi/process.hpp"
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp:22]: Done

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 24]
```diff
@@ -129,11 +76,24 @@ class ProcessManager : public ProcessManagerInterface
...
                          const version::VersionInfo& versionInfo) noexcept;
 
-    /// @brief Kills all registered processes. First try with a SIGTERM and if they have not terminated after
-    /// processKillDelay they are killed with SIGKILL. If RouDi doesn't have sufficient rights to kill the process, the
+    /// @brief Unregisters a process at the ProcessManager
+    /// @param [in] name of the process which wants to unregister
+    /// @return true if known process was unregistered, false if process is unknown
+    bool unregisterProcess(const ProcessName_t& name) noexcept;
+
+    /// @brief Kills all registered processes. If RouDi doesn't have sufficient rights to kill the process, the
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:84]: From a user's point of view, that's an implementation detail. Are you ok with leaving that out?

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 25]
```diff
@@ -129,11 +76,24 @@ class ProcessManager : public ProcessManagerInterface
...
     /// process is considered killed.
-    /// @param [in] processKillDelay Amount of time RouDi will wait before killing
-    void killAllProcesses(const units::Duration processKillDelay) noexcept;
+    void killAllProcessesTheHardWay() noexcept;
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:86]: You're right. Done.

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 26]
```diff
@@ -129,11 +76,24 @@ class ProcessManager : public ProcessManagerInterface
...
+
+    /// @brief Informs the user about the processes which are still and the list and then clears the list
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:88]: Left out the SIGTERM, as that's an implementation detail.

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 27]
```diff
@@ -129,11 +76,24 @@ class ProcessManager : public ProcessManagerInterface
...
+    void removeUnresponsiveProcesses() noexcept;
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:89]: You're right. Following the "Write down, what's inside" paradigm I've renamed it to `printWarningForRegisteredProcessesAndClearProcessList()`

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 28]
```diff
@@ -821,9 +703,11 @@ popo::PublisherPortData* ProcessManager::addIntrospectionPublisherPort(const cap
     return maybePublisher.value();
 }
 
-RouDiProcess* ProcessManager::getProcessFromList(const ProcessName_t& name) noexcept
+bool ProcessManager::searchForProcessAndThen(const ProcessName_t& name,
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp:614]: You're right, that's not consistent with our functional approach. However, I'd rather avoid the extra work here. The `ProcessManager` will be completely re-written with #611 anyway.

File: iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp [hunk 29]
```diff
@@ -0,0 +1,120 @@
...
+TEST_F(ProcessManager_test, RegisterSameProcessTwiceLeadsToError)
+{
+    auto result1 = m_sut->registerProcess(m_processname, m_pid, m_user, m_isMonitored, 1U, 1U, m_versionInfo);
+    auto result2 = m_sut->registerProcess(m_processname, m_pid, m_user, m_isMonitored, 1U, 1U, m_versionInfo);
+
+    EXPECT_TRUE(result1);
+    EXPECT_FALSE(result2);
+}
+
+TEST_F(ProcessManager_test, RegisterSameProcessTwiceWithoutMonitoringLeadsToError)
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp:96]: Correct, fixed.

File: iceoryx_posh/source/runtime/ipc_interface_base.cpp [hunk 30]
```diff
@@ -120,7 +120,7 @@ bool IpcInterfaceBase::send(const IpcMessage& msg) const noexcept
         if (error == posix::IpcChannelError::MESSAGE_TOO_LONG)
         {
             const size_t messageSize =
-                static_cast<size_t>(msg.getMessage().size()) + posix::MessageQueue::NULL_TERMINATOR_SIZE;
+                static_cast<size_t>(msg.getMessage().size()) + IpcChannelType::NULL_TERMINATOR_SIZE;
```
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/source/runtime/ipc_interface_base.cpp:123]: I know what you mean and it seems redundant here. However, imagine we add a third IPC mechanism and this one behaves different. Therefore I'd like to keep this open in the abstraction.

File: iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py [hunk 31]
```diff
@@ -62,12 +62,12 @@ def generate_test_description():
         sigterm_timeout='20')
 
     return launch.LaunchDescription([
+        roudi_process,
```
Comment (elBoberido) [inline iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py:65]: please revert this. It must be possible to start the applications before RouDi and this should also be tested

Comment (dkroenke) [reply iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py:65]: The integrationtest is starting the processes simultaneously and as we know RouDi takes some time for starting up, in the meantime the apps wait patiently if RouDi has started.
Log from test startup in waitset example:
```bash
[INFO] [launch]: Default logging verbosity is set to INFO
test_roudi_ready (test_waitset_example.TestWaitSetExample) ... [INFO] [iox-roudi-1]: process started with pid [25744]
[INFO] [iox-ex-waitset-publisher-2]: process started with pid [25746]
[INFO] [iox-ex-waitset-gateway-3]: process started with pid [25748]
[INFO] [iox-ex-waitset-grouping-4]: process started with pid [25750]
[INFO] [iox-ex-waitset-individual-5]: process started with pid [25753]
[INFO] [iox-ex-waitset-sync-6]: process started with pid [25755]
[iox-roudi-1] 2021-03-22 11:12:28.530 [ Info  ]: No config file provided. Using '/etc/iceoryx/roudi_config.toml'
[iox-roudi-1] Log level set to: [ Debug ]
[iox-roudi-1] 2021-03-22 11:12:28.530 [Warning]: IPC channel still there, doing an unlink of /roudi
[iox-ex-waitset-publisher-2] No server for unix domain socket "/tmp//roudi"
[iox-ex-waitset-publisher-2] 2021-03-22 11:12:28.530 [Warning]: RouDi not found - waiting ...
[iox-ex-waitset-gateway-3] 2021-03-22 11:12:28.530 [Warning]: IPC channel still there, doing an unlink of iox-ex-waitset-gateway
[iox-ex-waitset-gateway-3] 2021-03-22 11:12:28.530 [ Debug ]: reopen RouDi's IPC channel!
[iox-ex-waitset-gateway-3] 2021-03-22 11:12:28.530 [Warning]: RouDi not found - waiting ...
[iox-ex-waitset-grouping-4] 2021-03-22 11:12:28.531 [ Debug ]: reopen RouDi's IPC channel!
[iox-ex-waitset-grouping-4] 2021-03-22 11:12:28.531 [Warning]: RouDi not found - waiting ...
[iox-ex-waitset-individual-5] 2021-03-22 11:12:28.531 [ Debug ]: reopen RouDi's IPC channel!
[iox-ex-waitset-individual-5] 2021-03-22 11:12:28.531 [Warning]: RouDi not found - waiting ...
[iox-ex-waitset-sync-6] 2021-03-22 11:12:28.531 [ Debug ]: reopen RouDi's IPC channel!
[iox-ex-waitset-sync-6] 2021-03-22 11:12:28.531 [Warning]: RouDi not found - waiting ...
[iox-roudi-1] SharedMemory still there, doing an unlink of /iceoryx_mgmt
[iox-roudi-1] Reserving 64550400 bytes in the shared memory [/iceoryx_mgmt]
[iox-roudi-1] [ Reserving shared memory successful ] 
[iox-roudi-1] 2021-03-22 11:12:28.560 [ Debug ]: Registered memory segment 0x7eff8a551000 with size 64550392 to id 1
[iox-roudi-1] SharedMemory still there, doing an unlink of /apex
[iox-roudi-1] Reserving 149134400 bytes in the shared memory [/apex]
[iox-roudi-1] [ Reserving shared memory successful ] 
[iox-roudi-1] 2021-03-22 11:12:28.629 [ Debug ]: Roudi registered payload segment 0x7eff81717000 with size 149134400 to id 2
[iox-roudi-1] RouDi is ready for clients
ok
test_waitset_grouping (test_waitset_example.TestWaitSetExample) ... [iox-ex-waitset-publisher-2] 2021-03-22 11:12:28.730 [ Debug ]: RouDi IPC Channel found!
[iox-ex-waitset-publisher-2] 2021-03-22 11:12:28.730 [Warning]: ... RouDi found.
[iox-ex-waitset-gateway-3] 2021-03-22 11:12:28.730 [ Debug ]: RouDi IPC Channel found!
[iox-ex-waitset-gateway-3] 2021-03-22 11:12:28.730 [Warning]: ... RouDi found.
[iox-ex-waitset-grouping-4] 2021-03-22 11:12:28.731 [ Debug ]: RouDi IPC Channel found!
[iox-ex-waitset-grouping-4] 2021-03-22 11:12:28.731 [Warning]: ... RouDi found.
[iox-ex-waitset-individual-5] 2021-03-22 11:12:28.731 [ Debug ]: RouDi IPC Channel found!
[iox-ex-waitset-individual-5] 2021-03-22 11:12:28.731 [Warning]: ... RouDi found.
[iox-ex-waitset-sync-6] 2021-03-22 11:12:28.732 [ Debug ]: RouDi IPC Channel found!
[iox-ex-waitset-sync-6] 2021-03-22 11:12:28.732 [Warning]: ... RouDi found.
```

**Review by dkroenke — DISMISSED** [review]

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/source/roudi/process_manager.cpp:617]: I just hope this is not one of these provisional solution which hold for ages ;)

File: iceoryx_posh/source/runtime/ipc_interface_creator.cpp [hunk 32]
```diff
@@ -25,6 +25,25 @@ IpcInterfaceCreator::IpcInterfaceCreator(const ProcessName_t& name,
                                          const uint64_t maxMessages,
                                          const uint64_t messageSize) noexcept
     : IpcInterfaceBase(name, maxMessages, messageSize)
+    , m_fileLock(std::move(
+          posix::FileLock::create(name)
+              .or_else([&name](auto& error) {
+                  if (error == posix::FileLockError::LOCKED_BY_OTHER_PROCESS)
+                  {
+                      LogError() << "An application with the name " << name
```
Comment (elBoberido) [inline iceoryx_posh/source/runtime/ipc_interface_creator.cpp:33]: Please use `LogFatal` for `iox::ErrorLevel::FATAL`

File: iceoryx_posh/source/runtime/ipc_runtime_interface.cpp [hunk 33]
```diff
@@ -124,6 +126,7 @@ IpcRuntimeInterface::IpcRuntimeInterface(const ProcessName_t& roudiName,
     switch (regState)
     {
     case RegState::WAIT_FOR_ROUDI:
+        LogError() << "Timeout registering at RouDi. Is RouDi running?";
```
Comment (elBoberido) [inline iceoryx_posh/source/runtime/ipc_runtime_interface.cpp:129]: same here. By default the error handler has `iox::ErrorLevel::FATAL`

File: iceoryx_posh/source/runtime/ipc_runtime_interface.cpp [hunk 34]
```diff
@@ -253,6 +246,15 @@ IpcRuntimeInterface::RegAckResult IpcRuntimeInterface::waitForRegAck(int64_t tra
                     LogWarn() << "Received a REG_ACK with an outdated timestamp!";
                 }
             }
+            else if (stringToIpcMessageType(cmd.c_str()) == IpcMessageType::REG_FAIL_RUNTIME_NAME_ALREADY_REGISTERED)
+            {
+                // RouDi has not yet cleaned up the resources of the app, tell the user to try again later
+                LogError()
```
Comment (elBoberido) [inline iceoryx_posh/source/runtime/ipc_runtime_interface.cpp:252]: and here

File: iceoryx_utils/include/iceoryx_utils/posix_wrapper/file_lock.hpp [hunk 35]
```diff
@@ -45,7 +45,11 @@ enum class FileLockError
     INTERNAL_LOGIC_ERROR,
 };
 
+#if defined(__APPLE__)
+constexpr char PATH_PREFIX[] = "/var/tmp/";
+#else
 constexpr char PATH_PREFIX[] = "/var/lock/";
+#endif
```
Comment (elBoberido) [inline iceoryx_utils/include/iceoryx_utils/posix_wrapper/file_lock.hpp:52]: this is conflicting with #626

File: iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp [hunk 36]
```diff
@@ -67,8 +67,16 @@ class smart_lock
...
   public:
+    ///@brief c'tor creating empty smart_lock
     smart_lock() noexcept;
+
+    ///@brief c'tor constructing the underlying object via copy/move
     smart_lock(const T& t) noexcept;
+
+    ///@brief c'tor forwarding all args to the underlying object
+    template <typename... ArgTypes>
+    smart_lock(ArgTypes&&... args) noexcept;
```
Comment (elBoberido) [inline iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp:78]: I guess the `smart_lock` has no tests which could be extended, right?

File: iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp [hunk 37]
```diff
@@ -0,0 +1,69 @@
...
+
+#include <chrono>
+
+using namespace ::testing;
+using namespace iox;
+using namespace iox::posix;
+using namespace iox::runtime;
+
+constexpr char goodName[] = "channel_test";
+constexpr char anotherGoodName[] = "horst";
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp:30]: so you are claiming "horst" being a good name :laughing:

File: iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp [hunk 38]
```diff
@@ -0,0 +1,119 @@
...
+        m_portManager = std::make_unique<PortManager>(m_roudiMemoryManager.get());
+        m_sut = std::make_unique<ProcessManager>(*m_roudiMemoryManager, *m_portManager, m_compLevel);
+        m_sut->initIntrospection(&m_processIntrospection);
+    }
+
+    void TearDown() override
+    {
+        m_roudiMemoryManager.reset();
+        m_portManager.reset();
+        m_sut.reset();
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp:53]: this is not necessary and also the wrong order. Please remove it

File: iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp [hunk 39]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    const iox::ProcessName_t m_processname{"TestProcess"};
+    const pid_t m_pid{42U};
+    PosixUser m_user{iox::posix::PosixUser::getUserOfCurrentProcess().getName()};
+    const bool m_isMonitored{true};
+    VersionInfo m_versionInfo{42U, 42U, 42U, 42U, "Foo", "Bar"};
+    CompatibilityCheckLevel m_compLevel{CompatibilityCheckLevel::OFF};
```
Comment (elBoberido) [inline iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp:61]: can some of these be moved to `SetUp`?

**Review by elBoberido — COMMENTED** [review]
two files left

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 40]
```diff
@@ -0,0 +1,685 @@
...
+                    // try registration again, should succeed since removal was successful
+                    addProcess(name,
+                               pid,
+                               segmentInfo.m_memoryManager,
+                               isMonitored,
+                               transmissionTimestamp,
+                               segmentInfo.m_segmentID,
+                               sessionId,
+                               versionInfo);
+                    returnValue = true;
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/process_manager.cpp:240]: please change to `returnValue = addProces(...)`

Same 6 lines further down

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 41]
```diff
@@ -0,0 +1,685 @@
...
+                       versionInfo);
+            returnValue = true;
+        });
+
+    return returnValue;
+}
+
+bool ProcessManager::addProcess(const ProcessName_t& name,
+                                const uint32_t pid,
+                                cxx::not_null<mepoo::MemoryManager* const> payloadMemoryManager,
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/process_manager.cpp:262]: please use a `mepoo::MemoryManager&` instead

File: iceoryx_posh/source/roudi/process_manager.cpp [hunk 42]
```diff
@@ -0,0 +1,685 @@
...
+{
+    if (processIter != m_processList.end())
+    {
+        m_portManager.deletePortsOfProcess(processIter->getName());
+        m_processIntrospection->removeProcess(static_cast<int32_t>(processIter->getPid()));
+
+        // Reply with TERMINATION_ACK and let process shutdown
+        runtime::IpcMessage sendBuffer;
+        sendBuffer << runtime::IpcMessageTypeToString(runtime::IpcMessageType::TERMINATION_ACK);
+        processIter->sendViaIpcChannel(sendBuffer);
```
Comment (elBoberido) [inline iceoryx_posh/source/roudi/process_manager.cpp:345]: this should not be done here but in roudi.cpp where also the `runtime::IpcMessageType::TERMINATION` is handled. This method is also called without being invoked by an application

**Review by elBoberido — COMMENTED** [review]
done

File: iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp (hunk 36 above)
Comment (mossmaurice) [reply iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp:78]: Unfortunately not yet, that's something for a "increase coverage" issue.

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 41 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp:262]: You're definitely right. However, this would result in moving the `nullptr` check one level up into `ProcessManager::registerProcess()`. The issue is that `SegmentUserInformation.m_memoryManager` is a pointer. To address that, it would need some bigger rework. I would suggest to stick with the nullptr check inside `addProcess` for now, otherwise it would be done all the time when calling `registerProcess` e.g. with `cxx::Expects(segmentInfo.m_memoryManager != nullptr)`

Comment (elBoberido) [reply iceoryx_posh/source/roudi/process_manager.cpp:262]: We should probably use `std::reference_wrapper` in `SegmentUserInformation`. Could you either do that or create an issue for it/add a task somewhere?

It's used just a couple of times and would probably be quite easy to change.

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 42 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp:345]: Good catch! Unfortunately, at the level of roudi.cpp there is no way of sending a `IpcMessage` to a specific process as the iterator is needed.

I would add a 2nd parameter to `searchForProcessAndRemoveIt(name, DoNotSendAck)` to be able to omit the `TERMINATION_ACK` message. What do you think?

File: iceoryx_posh/source/roudi/process_manager.cpp (hunk 41 above)
Comment (mossmaurice) [reply iceoryx_posh/source/roudi/process_manager.cpp:262]: Add to #611

File: iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp [hunk 43]
```diff
@@ -158,14 +158,17 @@ class ProcessManager : public ProcessManagerInterface
 
     /// @brief Removes the process from the managed client process list, identified by its id.
     /// @param [in] name The process name which should be removed.
+    /// @param [in] sendAckToProcess Informs process that the termination messsage was received
     /// @return Returns true if the process was found and removed from the internal list.
-    bool searchForProcessAndRemoveIt(const ProcessName_t& name) noexcept;
+    bool searchForProcessAndRemoveIt(const ProcessName_t& name, const bool sendAckToProcess) noexcept;
```
Comment (elBoberido) [inline iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp:163]: Please no bool. Do you still know in half a year what `searchForProcessAndRemoveIt(foo, false);` means?

Please create an enum for this.

**Review by dkroenke — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]
