### PR TITLE
iox-#282 Fix deprecated-copy warning

### LINKED ISSUE #282: NewType Copy-Assign raises compiler warning on GCC 8.4.0
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 8.4.0

**Observed result or behaviour:**
The following test for the NewType class in utils causes an incorrect compiler warning:
```
TEST(NewType, CopyAssignableDoesCompile)
{
    Sut<cxx::NewType<int, newtype::ConstructByValueCopy, newtype::CopyAssignable, newtype::Comparable>> a(491), b(492),
        c(423);
    b = a;
    EXPECT_TRUE(a == b);
}
```

The warning "deprecated-copy" is raised at `b = a;` despite the NewType having no deprecated copy constructor.
The source of the error might be elsewhere but this is not clear to me.

GCC 8.4.0 is what is used on the Github Workflow VM so this test causes the build to fail and thus blocks merges.

**Expected result or behaviour:**
This code should compile without warning.

**Conditions where it occurred / Performed steps:**
Compile on GCC 8.4.0

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

This removes the suppression of the `deprecated-copy` warning and add a proper fix

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #282

### CODE REVIEW

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp [hunk 1]
```diff
@@ -54,6 +54,14 @@ namespace cxx
 ///         //                 otherwise the code will not compile
 ///             using ThisType::ThisType;   // this makes all constructors of NewType available for Index
 ///             using ThisType::operator=;  // put the assignment operators in scope
+///
+///             // implement ctors and assignment operators when they are implemented by the base class
+///             // this is necessary pro prevent warnings from specific compilers
```
Comment (elfenpiff) [inline iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp:59]: Do you mean `to prevent warnings`.

What kind of mistake is this when one writes a complete different word ... I say you made a moose.

File: iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp [hunk 2]
```diff
@@ -30,6 +30,14 @@ struct Sut : public T
 {
     using T::T;
     using T::operator=; // bring all operator= into scope
+
+    // implement ctors and assignment operators when they are implemented by the base class
```
Comment (elfenpiff) [inline iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp:34]: You made another moose. 🦌

And as I found out, there is no unicode character for moose... we have to change it

**Comment by elfenpiff** [comment]
https://ctl.s6img.com/society6/img/77g_0kI2lNFRB6YU89e2I6Ary1c/w_700/posters/top/~artwork,fw_2719,fh_3620,fx_122,fy_489,iw_2472,ih_2640/s6-original-art-uploads/society6/uploads/misc/a69ddf38c7c14a89b3e8bd4421bcdd8e/~~/moose-on-vacation-posters.jpg

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp:59]: How about `from some compilers`?

**Review by elfenpiff — APPROVED** [review]

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
