### PR TITLE
Iox #954 use cxx::expected for MemoryManager::getChunk

### LINKED ISSUE #954: Use cxx::expected for MemoryManager::getChunk
## Required information

Currently the `MemoryManager::getChunk` uses a `SharedChunk` initialized with a `nullptr` to indicate an out of chunk error. The usage of surrogates is not encouraged since it is not clear to the user that the method can fail. To make this more clear, the method should use a `cxx::expected`

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

This PR refactors the `MemoryManager::getChunk` method to use the error handling with `cxx::expected`

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #954

### CODE REVIEW

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp [hunk 1]
```diff
@@ -95,6 +95,21 @@ struct success<void>
...
+{
+    static_assert(always_false_v<F> && always_false_v<T>, "Conversion for the specified types is not implemented!");
+}
+
+template <typename T, typename F>
+constexpr T into(const F e)
+{
+    return from<F, T>(e);
+}
+
```
Comment (elBoberido) [inline iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:112]: This will not be merged with this PR. It is just here to show you a concept from Rust which is also used for error handling. There are the `From` and `Into` traits and when `From` is implemented, `Into` is automatically derived. With the `cxx::expected` we often have to pass an error through multiple layers. With this free functions we can create a contract to automate this. One just has to implement
```cpp
template <>
constexpr Bar from<Foo, Bar>(Foo f) {...}
```
and could then just do a `return cxx::error<Bar>::from(expectedWithFooError.get_error());` (note, this `from` is a different one than the one from above, but calls the one from above)

Additionally one can just call `auto barError = into<Bar>(fooError);`

If you agree that we should discuss this further, I will create an issue for this.

@elfenpiff @dkroenke @FerdinandSpitzschnueffler @mossmaurice @MatthiasKillat

File: iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp [hunk 2]
```diff
@@ -34,6 +34,8 @@ namespace popo
 enum class AllocationError
 {
     INVALID_STATE,
+    NO_MEMPOOLS_AVAILABLE,
+    NO_MEMPOOL_FOR_REQUESTED_CHUNK_SIZE,
```
Comment (elBoberido) [inline iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp:38]: I'm not sure if we need both or could just get along with `NO_MEMPOOLS_AVAILABLE`?

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:112]: The part with the conversion is done with #992.
Do we also want `cxx::error<T>::from(...)` static function?

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 3]
```diff
@@ -299,7 +299,8 @@ class Mepoo_IntegrationTest : public Test
     }
 
     template <uint32_t size>
-    bool sendreceivesample(const int& times)
+    bool sendreceivesample(const int& times,
```
Comment (mossmaurice) [inline iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:302]:
```suggestion
    bool sendReceiveSample(const int& times,
```

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 4]
```diff
@@ -401,21 +424,19 @@ TEST_F(Mepoo_IntegrationTest, WrongSampleSize)
     MemPoolInfoContainer memPoolTestContainer;
     auto testMempoolConfig = defaultMemPoolConfig();
     SetUp(memPoolTestContainer, testMempoolConfig, configType::CUSTOM);
-    constexpr int samplesize3 = 2048;
-    const int repetition3 = 1;
-    auto errorHandlerCalled{false};
-    iox::Error receivedError{iox::Error::kNO_ERROR};
+    constexpr int samplesize = 2048;
```
Comment (mossmaurice) [inline iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:427]:
```suggestion
    constexpr int SAMPLE_SIZE = 2048;
```

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp (hunk 3 above)
Comment (mossmaurice) [reply iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:302]: Also, the `int` could be replace with e.g. a `uint32_t` throughout the whole integration test.

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 5]
```diff
@@ -401,21 +424,19 @@ TEST_F(Mepoo_IntegrationTest, WrongSampleSize)
...
+    const int repetition = 1;
```
Comment (mossmaurice) [inline iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:428]: Same as above, replace with `uint32_t`

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 6]
```diff
@@ -299,7 +299,8 @@ class Mepoo_IntegrationTest : public Test
     }
 
     template <uint32_t size>
-    bool sendreceivesample(const int& times)
+    bool sendreceivesample(const int& times,
+                           iox::cxx::optional<iox::popo::AllocationError> expectedAllocationError = iox::cxx::nullopt)
```
Comment (mossmaurice) [inline iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:303]: Nice!

File: iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp [hunk 7]
```diff
@@ -424,20 +445,21 @@ TEST_F(Mepoo_IntegrationTest, SampleOverflow)
...
-         &receivedError](const iox::Error error, const std::function<void()>, const iox::ErrorLevel) {
-            errorHandlerCalled = true;
-            receivedError = error;
+        [&receivedError](const iox::Error error, const std::function<void()>, const iox::ErrorLevel) {
+            receivedError.emplace(error);
         });
 
-    sendreceivesample<samplesize1>(repetition1);
+    // make the mempool empty
+    EXPECT_TRUE(sendreceivesample<samplesize1>(DefaultNumChunks));
```
Comment (mossmaurice) [inline iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp:456]: `DefaultNumChunks` is `constexpr` and should be `ALL_CAPS`

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp [hunk 8]
```diff
@@ -43,14 +43,12 @@ class ShmSafeUnmanagedChunk_test : public Test
     SharedChunk getChunkFromMemoryManager()
     {
         auto chunkSettingsResult = iox::mepoo::ChunkSettings::create(sizeof(bool), alignof(bool));
-        EXPECT_FALSE(chunkSettingsResult.has_error());
-        if (chunkSettingsResult.has_error())
-        {
-            return nullptr;
-        }
+        iox::cxx::Ensures(!chunkSettingsResult.has_error());
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:46]: You could think about adding a message to the user with `iox::cxx::Ensures(!chunkSettingsResult.has_error() && "OMG Why did I fail");`. Same for the other occurrences.

File: iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp [hunk 9]
```diff
@@ -44,6 +45,22 @@ class MemoryManager_test : public Test
         free(rawMemory);
     };
 
+    using ChunkStore = std::vector<iox::mepoo::SharedChunk>;
```
Comment (mossmaurice) [inline iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp:48]: Why not `JunkStore`? :grin:

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+{
+    stream << asStringLiteral(value);
+    return stream;
+}
+
+inline log::LogStream& operator<<(log::LogStream& stream, const MemoryManager::Error value) noexcept
+{
+    stream << asStringLiteral(value);
+    return stream;
+}
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl:51]: I cannot do that since `asStringLiteral` cannot be used as `constexpr` when in a `.cpp` file or at least we will get a compiler warnings which results in an error in the CI

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:112]: The `AllocationError` has errors like `TOO_MANY_CHUNKS_ALLOCATED_IN_PARALLEL` which are not relevant for the `MemoryManager`. When we use one enum for all, we have to check for this error in all places and the user also has to handle this errors even if we condense multiple `MemoryManager::Error` to a single `ApplicationError`. 

The `from`/`into` is just an internal detail to make our live easier and create a consistent way to convert between enums

File: iceoryx_binding_c/test/moduletests/test_publisher.cpp [hunk 11]
```diff
@@ -269,20 +269,17 @@ TEST_F(iox_pub_test, allocate_chunkFailsWhenHoldingToManyChunksInParallel)
...
+    auto chunkSettingsResult = ChunkSettings::create(USER_PAYLOAD_SIZE, iox::CHUNK_DEFAULT_USER_PAYLOAD_ALIGNMENT);
+    ASSERT_FALSE(chunkSettingsResult.has_error());
+    auto& chunkSettings = chunkSettingsResult.value();
 
-        auto sharedChunk = m_memoryManager.getChunk(chunkSettings);
-        if (sharedChunk)
-            chunkBucket.emplace_back(sharedChunk);
-        else
-            break;
+    std::vector<SharedChunk> chunkBucket;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_binding_c/test/moduletests/test_publisher.cpp:278]: In other tests `chunkStorage` is used. I could use that for consistency

File: iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl [hunk 12]
```diff
@@ -19,6 +19,27 @@
...
+from<mepoo::MemoryManager::Error, popo::AllocationError>(const mepoo::MemoryManager::Error e)
+{
+    switch (e)
+    {
+    case mepoo::MemoryManager::Error::NO_MEMPOOLS_AVAILABLE:
+        return popo::AllocationError::NO_MEMPOOLS_AVAILABLE;
+    case mepoo::MemoryManager::Error::NO_MEMPOOL_FOR_REQUESTED_CHUNK_SIZE:
+        return popo::AllocationError::NO_MEMPOOL_FOR_REQUESTED_CHUNK_SIZE;
+    case mepoo::MemoryManager::Error::MEMPOOL_OUT_OF_CHUNKS:
+        return popo::AllocationError::RUNNING_OUT_OF_CHUNKS;
```
[the remark this answers is not in the document]
Comment (elBoberido) [reply iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl:35]: This is just the mapping of `MemoryManager::Error` to `AllocationError`. The latter one has more errors than the former one.

File: iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp (hunk 8 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp:46]: The only thing I could add is something like `This should never happen!`. It is there because I`m a chicken and didn't just want to use `.value()`. But for such cases I think we should add an `T& expects(cxx::string)` to the `optional` and `expected`. This would have the same result and is nicer to use in tests where this values are under our control and we can actually expect that they don't fail but somehow want to appease the inner chicken.

File: iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp (hunk 9 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp:48]: I'll use `chunkStore` which is already used in another test

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp [hunk 13]
```diff
@@ -17,7 +17,9 @@
 #ifndef IOX_HOOFS_CXX_HELPLETS_HPP
 #define IOX_HOOFS_CXX_HELPLETS_HPP
 
-#include <assert.h>
+#include "iceoryx_hoofs/cxx/type_traits.hpp"
```
Comment (elBoberido) [inline iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp:20]: This is part of another PR, so please ignore helplets and type_traits changes. They will disappear once the other PR is merged

File: iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp (hunk 9 above)
Comment (elBoberido) [reply iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp:48]: I should read and think before responding 😁

File: iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl (hunk 10 above)
[the remark this answers is not in the document]
Comment (mossmaurice) [reply iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl:51]: If an implementation does not depend on a template parameter it should be moved to the `.cpp`.

Please move the functions like this:

```
diff --git a/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp b/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
index 026865823..82e3f53b5 100644
--- a/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
+++ b/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
@@ -105,13 +105,13 @@ inline constexpr const char* asStringLiteral(const MemoryManager::Error value) n
 /// @param[in] stream sink to write the message to
 /// @param[in] value to convert to a string literal
 /// @return the reference to `stream` which was provided as input parameter
-inline std::ostream& operator<<(std::ostream& stream, const MemoryManager::Error value) noexcept;
+std::ostream& operator<<(std::ostream& stream, const MemoryManager::Error value) noexcept;
 
 /// @brief Convenience stream operator to easily use the `asStringLiteral` function with iox::log::LogStream
 /// @param[in] stream sink to write the message to
 /// @param[in] value to convert to a string literal
 /// @return the reference to `stream` which was provided as input parameter
-inline log::LogStream& operator<<(log::LogStream& stream, const MemoryManager::Error value) noexcept;
+log::LogStream& operator<<(log::LogStream& stream, const MemoryManager::Error value) noexcept;
 
 } // namespace mepoo
 } // namespace iox
diff --git a/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl b/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl
index 97feb1deb..f0954e874 100644
--- a/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl
+++ b/iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl
@@ -21,6 +21,7 @@ namespace iox
 {
 namespace mepoo
 {
+
 inline constexpr const char* asStringLiteral(const MemoryManager::Error value) noexcept
 {
     switch (value)
@@ -38,18 +39,6 @@ inline constexpr const char* asStringLiteral(const MemoryManager::Error value) n
     return "[Undefined MemoryManager::Error]";
 }
 
-inline std::ostream& operator<<(std::ostream& stream, const MemoryManager::Error value) noexcept
-{
-    stream << asStringLiteral(value);
-    return stream;
-}
-
-inline log::LogStream& operator<<(log::LogStream& stream, const MemoryManager::Error value) noexcept
-{
-    stream << asStringLiteral(value);
-    return stream;
-}
-
 } // namespace mepoo
 } // namespace iox
 
diff --git a/iceoryx_posh/source/mepoo/memory_manager.cpp b/iceoryx_posh/source/mepoo/memory_manager.cpp
index b555f2b62..cc748ad06 100644
--- a/iceoryx_posh/source/mepoo/memory_manager.cpp
+++ b/iceoryx_posh/source/mepoo/memory_manager.cpp
@@ -207,5 +207,17 @@ cxx::expected<SharedChunk, MemoryManager::Error> MemoryManager::getChunk(const C
         return cxx::success<SharedChunk>(SharedChunk(chunkManagement));
     }
 }
+
+std::ostream& operator<<(std::ostream& stream, const MemoryManager::Error value) noexcept
+{
+    stream << asStringLiteral(value);
+    return stream;
+}
+
+log::LogStream& operator<<(log::LogStream& stream, const MemoryManager::Error value) noexcept
+{
+    stream << asStringLiteral(value);
+    return stream;
+}
 } // namespace mepoo
 } // namespace iox
```

**Review by mossmaurice — COMMENTED** [review]
LGTM, two minor findings.

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp [hunk 14]
```diff
@@ -123,6 +124,12 @@ struct error
     template <typename... Targs>
     error(Targs&&... args) noexcept;
 
+    template <typename F>
+    static error<T> from(F e)
+    {
+        return error(cxx::from<F, T>(e));
+    }
+
```
Comment (elBoberido) [inline iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:132]: I'll remove this from the current PR since it is not related to the issue but I would like to introduce this as feature in another PR. Any objections?

**Review by mossmaurice — APPROVED** [review]
LGTM

File: iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp (hunk 14 above)
Comment (mossmaurice) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:132]: @elBoberido For me, it's ok to introduce it as part of this PR.

Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:132]: Well, I would have to create tests and add documentation. For traceability it would also not quite fit to this issue

Comment (mossmaurice) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp:132]: Why not add a link to the follow-up issue here and maybe also as a `/// @ todo` in code? That workflow is ok for me as long as one continues to work on the follow-up in the next few weeks.

Comment (elBoberido) [reply iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp]: done with #1012

File: iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl [hunk 15]
```diff
@@ -105,7 +128,8 @@ ChunkSender<ChunkSenderDataType>::tryAllocate(const UniquePortId originId,
         }
         else
         {
-            return cxx::error<AllocationError>(AllocationError::RUNNING_OUT_OF_CHUNKS);
+            /// @todo iox-#1012 use cxx::error<E2>::from(E1); once available
```
Comment (mossmaurice) [inline iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl:131]: :+1: :pray:

**Review by mossmaurice — APPROVED** [review]

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
